### ISSUE TITLE
[Feature Request] apk on F-Droid

### ISSUE THREAD

**Issue by DistantParadox** [popcorn-official/popcorn-android#1]
Uploading this to the F-Droid app market for Android would help to bring it to many users, since the Google Play store would most likely reject it.  Also, it would bring Popcorn Time to less tech-savvy users who would be able to download it directly from F-Droid.

**Comment by pct-team** [comment]
We have our own updater, F-Droid would ruin that. So the answer is no.

**Comment by fazlerabbi37** [comment]
@MrRory how does that updater works and how would F-Droid ruin it? Would you please explain? Many of us depends on F-Droid to get a complete FLOSS and trusted apps so inclusion to F-Droid would be a very appreciated step.

**Comment by fazlerabbi37** [comment]
I have opened an [issue](gitlab.com/fdroid/rfp/-/issues/1290) in the Requests For Packaging (RFP) repo in the F-Droid repo and got the response that all it needs are:
- Providing the Fastlane structure of the app
- Changing the `versionCode` to be static
- And tagging the releases 

The app doesn't have any non-free dependency which is really awesome. Now the only barrier to inclusion in F-Droid are those small things. Hope to see this resolved!

I must apologize first for this sudden mention but I hope you would understand my desperation as I haven't seen any contributor comment in any issue for long time. So if you can shade any light on this or can mention to any active contributor (or worse case, if this is being developed in any other repo, a pointer to that), I would really appreciate it. 

[mentioning top 5 contributors from [Insights](https://github.com/popcorn-official/popcorn-android/graphs/contributors)]
cc: @vzamanillo @MrRory @se-bastiaan @MrAdder @team-pct


If you have any addition query, I am sure @IzzySoft (F-Droid contributor) would happy to help.

**Comment by IzzySoft** [comment]
Well, F-Droid wouldn't "ruin" your updater – it would ask you to disable it.

Background: F-Droid builds the app from source and signs it – obviously not with the author's key which we don't have access to. So when installed from F-Droid, one cannot update from a different source.

This is the way it was done for several apps which ship their own update mechanism. And honestly, I think this is fair – looking at the tags update frequency of Popcorn, I don't see why a separate updater would be an urgent issue. Yes, updates from F-Droid can take between 1 day and 1 week on average – but the last update here was … when? According to tags, in 2016 (the last version from 1/2019 wasn't even tagged).

So while on it, may I asked whether this app is still maintained at all? Last commit was more than a year ago.

**Comment by se-bastiaan** [comment]
It would be highly appreciated if you would mind not mentioning people that once upon a time contributed to the _upstream_ project.

**Comment by nicolasmaia** [comment]
I've split them into different bug reports: #673 #874 #675

**Comment by supermamie** [comment]
Just my 2 cents : having a F-Droid build is also a security measure foe some people, as it guarantee that the builded APK is really from the source code (Only 1 structure to trust : F-Droid).
Having your own builds force me to trust you that you did not add some code to the build that is not in the published source.

**Comment by IPv777** [comment]
@MrRory +1 for F-Droid, the FLOSS community would appreciate that ! ;)
