### ISSUE TITLE
version 2.8 of the android does not show streaming option to Chromecast

### ISSUE THREAD

**Issue by brunobsouzac** [popcorn-official/popcorn-android#10]
version 2.8 of the android does not show streaming option to Chromecast

I wish I could watch my TV series for Chromecast, but does not appear this option as the old app .io

I tested the 2.7 apk app popcorntimece.ch and their shows only tablet but not in other smartphones.

Even has option to switch to the chromecast while you watch the video.

I would ask for that adicionassem it all in version 2.9 of the .sh and option to change the caption and size of the legend after you are already doing streaming.

Note: there is a very annoying flaw of green pixels in video

Sorry for the translation.

**Comment by pct-team** [comment]
What is your problem exactly?

**Comment by jagomf** [comment]
As the title says, the important issue here is to be able to cast to a Chromecast device.

**Comment by brunobsouzac** [comment]
The chromecast button does not appear.


And the suggestion appears the same icon in the popcorn time the player with option to change the label and the size of it.

**Comment by pct-team** [comment]
The first thing has been confirmed working, if it's not then check your network configuration.
The second thing is not possible at all.
