### ISSUE TITLE
The vídeos in app are with distorted images

### ISSUE THREAD

**Issue by anapaularsena** [popcorn-official/popcorn-android#104]
Version: 0.2.9 - armeabi-v7a
Download date: 9 dec. 2016
Android version: 6.0.1

I have Moto G4 Play, all the above informations. Well, when I click on a vídeo,  the app make download normally, the problem is that when I'm going to go watch the images get distorted and shuffled, making it impossible to watch.

**Comment by MrRory** [comment]
Please use the full issue report form.
