### ISSUE TITLE
 dlna not work

### ISSUE THREAD

**Issue by titobadadi** [popcorn-official/popcorn-android#115]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by titobadadi** [comment]
yo estoy intentando conectar el tlf por dlna al tv. el programa si que encuentra el tv pero no se conecta nunca. mi tv el un televisor philips con smart and android tv serie 8000.
también estaría muy interesante que se pudiera conectar el programa por Chromecast.
gracias

**Comment by MrRory** [comment]
English.
