### ISSUE TITLE
Download Folder

### ISSUE THREAD

**Issue by dkirbyechs** [popcorn-official/popcorn-android#117]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...
Clear Temporary Files

#### Actual Behaviour

...
Every time I open the app, even just to browse, it fills my Downloads folder with "temporary" files that I have to delete manually.

#### Steps to repoduce the behaviour

Open app, browse, close app, check Downloads folder.

1. ...
2. ...
3. ...

**Comment by MrRory** [comment]
you need to be more specific
