### ISSUE TITLE
Time moves but video loading.

### ISSUE THREAD

**Issue by endriklos977** [popcorn-official/popcorn-android#118]
Version:  Current latest
Download date:  24-12-2016
Android version:  6.0.1

#### Expected Behaviour

If seeking forward, video would stop, load and time would stop.

#### Actual Behaviour

While video is black and audio silent (hasn't downloaded to the point yet), time goes on and subtitles still appear, making it nearly impossible for the video to catch up.

#### Steps to repoduce the behaviour

1. Have mediocre wifi.
2. Seek to near the end of a show
3. See the time moving but no video or audio

Thus was already reported I think but not enough details.

**Comment by luis02lopez** [comment]
Same here.

**Comment by MrRory** [comment]
The video will never catch up because seeking is not really supported, it won't try to catch up to the point you've changed the progress to. It'll take a looooooooooooooong time before it'll continue the video since it has to download everything from start to end first.

**Comment by luis02lopez** [comment]
So why you close it, if it isn't solved?...

**Comment by MrRory** [comment]
Because it is expected behaviour.

**Comment by luis02lopez** [comment]
@MrRory If the misbehave is expected doesn't mean it's good or solve.
