### ISSUE TITLE
Cache full in unotec tvibox II

### ISSUE THREAD

**Issue by xungarro** [popcorn-official/popcorn-android#121]
Version:  
Version 2.9 for android (0.2.9-armeabi-v7a)

Download date:  
28-12-15

Android version:  
4.2.2

#### Expected Behaviour
Stream buffering normal. Can change buffering path to another directory without issues.
...

#### Actual Behaviour
The stream buffering fills quickly the 1g ram temp cache of the unotec tvibox II androidtv device stopping playback (at 30 minutes aprox) 
When trying to change the cache path to an internal storage directory the preload fails. It remains loading for a while without reaching 0%. 
In the new path created (The app can properly create a folder named Popcorn Time) are some txt files and an empty directory but no video file is downloaded.

#### Steps to repoduce the behaviour

1. Playing a unotec tivibox II with automatic caché file management option, (After 30 minutes a warning message of Insufficient memory will be displayed and then it will stop playback)
2. When you try to manually redirect path to another (non temp) directory the preloads don't work.
3. In addition. Directories located in external devices (such as USB storages or SD cards) are NOT elegible to cach tmp files. The app can't even write the Popcorn Time folder.

**Comment by MrRory** [comment]
> The stream buffering fills quickly the 1g ram temp cache
RAM? there is no cache, video's are downloaded to disk
make sure the directory you selected is writable by the app

**Comment by xungarro** [comment]
Hi!
The app is configured by default (and automatically) to save the video download stream in a tmp folder called (/data/data/pct.droid/cache). That is the UNOTEC 1gb RAM memory. Aditionally, the device have a internal storage drive of 8gb, but when you redirect manually to any folder there all the preloads fail, they get stucked at 0%. 
Folders located in mounted external devices (such as USB storages or SD cards) are NOT elegible to cach the files. The app can't even write a Popcorn Time folder.
So the problem is that if you leave the auto folder cache enabled the 1gb RAM of the device only allows you to charge 30-40 minutes of video, after that a message of "cache memory full" is displayed. There's no functional way to change path and allow full download neither in internal memory or mouted drivers.

**Comment by MrRory** [comment]
I believe you do not understand the difference between RAM and the internal storage. There is literally no way `/data/data/` is located in the _RAM_ of your device. That is always the internal storage.

It's definitely possible that any other folder won't work, that it because they're not writable by the application. If the SD card is mounted to `/sdcard/` then it's possible that locating the folder there works, if not then it won't be writable at all.

Can you provide a full overview of your device's storage system?

**Comment by xungarro** [comment]
Yes, that's it. 
But it seems that UNOTEC have two partitions, one of 1gig and other of 4gig mounted as a sd card.
Anyway. This is the folder tree as it can be accesed from popcorn time: 
/acct
/cache
/config
/d
/data
/databk
/dev
/etc
/mnt
/proc
/root
/sdcard
/storage
/sys
/system
/vendor

The automatic folder (/data/data/pct.droid/cache) is not elegible manually, cause you cannot enter inside of /data folder to explore subfolders. I checked all the rest of folders to save the video download, and I encountered any of the two errors listed above: device cannot write in the folder and is not ellegible or device make the folder ellegible but stucks on preloading any film (only downloads a jpg file, a sub folder and txt files).

When inside /mnt/ folder you can acces:

/mnt/asec/
/mnt/extsd/
/mnt/media/
/mnt/obb/
/mnt/private/
/mnt/sdcard/
/mnt/secure/
/mnt/shell/
/mnt//usbhost1/
/mnt//usbhost2/
/mnt//usbhost3/
/mnt//usbhost4/

That are the mounted usb's, and the local memory folder /mnt/sdcard. But here we're encountering the same problems.

**Comment by MrRory** [comment]
I've got no idea what's going wrong here, but if `/sdcard` and thus probably `/mnt/sdcard/` is unwritable then I think its something about system rules and we can't change those. :/

**Comment by xungarro** [comment]
Ok, 
Yes, it seems that.
But what seems strange to me is that /sdcard and /mnt/sdcard/ are ellegible, and the program can truly write something on them.  The app can create a folder named Popcorn Time and some txt files and an empty directory named /sub/ are deployed there, but no video file is downloaded. It only stucks on preloading any film.
Anyway Thank you for your kind support !
Best
