### ISSUE TITLE
SD Card not available to choose as cache directory

### ISSUE THREAD

**Issue by TizianoVecellio** [popcorn-official/popcorn-android#122]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

Let me pick my SD card as cache directory.

#### Actual Behaviour

It doesn't show the SD card as an option.

#### Steps to repoduce the behaviour

1. Go to preferences
2. Try to change cache directory
3. Tap the up button.

**Comment by vzamanillo** [comment]
dup  #71
