### ISSUE TITLE
Torrent search feature

### ISSUE THREAD

**Issue by faroutxxx** [popcorn-official/popcorn-android#123]
On the desktop version there is a "search for torrent" feature under the folder icon button ("Torrent collection") next to the heart/favourite icon. This is a really useful feature as it searches other sources outside of the default catalogue. To me this is the most widely used feature because the default source catalogue (which you have no control over) does not update quickly enough with the newest episodes of series or newest movies. Sometimes takes months to update making Popcorntime for Android useless for regular use.

Unfortunately this feature seems to be missing on the mobile android version (I dont know about andoidTV and if in fact its a separate version).

Please add this feature as a priority I really think it makes the android version kind of useless when the default catalogue only updates on a monthly basis if at all.

**Comment by MrRory** [comment]
Imho: this feature would not add anything useful and is too complicated to support. You can just go to your favorite neighbourhood torrent website and open the magnet link.

**Comment by faroutxxx** [comment]
feature is widely used on desktop because sources are months behind. This update problem is killing popcorntime!

do you want to crawl through a virus infested torrent website to get magnet links on an android phone?

why would it be complicated when the desktop version is doing exactly the same thing!

**Comment by MrRory** [comment]
Because there are no _real_ APIs. that some desktop developer decided that it was a good idea doesnt mean we have to agree

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/torrent-search-feature/115
