### ISSUE TITLE
Not working in Android 7.1.1 & keep crashing

### ISSUE THREAD

**Issue by Projectro** [popcorn-official/popcorn-android#125]
Version:  mobile-armeabi-v7a-release-0.2.9
Download date:  5 January 2017
Android version:  7.1.1 (Nexus 9)

#### Expected Behaviour
Should take to the default screen
...

#### Actual Behaviour
It takes me to the default screen then with-in quarter seconds it crashes everytime.
...

#### Steps to repoduce the behaviour

1. Use Nexus 9(7.1.1)
2. AFTER downloading popcorntime, it will show error and start downloading the correct version itself.
3. after this it crashes everytime.

**Comment by vzamanillo** [comment]
Did you try with the [latest build](https://ci.popcorntime.sh/job/Popcorn-Time-Android/)?

**Comment by Projectro** [comment]
@vzamanillo Yes.... Latest Popcorntime v2.9...

**Comment by vzamanillo** [comment]
What is the build number? 135? Check the above link.

**Comment by hmbto** [comment]
Running same app version on nexus 6 7.1.1_r4, working fine.

**Comment by vzamanillo** [comment]
@hmbto, thank you, closing due to not enough information, @Projectro, check with the latest 135 build, if the app is still failing I will re-open the issue.

**Comment by computersteve** [comment]
This happens on the nexus player as well.
