### ISSUE TITLE
Problem in enable proguard 

### ISSUE THREAD

**Issue by aliahmaed** [popcorn-official/popcorn-android#127]
i cant make proguard the mobile apk why ???

**Comment by vzamanillo** [comment]
We need more information to do a diagnostic about the problem, post it, please.

**Comment by aliahmaed** [comment]
i put in build.gradle of mobile this code to enable proguard 
buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".dev"
        }

when i need to generate signed apk , i cant and this problem that appear : 
Error:Execution failed for task ':mobile:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Please correct the above warnings first.

**Comment by MrRory** [comment]
you're not helping by posting this, plus: this is not a 'how to build' helpdesk
if you want proguard to work then you'll have to figure out yourself, we don't have any use for it except for maybe creating smaller APKs. but there are more important things to fix first
