### ISSUE TITLE
DLNA not working in LG LA6200-SA Tv

### ISSUE THREAD

**Issue by nmanuelides** [popcorn-official/popcorn-android#128]
Version:  0.2.9 -arm64-v8a
Download date:  January 2017
Android version:  6.0

#### Expected Behaviour

start streaming to my smart tv

#### Actual Behaviour

a sign with 6 numbers appeared on the TV like if it was a paring code, but there was no place to input that code on the app

#### Steps to repoduce the behaviour

1. Open the app
2. open a movie 
3. touch play 
4. once available touch the DLNA icon at the top right

**Comment by danton721** [comment]
+1 with LG TV too

**Comment by MrRory** [comment]
Subissue, kind of, of #83
