### ISSUE TITLE
Weird thing is happening with subtitle time settings

### ISSUE THREAD

**Issue by candh** [popcorn-official/popcorn-android#13]
When the subtitle timing is set to a negative number such as -15 or something. It works good.
But, when the timing settings is opened again to reconfigure the timing, it somehow jumps to a big negative number starting with the first two integers that was first set. Like -1500...

**For Example**
I set it to -16 initially...
![screenshot_2016-02-28-16-33-46](https://cloud.githubusercontent.com/assets/11281452/13378958/989b39c0-de39-11e5-887a-fbfd9d0443bb.png)
and when I opened it again, it jumped to a big negative number.
![screenshot_2016-02-28-16-34-05](https://cloud.githubusercontent.com/assets/11281452/13378956/80299ed6-de39-11e5-842f-81ae9466c305.png)

**Comment by mathieuzen** [comment]
Managed to find a workaround when running on the nexus player (i was unable to delay subtitles before that) by using an EditText widget instead of NumberPicker in NumberPickerDialogFragment.java as shown below:


    import android.widget.EditText;

...

    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());

        if (getArguments() == null || !getArguments().containsKey(TITLE) || mOnResultListener == null) {
            return builder.create();
        }

        final EditText numberPicker = new EditText(getActivity());

        final int currentValue = getArguments().getInt(DEFAULT_VALUE);

        builder
                .setView(numberPicker)
                .setTitle(getArguments().getString(TITLE))
                .setPositiveButton(R.string.ok,
                        new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                mOnResultListener.onNewValue(Integer.parseInt(numberPicker.getText().toString()));
                                dialog.dismiss();
                            }
                        })
                .setNegativeButton(R.string.cancel,
                        new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                dialog.dismiss();
                            }
                        }
                );

        return builder.create();
    }

then rebuild the apk and install to get this (not so nice though but it works):

![screenshotpopcorntime-numberpicker](https://cloud.githubusercontent.com/assets/2734266/18285920/cf97af62-7470-11e6-9c00-6ddb7bab986d.png)

**Comment by imurreflection** [comment]
Hi mate, I know its quite late to ask this question but looking at the response above, I can see that you are the man. Please help, I have been requesting these developers for a long time but its of no use. All I am looking for is to include subtitles position in subtitles  settings as they kind of come in between movie and its like hell. Please help me or teach me how to accomplish this task as I m sure these people will never listen. Please help

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/weird-thing-is-happening-with-subtitle-time-settings/111
