### ISSUE TITLE
Development version crashes and glitches video

### ISSUE THREAD

**Issue by TizianoVecellio** [popcorn-official/popcorn-android#131]
Version:  0.2.9 development 136
Download date:  09.01.2017
Android version:  6.0

#### Expected Behaviour

When I clicked play I expected the torrent to start like it normally does and then switch to my external player (MX Player). This works fine in the release version.

#### Actual Behaviour

In the dev 136 version however, when I click play the app often stops responding. When it doesn't, it does start the torrent (but very slowly, hanging on "starting buffering" for a long time) but when it opens the video in the player (external or internal) the image glitches out. I can still hear the sound and the subtitles are there, but the image goes all blocky and I can see some frames from other parts of the film on top of each other. 

The SD card issue has been fixed however. This bug happens no matter where my cache location is set to.

#### Steps to repoduce the behaviour

1. Start any torrent
2. ...
3. ...

**Comment by Idan345** [comment]
Having the same issue on android TV (actually android tv version :) ) version 6.0.1
works very much ok on my Philips android tv version 5.1

the last version which works somewhat normally on 6.0.1 (for me) is 119

**Comment by computersteve** [comment]
Dev version not working at all for me on Nexus Player crashing as soon as I open it =(

**Comment by MrRory** [comment]
It's a development version for a reason. We cannot guarantee that it is stable.
