### ISSUE TITLE
streaming mobile data

### ISSUE THREAD

**Issue by Svenson01** [popcorn-official/popcorn-android#133]
Version:  0.2.9 - armeabi-v7a
Download date:  1.79 GB
Android version:  5.0

#### Expected Behaviour
the mobile app wat set to only streaming over wifi

#### Actual Behaviour
due to bad wifi-reception all the mobile data was used - setting were set to only streaming over wifi!
...

#### Steps to repoduce the behaviour

1. Find error
2. Fix error
3. Report wen fixed

**Comment by vzamanillo** [comment]
Thank you, it is an awesome bug
