### ISSUE TITLE
Bug when the movie starts, the screen gets green and bug

### ISSUE THREAD

**Issue by Al3isterC** [popcorn-official/popcorn-android#135]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. open app
2. choose a movie
3. wait movie starts, then it bugs

**Comment by danton721** [comment]
+1
Version: 0.2.9-arm64-v8a
Android 5.1.1
TV Show: The Royals 3x4

Screen flickers with green color, movie and pixels acting weird

**Comment by MrRory** [comment]
Please fill in the complete report.
