### ISSUE TITLE
popcorn bugs

### ISSUE THREAD

**Issue by SirAndyWillis** [popcorn-official/popcorn-android#136]
Version:  latest :)
Download date:  10.1.2017
Android version:  6.0.1

#### Expected Behaviour

...i was expecting to be able to browse through movies genres and "forward" on some movies.

#### Actual Behaviour

...i cannot browse between genres. and i can't forward to a specific point of the movie. the app lags and "cracks"..shuts down etc.

#### Steps to repoduce the behaviour

1. ...simply try to browse though movie genres
2. ...or try to go to a specific point of the movie
3. ...
 PS: i use a Samsung Galaxy A3 (2014) android 6.0.1 latest updates. (1.5GB RAM and 2-3 Free GB of memory) if that helps you. 0:)

**Comment by MrRory** [comment]
Unclear what the bug is
