### ISSUE TITLE
Trailers don't work on Android TV

### ISSUE THREAD

**Issue by computersteve** [popcorn-official/popcorn-android#137]
Version:  tv-x86-release-0.1.4
Download date:  1/18/17
Android version:  7.1.1

#### Expected Behaviour
I expect that when I click the movie, and the window pop up loads a link that shows play trailer then when I select that the trailer plays.. this does not happen.
...

#### Actual Behaviour
Instead You get A Message Saying Error Loading Media.. 
...

#### Steps to repoduce the behaviour

1. Start PopCornTime 
2. Select Any Show Or Movie Trailer 
3. See Result

**Comment by ChrisAlderson** [comment]
#53

**Comment by computersteve** [comment]
Just wanted to say in the older builds Trailers do work for the movies??? is this not fixable then?
