### ISSUE TITLE
Subtitles issue

### ISSUE THREAD

**Issue by bojan2109** [popcorn-official/popcorn-android#139]
Version:  tv-armeabi-v7a-release-0.1.4
Download date:  1/19/2017
Android version:  5.0

#### Expected Behaviour
Choose subtitles from list 
...

#### Actual Behaviour
Not showing subtitles at all. Only two options, choose subtitle, custom subtitles.. Neither works
When choosing custom and load it , nothing shows.
...

#### Steps to repoduce the behaviour
Choose CC then subtitle language > no subtitles...

**Comment by computersteve** [comment]
just curious other than that is it working for you??? like does the app crash and if so what device are you using.. I think it would help developers if they knew what devices the app was working on or not =)

**Comment by MrMysakovich** [comment]
Install classic android version. It is much better

**Comment by turanemre** [comment]
I have the same problem

**Comment by MrRory** [comment]
@ChrisAlderson did we loose access to the opensubs api?

**Comment by MrRory** [comment]
seems like the yifysubs api is broken, thus switched to opensubs now
