### ISSUE TITLE
Certain movies get stuck on starting buffering 

### ISSUE THREAD

**Issue by computersteve** [popcorn-official/popcorn-android#142]
Version:0.1.4  
Download date:  1/21/16
Android version:  7.1.1

#### Expected Behaviour
Try to play Captain America: Civil War or Suicide Squad : 1080P

#### Actual Behaviour
The app gets stuck on Starting Buffering and never changes to loading 

#### Steps to repoduce the behaviour
Certain movies do not work if you pick 1080P I notice if I play the same movie on 720p then it might load sometimes...

**Comment by MrRory** [comment]
This is always possible and is caused by your internet connection or the health of the torrent. We cannot fix these specific issues.

**Comment by computersteve** [comment]
to be honest I just tried a different branch of popcorn time (https://popcorn-time.to) and there was no problem loading both these torrents..
