### ISSUE TITLE
Can't install DEV version to Mi Box

### ISSUE THREAD

**Issue by marshallCZE** [popcorn-official/popcorn-android#143]
Version:  tv-armeabi-v7a-development-136.apk
Download date:  1/21/2017
Android version:  Android TV 6.0.1 (Mi Box)

#### Expected Behaviour

Smooth installation of v7a version.

#### Actual Behaviour

Wont't even install on Mi Box - says "App Not Istalled". The stable version v1.4 (v7a) can be installed correctly.

#### Steps to repoduce the behaviour

1. Copy APK file (using e.g. ES file explorer)
2. Open the APK a attempt to install (unknowonz sources allowed)
3. ...

**Comment by nextapprage** [comment]
Works for me are you sure you downloaded the correct file also make sure if using USB drive as internal storage you have that USB drive plugged in after you download and install popcorn time or you well are errors ... 
Download arm 7 file 
Try to download the beta dev app you can find that by clicking this link https://is.gd/GahesJ

**Comment by MrRory** [comment]
This is a system issue, not a Popcorn Time issue.
