### ISSUE TITLE
T.v shows problem

### ISSUE THREAD

**Issue by Mmog5** [popcorn-official/popcorn-android#144]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

... When I'm trying to watch a t.v show it always freeze at a random time and will crash the app. The movie works but the t.v show always fail to play the video

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by MrRory** [comment]
Please provide more information
