### ISSUE TITLE
Android TV Must have Features request

### ISSUE THREAD

**Issue by nextapprage** [popcorn-official/popcorn-android#146]
Version:  1.4
Download date:  1/30/17
Android version:  7.0

(Change) default storage from internal to external storage !!!

(Create) My Tv Show's Tab 
"-Favorit TV shows by clicking the Heart on each show before you watch ..
Saves show and automatically toggles with a little number that indicates the number of episodes that are New... Ready to watch ...

Create Favorite Network Tab 
List and Search TV show by Network alternate create by clicking Favorite on any Network to Appear on favorite Networks tab... 

Create a Save to internal Storage for meta Data related to my Favorites and TV show list network list ...

Fix bug where if TV Show or movie is Pulsed for more then 2 minutes popcorn time stops playback buffer and starts movie over from beginning of timeline ...

Create a way for Android TV to display Meta Data onto recommended program to watch on Android TV home screen on top panel also related to that help Android TV when voice search for movie or TV show to search in popcorn time to start playback ....

**Comment by MrRory** [comment]
You can create separate issues for all these things, but please first search if they do not exist already.
