### ISSUE TITLE
External playing on x86 not working

### ISSUE THREAD

**Issue by MrMysakovich** [popcorn-official/popcorn-android#150]
Version:  0.2.9 - x86
Download date:  4.2.2017
Android version:  6.0.1

#### Expected Behaviour
If I use MX Player or VLC. Movie does not start. But If I go to the cache folder and play it. It works.

#### Actual Behaviour
If I use MX Player or VLC. Movie does not start. But If I go to the cache folder and play it. It works.

#### Steps to repoduce the behaviour

1. Install MX Player or VLC and change form internal player to VLC player or MX Player

Problem is not in Arm version. Only in x86.

**Comment by MrRory** [comment]
What's the difference between the expected and actual behaviour? I get the issue but please differentiate next time you use the template.

**Comment by MrMysakovich** [comment]
Expected is normal play movie in external player (on ARM version it is ok).
Actual is that external player only loading and does not play.

Dne 12. 2. 2017 15:22 napsal uživatel "Heat Wave" <notifications@github.com

**Comment by MrMysakovich** [comment]
OK sorry :) I fill it in previous post.

**Comment by MrRory** [comment]
It might be possible that the ARM version of VLC doesn't have the right codec for some reason.
