### ISSUE TITLE
Crashing!!!

### ISSUE THREAD

**Issue by PoopyPantz** [popcorn-official/popcorn-android#151]
So guys IFK what's going on but I just DL popcorn and for some reason it crashes when I go to genres and click on certain ones I.e. documentaries etc. That being said if. You click on any of the rest (besides the few that causes the crash). ...NONE of the genres work. You click it and it highlights but nothing happens....no matter how long u wait.
I'm using the nexus 7 tab BTW. If that helps. Thanx again guys. I'll await your response.  -Ken

Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by MrRory** [comment]
Use the issue template. Then we can help.
