### ISSUE TITLE
Genres

### ISSUE THREAD

**Issue by talyon** [popcorn-official/popcorn-android#153]
Version:  0.2.9 arm64-v8a
Download date:  
Android version:  6.0.1

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by talyon** [comment]
I expected when I click a genre to be taken to a list of movies, shows, or anime of that genre.

Instead, it highlights the genre and does nothing.

1. Click on the genre tab.
2. Click on any genre

**Comment by MrRory** [comment]
Duplicate of #20
