### ISSUE TITLE
Video error when the screen is locked 

### ISSUE THREAD

**Issue by Sewitz** [popcorn-official/popcorn-android#154]
Version:  latest 
Download date:  11th Feb 2017
Android version:  6.1 

#### Expected Behaviour
The app should had played the video but it stuck there and didn't play or else showed an playback error.  
...

#### Actual Behaviour
Show playback error or didnt play at all. 
...

#### Steps to repoduce the behaviour
Lock your phone while the video is playing or paused and try playing the video after unlocking. 😃

1. When the screen is lock replaying the video after unlocking is not doable.. Other than that great work guys.. 
2. ...
3. ...

**Comment by MrRory** [comment]
Version: latest? I can reopen this if you use the complete issue template. I've got no idea what's going on here with this information
