### ISSUE TITLE
External Storage Option

### ISSUE THREAD

**Issue by jjcarloss** [popcorn-official/popcorn-android#155]
Version:  
Download date:  
Android version:  6.0

#### Expected Behaviour

Let me use external storage as cache folder.

#### Actual Behaviour

Do not present that option

#### Steps to repoduce the behaviour

1. Go to settings.
2. Sorage option
3. Can't select Storage options

**Comment by MrRory** [comment]
No version, no download date. Please use the complete issue template and be more specific about what's happening

**Comment by nextapprage** [comment]
I think he's referring to Android TV  6.0 and Android TV app 1.4 current stable release

**Comment by jjcarloss** [comment]
@MrRory :
**Android version**: 6.0
**Apk version** (downloaded from the popcorntime.sh web): **_mobile-armeabi-v7a-release-0.2.9.apk_**
**Issue**: Couldn't find the option to use External sd for cache storage, the up narrow can't go out internal storage.
**Note**: Found that a development **_version mobile-armeabi-v7a-development-0.2.9.apk_** (downloaded 12/03/2017) is implementing this feature, though it seems to have **problems**: 

- it never start buffering films (Inferno, A monster calls, Arrival tested) release version do start buffering,

- and it just can't even launch the buffering activity in a show chapter (Homeland E01S02 for instance), or at least it doesn't show any info showing that it is doing something, just a static picture and doesn't make any progress.

It is a development version after all.
