### ISSUE TITLE
Subtitles encoding problem for Czech

### ISSUE THREAD

**Issue by MrMysakovich** [popcorn-official/popcorn-android#156]
Version:  0.2.9
Download date:  12.2.2017
Android version:  6.0

#### Expected Behaviour
I expected that czech subtitles works correctly, but it did not, because Czech have letters Ž Ř etc. And in app it makes question mark (?) for this letters.

#### Actual Behaviour
Subtitles is showing question mark (?) for letters Ř, Ž, Š etc. I think bad here is bad encoding. 

#### Steps to repoduce the behaviour

1. Play movie that is available with Czech subtitles
2. You will see question mark in letters Ř Ž Š etc

**Comment by minipinki** [comment]
Same problem any solution?

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/subtitles-encoding-problem-for-czech/108
