### ISSUE TITLE
Bug with playback salved enter fix below

### ISSUE THREAD

**Issue by nextapprage** [popcorn-official/popcorn-android#157]
Version:  Android TV 1.4
Mi box 
Download date:  2/9/2017
Android version:  Android TV 6.0
Bug 

Starting a movie or TV show after a few seconds or minutes normally under 2 minutes playback well stop no crash or force close ..

I am assuming this is because my device ran out of available storage and PT couldn't download the appropriate data to keep up with the playback buffer ...

So a simple solution would be to let user select default download to SD card or external storage ...

Or by default PT would allow or detect if external storage is present or external storage is merged into internal storage the default storage should Go to SD card ...

After checking with my android TV it turns out my available storage for internal is 859mb 
External is 227gbs .

This is a weird bug concidering I have already set up SD as internal storage and has migrated all data to SD card but it looks like when Popcorn time was installed it was placed into internal storage and not external ...

**Comment by MrRory** [comment]
Why did you not follow the full issue template? :/

If I understand correctly you want to be able to change the storage location on Android TV? That's it?
