### ISSUE TITLE
Application crashes after installing on the Google Pixel

### ISSUE THREAD

**Issue by martinrojas** [popcorn-official/popcorn-android#158]
Version:  2.9
Download date:  Feb 13, 2017
Android version:  7.1.1

#### Expected Behaviour
Normal Start up

#### Actual Behaviour
Application shows modal about downloading a newer version in the background and crashes. 

#### Steps to repoduce the behaviour

This happens on a fresh install on a Google Pixel phone running version 7.1.1

**Comment by MrRory** [comment]
Use https://get.popcorntime.sh/android/0.2.9/mobile-arm64-v8a-release-0.2.9.apk
