### ISSUE TITLE
Constantly crashing, showing FC windows on Nexus Player

### ISSUE THREAD

**Issue by gonzad26** [popcorn-official/popcorn-android#16]
Version:  0.1.2 TV
Download date:  25/02/2016
Android version:  Android 6.0.1 on Nexus Player (x86)

#### Expected Behaviour
Open the application and let me select the movie or serie to watch

#### Actual Behaviour
Constantly crashing, showing FC windows.

#### Steps to repoduce the behaviour
Open the app

**Comment by pct-team** [comment]
Too abstract. Give better steps.
