### ISSUE TITLE
geen ondertiteling

### ISSUE THREAD

**Issue by kakkie** [popcorn-official/popcorn-android#165]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by kakkie** [comment]
Wanneerste komt de ondertiteling terug ?

**Comment by MrRory** [comment]
Sorry, we don't understand any language other than English

**Comment by kakkie** [comment]
The subtitels is gone



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Heat Wave <notifications@github.com>
Datum: 16-02-17 16:11 (GMT+01:00)
Aan: popcorn-official/popcorn-android <popcorn-android@noreply.github.com>
Cc: kakkie <benhegeman@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [popcorn-official/popcorn-android] geen ondertiteling (#165)


Sorry, we don't understand any language other than English

**Comment by MrRory** [comment]
Then this is probably a duplicate of #139
