### ISSUE TITLE
fix(ChromeCast): stream option not available

### ISSUE THREAD

**Issue by mateusleon** [popcorn-official/popcorn-android#167]
Version:  0.2.9 - x86
Download date:  02/04/2017
Android version:  5.0

#### Expected Behaviour
Provide cast through Chrome Cast 2

#### Actual Behaviour
The option isn't visible, on the upper right corner of the main view on the app.

#### Steps to repoduce the behaviour

1. Enter the app
2. Go to preferences
3. Select Popcorn Player
4. Select Stream over Wifi only
5. Return to main view and the button doesn't appear.

Note: Chorme Cast is up and running while reproducing the steps, with visitor mode activated, also with none streaming running too.

**Comment by jlegas** [comment]
same here, running mobile-armeabi-v7a-release-0.2.9.apk
cast button doesn't appear for Chromecast, even though other apps cast fine.

**Comment by MrRory** [comment]
Duplicate #74
