### ISSUE TITLE
Show Trending movies instead of Popular in Top Movies.

### ISSUE THREAD

**Issue by soavarice** [popcorn-official/popcorn-android#168]
Version:  Beta 1.4 TV
Download date:  18 FEB 2017
Android version:  6.0

#### Expected Behaviour

Show Trending movies instead of Popular in Top Movies.

#### Actual Behaviour

Show Popular movies instead of Trending in Top Movies.

#### Steps to repoduce the behaviour

1. Install the app.
2. Open the app.
3. Home screen or / top movies section.

**Comment by MrRory** [comment]
Why?

**Comment by soavarice** [comment]
Because in desktops is this? And in trending show movies who are hot and new, not most seed and watch.

**Comment by MrRory** [comment]
That the desktop app has something doesn't immediately mean we should do it too
