### ISSUE TITLE
Watch Trailer Fix

### ISSUE THREAD

**Issue by soavarice** [popcorn-official/popcorn-android#169]
Version:  1.4 Beta TV
Download date:  17 FEB 2017
Android version:  6.0

#### Expected Behaviour

When click on watch trailer to play the trailer for the movie.

#### Actual Behaviour

Stuck or crash and show no video found.

#### Steps to repoduce the behaviour

1. Install the app on android tv.
2. Open the app and open some movie.
3. Click watch trailer button.

**Comment by dickreuter** [comment]
I experience the same problem.
