### ISSUE TITLE
Can't run on ARM64?

### ISSUE THREAD

**Issue by emersion** [popcorn-official/popcorn-android#17]
Version: 0.2.8
Download date:  2016-03-06
Android version: 6.0.1

#### Expected Behaviour
Run. :P

#### Actual Behaviour
Does not run. Instead, shows message: you're using the wrong version of Popcorn Time for Android.

#### Steps to repoduce the behaviour
Download the app on a Nexus 5X.

**Comment by pct-team** [comment]
Then install the arm64 version. https://ci.popcorntime.sh
