### ISSUE TITLE
Genre switching not working

### ISSUE THREAD

**Issue by rachitkhurana007** [popcorn-official/popcorn-android#170]
Version:  0.2.9 - armeabi-v7a
Download date:  19/02/2017
Android version:  6.0

#### Expected Behaviour

Should get me the movies and TV series related to the genre I selected.
...

#### Actual Behaviour

Didn't do anything at all... Remained as it is.
...

#### Steps to repoduce the behaviour

1. open app
2. go to movies / TV shows
3. go to genres tab
4. Try to select one.

**Comment by ChrisAlderson** [comment]
#20
