### ISSUE TITLE
Sem legenda

### ISSUE THREAD

**Issue by Jes2ic4** [popcorn-official/popcorn-android#171]
Todos os filmes estao sem legenda disponivel.

**Comment by WHAmarcelo** [comment]
Sem legenda! Mesmo problema aqui

**Comment by WHAmarcelo** [comment]
No subtitles for android and android tvs. Also downloaded dev build 136 and keeps not showung any subs option on both devices tested.

**Comment by MrRory** [comment]
Duplicate #139
