### ISSUE TITLE
No subs available for all movies in Android and Androidtv

### ISSUE THREAD

**Issue by WHAmarcelo** [popcorn-official/popcorn-android#172]
Version:  0.2.8-amveabi-v7a (mobile) and 0.1.4-armveabi-v7a (androidtv), also tested jenkins dev builds 131, 135 and 136 with same error.
Download date:  18/feb/2017
Android version:  Android 6.0.1 (mobile/samsung) and Android 6.0.1 (sony androidtv)

#### Expected Behaviour
Load subs options, select, and play.

#### Actual Behaviour 
"No subs available" message displayed for any movie

#### Steps to repoduce the behaviour

1. Open
2. Open movie (any)
3. Wait load subs
4. No subs available message thrown

**Comment by MrRory** [comment]
Duplicate #139
