### ISSUE TITLE
problem subtitles

### ISSUE THREAD

**Issue by Buda992** [popcorn-official/popcorn-android#174]
Version:  0.2.9-amveabi-v7a
Download date:  19.02.2017
Android version:  5.1.1

#### Expected Behaviour
Load subs options,select,and play
...

#### Actual Behaviour
No subs available message displayed for any movie
...

#### Steps to repoduce the behaviour

1. open
2. open movie(any)
3. wait load subs
4.no subs available message thrown

**Comment by filiep** [comment]
standaardondertiteling staan geen, installeer mx player 
Klik op standaard videospeler klik op mx player selecteer je film dat je wil kijken 3 puntjes inderdaad rechter hoek, klik op ondertiteling en op zoeken. En je hebt ondertiteling. Ik hoop dat jullie er aan uit kunnen

**Comment by secretmyth** [comment]
I also have this issue :(
I don't know what happen there..maybe is an API issue from yifysubtitles.com

**Comment by MrRory** [comment]
Duplicate #139
