### ISSUE TITLE
Crhomecast error

### ISSUE THREAD

**Issue by neo3kk** [popcorn-official/popcorn-android#176]
Version:  0.3.0
Download date:  20/02/17
Android version:  android 6.0.1

#### Expected Behaviour

...
Crhomecast mirroring not working
#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...INSTALL APP
2. ...CONECT TO CRHOMECAST
3. ...NOT WORKING

**Comment by Breaking1** [comment]
Where did you download this version?

**Comment by MrRory** [comment]
doesn't matter, if it's our version then this is a duplicate of #74
