### ISSUE TITLE
eem legendas disponíveis

### ISSUE THREAD

**Issue by marcocavalcanti** [popcorn-official/popcorn-android#178]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by marcocavalcanti** [comment]
Fix app

**Comment by marcocavalcanti** [comment]
Sem legendas disponíveis

**Comment by ChrisAlderson** [comment]
Fill in the template
