### ISSUE TITLE
Add additional remote actions

### ISSUE THREAD

**Issue by Abushawish** [popcorn-official/popcorn-android#179]
Version:  0.2.9
Download date:  Feb 22, 2017
Android version:  Android 6.0.1

#### Expected Behaviour
When watching on a phone or an Android box on TV, pressing the Enter button using a remote should pause the video or at least bring up the video player controls. Pressing arrow right should skip forward, etc.

[Type of remote I'm talking about](http://i.imgur.com/QJdQ1SS.jpeg)

#### Actual Behaviour
Currently, there's no actions assigned to pressing any of the controls on the remote, including Enter.

#### Steps to repoduce the behaviour
Access to a remote, play video, attempt to press Enter/arrow keys.

**Comment by MrRory** [comment]
Weird remote, but yes you're right

**Comment by Abushawish** [comment]
@MrRory You're correct, it should show the controls/overlay. I just added a fix in my PR (https://github.com/popcorn-official/popcorn-android/pull/183)
