### ISSUE TITLE
Green big on screen

### ISSUE THREAD

**Issue by guilhermepaesa** [popcorn-official/popcorn-android#189]
Version: 0.2.9
Download date: 03/03/17
Android version:  5.1.1

#### Expected Behaviour
Work the player correctly

#### Actual Behaviour
Every show I start it's with a green bug on screen and I can't see anything

#### Steps to repoduce the behaviour

1. Open any movie or episode
2. Loading
3. Bug on screen

Other players don't show subtitles, my problem it's only with the default player

**Comment by Rafael77br** [comment]
Vc ja tentou baixar outro player? 
No meu celular anterior eu tive que baixar pq tava meio bugado, mas pelo player deles e o player vlc tb da pra arrumar o tempo das legendas..

**Comment by guilhermepaesa** [comment]
Como colocar a legenda em outro player?

**Comment by Nicofisi** [comment]
Screenshot please

**Comment by MrRory** [comment]
Closing as stale
