### ISSUE TITLE
Crashes after less of a minute use on Nexus Player

### ISSUE THREAD

**Issue by gonzad26** [popcorn-official/popcorn-android#19]
Version:  0.1.2
Download date:  25/02/2016
Android version:  6.0.1 on Nexus Player

#### Expected Behaviour
Open the app and search for a movie or TV series and then play it

#### Actual Behaviour
Open the app and after 1 minute, crashes

#### Steps to repoduce the behaviour

1. Open the app
2. Navigate to find a movie or go to search o go to option, just using the app trigger the crash
3. It crashes not matter what I do

**Comment by pct-team** [comment]
cannot reproduce
