### ISSUE TITLE
SUBTITLES DOESN'T WORK ANYMORE TO WATCH MOVIES

### ISSUE THREAD

**Issue by Rafael77br** [popcorn-official/popcorn-android#191]
Version:  0.2.9 - arm64-v8a
Download date:  4-03-2017
Android version:  6.0

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ... Click on any movie
2. ... And subtitles dont open..
3. ...

**Comment by bbougot** [comment]
Yes, it seems there is an issue with YIFY provider. The API returns a "Maintenance in progress" message.
http://www.ysubs.com/

**Comment by ant-1** [comment]
I also confirm that it seems to be any issue with the subtitle provider.

From what I understand from the sources, Yifi subtitles service is used only for movies.
The urls used to fetch the subtitles are [http://api.yifysubtitles.com/subs/](http://api.yifysubtitles.com/subs/) and [http://api.ysubs.com/subs/](http://api.ysubs.com/subs/), which are obviously no more available

The Opensubtitles service is also used but only for series, and it seems to work perfectly.

So if a popcorn time developer can have a look at it I explain if there is any limitation with OpenSubtitles service for movie subtitle ?

**Comment by team-pct** [comment]
No limitation , we planned move to OpenSub for movies too , i guess our guys had no time

**Comment by ant-1** [comment]
It seems to be fixed in the commits [75c32dd](https://github.com/popcorn-official/popcorn-android/commit/4944b981f7498dfb9a3acb092a7baffd34e4a7ad) and [d0ee7c2](https://github.com/popcorn-official/popcorn-android/commit/078168f368e34ab914071d94345b02b604e2019d)
I have tried to test the last version from develop branch but I was not able because of issues #193 and #106

**Comment by team-pct** [comment]
Hey Thank you for the PR ,
I hope someone will review it and merge 

Thank you again for your contribution

**Comment by Rafael77br** [comment]
Thanks for attention!
Cheers
