### ISSUE TITLE
Subtitles not available for movies

### ISSUE THREAD

**Issue by TorresGiovanne** [popcorn-official/popcorn-android#192]
Version:  0.2.9 arm64
Download date:  03/03/17
Android version:  6.0.1

#### Expected Behaviour

... It should show all the languages that has subtitles available.

#### Actual Behaviour

... The app says that there's no subtitles available for any movie. It works fine for the Series, but for the Movies is not available.

#### Steps to repoduce the behaviour

1. ... Choose any movie title
2. ... Try to choose a subtitle
3. ... Appears the following message "there's no subtitles available"

**Comment by minipinki** [comment]
Same problem

**Comment by bastian94** [comment]
Same problem

**Comment by crsag** [comment]
Still same problem

**Comment by rqsakai** [comment]
Bump

**Comment by lucasalveslol** [comment]
Same problem, is there any any new version avaliable?

**Comment by computersteve** [comment]
Same & Latest developer version crashes on android tv boxes..

**Comment by vijaythecoder** [comment]
same problem on android tv

**Comment by kikocole** [comment]
Same problem it say subtitles loading but its a loop... Fix it

**Comment by elminouch** [comment]
Same problem on Android for Samsung s7edge app and android TV  subtitles are not available on series and films. Not cool.

**Comment by computersteve** [comment]
Also the same problem on android tv for me as well...

**Comment by fguespe** [comment]
Same here

**Comment by pdamonte** [comment]
Same here

**Comment by gangstaboy5785** [comment]
Same here!!!!

**Comment by vijaythecoder** [comment]
@ChrisAlderson your reply on this would be highly appreciated :) Thanks for your effort

**Comment by ChrisAlderson** [comment]
@vijaythecoder I don't know much more. I'm not in the android development branch of anything. I just close duplicate issues.

**Comment by ivand232** [comment]
Same problem

**Comment by vijaythecoder** [comment]
@ChrisAlderson Thanks for the reply.

**Comment by adriannieto** [comment]
Same here

**Comment by ipdxl** [comment]
Same here

**Comment by venzislav** [comment]
Same - no subtitles on android TV version tv-armeabi-v7a-release-0.1.4.apk

**Comment by spike886** [comment]
Same

**Comment by pentakalos** [comment]
The problem remain. Anyone find solution?

**Comment by shadowintheface** [comment]
Android 7,0 and 7.1.2 same problem

**Comment by shadowintheface** [comment]
It was possible at least to add the ability to play on another player so I can put the subtitles (talk about android tv app) thank you

**Comment by epistularum** [comment]
This seems to be a 1year long issue that has not been fixed. This makes it impossible to watch foreign movies.

**Comment by pentakalos** [comment]
Open movie with an external player like mx player and download subs from there. Its the only way. I dont think that anybody will fix it

**Comment by epistularum** [comment]
A Real bummer since the subtitle download is supposed to be automated like the windows soft.

**Comment by gabera** [comment]
Or the developers are native English speakers so they don't care about this issue or the development is stopped... It's been more than a year and it feels like never gonna be fixed. The desktop version also has the same problem for decades. It's a pain in the ass to make subtitles work in popcorn

**Comment by Persei08** [comment]
>Or the developers are native English speakers so they don't care about this issue or the development is stopped... It's been more than a year and it feels like never gonna be fixed.

This issue is fixed for more than one year in development branch. You people should try the [dev builds](https://ci.popcorntime.sh/job/Popcorn-Time-Android/) especially the 138 which ATM (2018-03-13) is the last one from the development branch. 

> The desktop version also has the same problem for decades.
Same for desktop version: https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/lastSuccessfulBuild/

**Comment by danielatatu** [comment]
Hello, all! 

I am facing the same issue and I was hoping that maybe a fix was found... 

I have a Mi Box 3 and I have installed many versions of the Popcorn Time application (release, development, debug), but the only ones that I could actually run without receiving an error message were:
- tv-armeabi-v7a-development-138.apk
- tv-armeabi-v7a-release-0.1.4.apk

The first one however stops when I try to play a movie and the second one doesn’t have any subtitles.

Please let me know if you manage to find a fix or an workaround for this problem. Thanks!

**Comment by tiago2hp** [comment]
Nobody gets a solution?

**Comment by Persei08** [comment]
@danielatatu No, I just know sometimes some changes from butter-android are merged into popcorn-android, the dev builds with "-debug" suffix in their filenames, but it's like they are experimental I guess.

@tiago2hp try the dev build 138; https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Android/138/

**Comment by marcuscarvalho** [comment]
Fixed on the development branch after merging the following open pull request https://github.com/popcorn-official/popcorn-android/pull/444

**Comment by marcuscarvalho** [comment]
Fixed for android tv, the working build artifact is available at https://ci.popcorntime.sh/job/Popcorn-Time-Android/lastBuild/
