### ISSUE TITLE
TV version fails to open with last version from develop branch

### ISSUE THREAD

**Issue by ant-1** [popcorn-official/popcorn-android#193]
Version: last sources from develop branch
Download date:  March 3rd, 2017
Android version:  7.0, Nvidia Shield TV

#### Expected Behaviour
Open the popcorn time application on android TV successfully

#### Actual Behaviour
application fails to open and shield display "reopen the application"

#### Steps to repoduce the behaviour

1. Compile and install popcorn time apk for android TV from development branch 
2. Launch popcorn time
3. et voilà

Please find attached logcat of tv apk
[logcat.txt](https://github.com/popcorn-official/popcorn-android/files/819456/logcat.txt)

**Comment by WHAmarcelo** [comment]
same issue here on armv7 Sony androidtv 6.0.1

**Comment by omarbelkhodja** [comment]
Is it possible to run Jenkins again ? I would like to download and give it a try.

**Comment by lopesdasilva** [comment]
This still happens.

**Comment by MrRory** [comment]
I think this specific issue was fixed in the PR.
