### ISSUE TITLE
Galaxy S7 Android 7 

### ISSUE THREAD

**Issue by Serj1027** [popcorn-official/popcorn-android#196]
Version:  0.2.9
Download date:  06.03.2017
Android version:  
7.0
#### Expected Behaviour

Work.

#### Actual Behaviour

It say that i'm using a wrong version of Popcorn time and it say that my device is not supported, but it's a Galaxy S7. On android 6.0.1 it works...

#### Steps to repoduce the behaviour

1. Open the app from a Galaxy S7 with Android 7.0
2. ...
3. ...

**Comment by syl3nt** [comment]
Yes, that happened to me as well, it seems that the app available for download from the site is in arm, and our processor is arm64, so what you need to do (if i am correct) is download the last stable version from ci.popcorntime.sh 
cheers.

**Comment by CyberBubba** [comment]
I am using a S7 with Nougat using Popcorn Time v2.8.0-76 and it works without a hitch. I will try the version from the repository and see what happens.
