### ISSUE TITLE
Stucked on "Waiting for torrents..."

### ISSUE THREAD

**Issue by bbougot** [popcorn-official/popcorn-android#197]
Version:  mobile-arm64-v8a-development-138
Download date:  08/03/2017
Android version:  6

#### Expected Behaviour
Launching movie

#### Actual Behaviour
App stucked on "Waiting for torrents..."

#### Steps to repoduce the behaviour
Launch a movie...

I tried Wifi, 4G, with or without subtitles, several movies and wait 5+ minutes. Still the same issue

**Comment by WHAmarcelo** [comment]
Same here for mobile armv7 on samsung galaxy s5 (android 6.0.1)

**Comment by WHAmarcelo** [comment]
Also tested 138 armv7 on sony android tv and same error persists (waiting for torrent), android version on my androidtv is also 6.0.1

**Comment by MrRory** [comment]
We do not support development versions
