### ISSUE TITLE
crash when going in episode description

### ISSUE THREAD

**Issue by LaPatate64** [popcorn-official/popcorn-android#199]
Version:  0.2.9 arm64 v8a
Download date: 16/03/2017
Android version:  5.0.1 huawei ale-l21

#### Expected Behaviour
Go in the episode's description and see play button, description, subtitle and quality option and be able to play it.

Instead the menu apear for a few frames and crash to the main menu of the app, so i can't watch any serie.

It could be related to the subtitle list loading.

#### Steps to reproduce the behaviour
1. Click on the serie you want to watch
2. Click on the season
3. Select the episode
4. Crash :)
5. You are now back on the series menu.

**Comment by MrRory** [comment]
Please update to 0.2.10
