### ISSUE TITLE
App crashes when starts

### ISSUE THREAD

**Issue by exiominiox** [popcorn-official/popcorn-android#2]
App crashes when start on Moto E 2015 and Moto G 2014, works fine on Samsung Galaxy E5 

Please fix this (sorry this application has stopped)

**Comment by pct-team** [comment]
This has been fixed. You just don't have the right version yet since it has not been released.

**Comment by pct-team** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Android/lastSuccessfulBuild/

**Comment by atheleron** [comment]
Hello Im using **tv-arm64-v8a-release-0.1.2.apk** with **Nvidia Shield TV** that runs **android 6.0** every build I try on ci.popcorntime.sh just crashes I get error **Unfortunatley, Popcorn Time has stopped.** I run it multiple times and it works for while but this error just pops up and quit app then I start app again i can scroll and watch cover art but after 10 second error pops up and app crash again maybe I could get error log from shield to se exacty what happend ??

**Comment by gonzad26** [comment]
I'm having the same problem with the **Nexus Player (x86)**
