### ISSUE TITLE
Genre filter not working

### ISSUE THREAD

**Issue by hawkican** [popcorn-official/popcorn-android#20]
Version:  0.2.8
Download date:  may 7
Android version:  5.1.1
#### Expected Behaviour

Filter shows or movies via genre
...
#### Actual Behaviour

Not really anything
...
#### Steps to repoduce the behaviour

1. ...open app
2. ...go to either movie or shows section
3. ...go to the genre tab, hit a genre, and nothing happens

**Comment by popcorntimetempmail** [comment]
Version 0.2.8
Download date: 24 June 2016
Android version: 4.4
Hardware: Minix X8-H Plus (firmware 009 (latest))

Nothing on the Genre menu is selectable, i can highlight items by moving the pointer but no response on clicking on my airmouse (I am not using a touch screen). There were other android programs which had the same issue with air mouse/touch, so this could be a similar bug.

**Comment by heathcliffr** [comment]
@Chris Anderson:  Is my comment irritating you?  Even though I said the new Android beta doesn't filter genres now, you only focused on my error to write iOS instead of desktop, without responding to the issue.  I posted again, and you refer me to a May post about the problem, again without commenting.  The previous Android version worked; the new beta doesn't.  That's all I'm saying.

**Comment by ChrisAlderson** [comment]
@heathcliffr I'm only pointing out the relevant information about the issue you are having, which is:
 - Genres on Android not working, which should not be reported on the relevant `popcorn-android` repo.
 - Genres on iOS not working, the .sh branch does not have an iOS version, so we cannot help you with that.
 - Film-Noir not working on the desktop version, I linked you to a relevant comment saying there are no movies with the genre film-noir in the database.

I'm not irritated, but I am busy.

**Comment by heathcliffr** [comment]
I’m sorry you’re busy.  So am I.  NONE of the genres work on desktop.
