### ISSUE TITLE
64-bit Android unsupported

### ISSUE THREAD

**Issue by redjoker** [popcorn-official/popcorn-android#21]
Version:  2.8
Download date:  2016-03-15
Android version:  6.0.1

#### Expected Behaviour

...Run similar the same as on other 32-bit Android devices

#### Actual Behaviour

...Gives a version error

#### Steps to repoduce the behaviour

1. ...Install on Nexus 9
2. ...Open app
3. ...Get version error

**Comment by pct-team** [comment]
Then download the 64-bit version: https://ci.popcorntime.sh/job/Popcorn-Time-Android/
