### ISSUE TITLE
Providing subtitles to external player

### ISSUE THREAD

**Issue by beppe9000** [popcorn-official/popcorn-android#213]
Version: Latest stable on CI
Download date:  A week ago
Android version:  6

#### Expected Behaviour
PT supplies the external player with subtitles

#### Actual Behaviour
My external media player (VLC) was opened with the media, but without subtitles.

#### Steps to repoduce the behaviour
1. Set PT to use external player
2. Open any media

**Comment by MrRory** [comment]
What's the url VLC is player? What if you replace the extension of the file by .srt? Does it open subtitles? Did you select subtitles before playback?

**Comment by beppe9000** [comment]
it was something like `127.0.0.1:xxxx/`. I don't think `127.0.0.1:xxxx/.srt` would be any better...
I had to download the subtitles separately and to open them within vlc.

I think PT should put the srt in the actual stream.

**Comment by MrRory** [comment]
We cannot put subtitles in the stream, the url is local server that hosts the video. The .srt url should be served with that video, which provides the subtitles. The feature is already there, has been for a long time. Just doesn't seem to be working.

https://github.com/popcorn-official/popcorn-android/blob/development/base/src/main/java/butter/droid/base/content/preferences/DefaultPlayer.java#L96
