### ISSUE TITLE
Cast to smartv doesnt works

### ISSUE THREAD

**Issue by Daniellviana** [popcorn-official/popcorn-android#218]
Version:  
Download date:  
Android version:  7.1 lineage

#### Expected Behaviour

...

Cast the screen to  smartv lg
#### Actual Behaviour

...
Nothing happens. I click in the cast button and select my tv but Nothing happens 
#### Steps to repoduce the behaviour

1.click in the cast tv
2. ...
3. ...

**Comment by alexsilva** [comment]
Cast for smart tv samsung 6 series also does not work.
