### ISSUE TITLE
Subtiles don't are show 

### ISSUE THREAD

**Issue by luiz2334** [popcorn-official/popcorn-android#219]
Version 2.9:  
Download date:  11/04/2017
Android version:  4.4.2

I don't see the videos because the app don't show the options about subtiles. The apple show me only "No subtitles" and when i selected the option "subtiles custom", the app don't show the subtiles and automatically back at option "no subtiles" 

What i have to do the app back show the subtiles normally? 

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by bastian94** [comment]
second this

**Comment by jona2428** [comment]
Lo mismo para mi 
Android 6.0.1 
Se queda en cargando subtítulos

**Comment by nacho87** [comment]
The same here

**Comment by crsag** [comment]
Same here.. It shows for tv series and animation but not for movies.

**Comment by Jonyx4** [comment]
Same here
