### ISSUE TITLE
Playing any movie on AndroidTV doesn't work

### ISSUE THREAD

**Issue by vriera** [popcorn-official/popcorn-android#22]
Version:  mobile-armeabi-v7a-release-0.2.8.apk
Download date:  from CI, build #77, revision 0468b2ba98eea66d0c715734ff1d34f30c86aef6 
Android version:  5.1.1

When I try to play a movie on my Sony Bravia KD55-X8509C it stuck and never works. It doesn't even start. I don't know if it's a problem of not having enough hard disk space. Why isn't there an option to change the temporary directory so I could make it point to a USB drive with plenty of free space?

**Comment by pct-team** [comment]
There is. The storage location in settings.
