### ISSUE TITLE
Load custom subtitle 

### ISSUE THREAD

**Issue by Znuff** [popcorn-official/popcorn-android#23]
Version:  0.2.8
Download date:  26.03.2016
Android version:  6.0

Android version doesn't have the possibility of loading custom subtitles like the desktop version. 

It's really inconvenient when I watch a movie with friends and the app doesn't have subtitles in our language.

**Comment by pct-team** [comment]
it did, last time I checked. scroll all the way down in the subtitle language list and choose 'Custom...'
