### ISSUE TITLE
Video doesn't load even with proper internet 

### ISSUE THREAD

**Issue by kshamakale** [popcorn-official/popcorn-android#232]
Version:  0.2.9
Download date:  
Android version:  7.0

#### Expected Behaviour
Video should load every time, something. Went wrong message should not display

#### Actual Behaviour
Video doesn't load and user can see something went wrong msgs

#### Steps to repoduce the behaviour

1. select any series
2.start playing any episode
3.waiting for torrent displays and observe after that

**Comment by ItsSh4dow** [comment]
I had exactly the same problem, then I switched to cellular data and it worked

**Comment by zedszanue** [comment]
Also having that problem with tv shows only. Will play about 10 seconds of the show and then everything freezes.

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
