### ISSUE TITLE
PopcornTime crashes while attempting to resume movie after screen locks on phone

### ISSUE THREAD

**Issue by zedszanue** [popcorn-official/popcorn-android#234]
Version:  3.10
Download date:  May 25 2017
Android version:  Nougat (Samsung Galaxy S6 Edge)

#### Expected Behaviour

Be able to resume video after screen locks

#### Actual Behaviour

Popup error is displayed saying Popcorn time is not responding (do you want to close or wait for the app)

#### Steps to repoduce the behaviour

1. Watch a movie
2. Pause it and wait for screen to lock (1 minute or so)
3. Unlock your screen and attempt to resume movie

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
