### ISSUE TITLE
Subtitles not showing on movies only

### ISSUE THREAD

**Issue by gfmaciel** [popcorn-official/popcorn-android#245]
Version:  0.2.9 arm V8 64
Download date:  23/06/17
Android version:  marshmallow

#### Expected Behaviour

let me choose the subtitles when I select a movie, with series work everytime

#### Actual Behaviour

keep on showing loading subtitles until it says that something went wrong

#### Steps to repoduce the behaviour

1. select any movie
2. try to choose a subtitle
3. ...

**Comment by ChrisAlderson** [comment]
#243

**Comment by BillGods** [comment]
I have tryed, but problem keep...
Have a new version to download?
