### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by ChrisAlderson** [popcorn-official/popcorn-android#247]
Make Chromecast grate again: 
- [ ] Ability to select chromecast device on current wifi network
- [ ] Ability to cast default subtitles from the application
- [ ] Ability to cast custom subtitles from the application
- [ ] Cast button doesn't show up in some cases

**Comment by lfreneda** [comment]
Please ;___;

**Comment by vickykage** [comment]
Chrome cast #247

**Comment by noeltorious** [comment]
Any updates on this one?

**Comment by hsantanna** [comment]
There is any work around to make the chromecast button to show up?

**Comment by christiga** [comment]
I'm having the issue...
