### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by jokhallouf** [popcorn-official/popcorn-android#25]
Version:  2.8
Download date:  31.03.2016
Android version:  6.0.1

#### Expected Behaviour

Install properly on my Nexus 7 

#### Actual Behaviour

After downloading and when i click on the file to install, it comes back as "Can't open file"

#### Steps to repoduce the behaviour

1. Have an android device running android 6.0.1
2. Download the apk from popcorntime.sh
3. try to install

**Comment by Breaking1** [comment]
Try to manually fetch the link from here and see if it works.

https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Android/
