### ISSUE TITLE
No me cargan las peliculas

### ISSUE THREAD

**Issue by marogu** [popcorn-official/popcorn-android#259]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by marogu** [comment]
Cuando abre la película, parece como un cd rayado por favor ayudenme no se como arreglarlo

**Comment by Nicofisi** [comment]
You need to use English

**Comment by marogu** [comment]
Sorry, I can't use the app, I don't upload movies please help me!
