### ISSUE TITLE
Search causes the Android TV Popcorn Time to refresh / restart

### ISSUE THREAD

**Issue by McShmoopy** [popcorn-official/popcorn-android#26]
Version:  	tv-armeabi-v7a-development-79.apk
Download date:  18th April 2016
Android version:  Side loaded onto Amazon fire stick TV

#### Expected Behaviour

Expect search results to appear and allow me to select them

#### Actual Behaviour

...Freezes momentarily and then it exits search and shows the main page with the movie and tv shows list. 

#### Steps to repoduce the behaviour

1. ... Open popcorn time
2. ... Click search
3. ... Type in search phrase and press search and then the freeze occurs

**Comment by pct-team** [comment]
The Amazon Fire TV is not officially supported. Its not an Android TV device

**Comment by mohamnag** [comment]
Is this still an up-to-date decision not to support Fire TV? its a very cheap device with great hardware and its a pity that lots of basics (like forward and backward button) does not work on it. I think it has all the potential to be preferred to no-name Chinese android boxes.

**Comment by MrRory** [comment]
The Fire TV is still not an Android TV device, so the Android TV version is still not supported for such a device.
