### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by RoToRx88** [popcorn-official/popcorn-android#264]
Version:  0.2.9
Download date:  31/07/2017
Android version:  7.1.2

#### Expected Behaviour

Just after the installation of the app, I launched it. it was supposed to start.

#### Actual Behaviour

But here is the screen I am stuck on: http://imgur.com/4q7eeVu

#### Steps to repoduce the behaviour

1. Download the apk from the website popcorntime.sh
2. Install the APK
3. launch the app
4. Wait a minute to be sure the app is not downloading something

**Comment by hansjd** [comment]
same error
android 8.0
Nexus P6

**Comment by blazsolar** [comment]
Try [this](https://get.popcorntime.sh/android/0.2.9/mobile-arm64-v8a-release-0.2.9.apk) link. For some reason website redirects you to 32 bit arm apk, but your device requires 64 bit.

**Comment by StyxOfDynamite** [comment]
This fixes the issue on Huawei P10. Any reason there's not a better device detection on the download page? If popup adverts now the exact model of phone I'm on it shouldn't take much it is there an issue open on the website project I couldn't find?

**Comment by vickykage** [comment]
OK Make it ASAP!!!
