### ISSUE TITLE
Subtitles not available

### ISSUE THREAD

**Issue by elminouch** [popcorn-official/popcorn-android#267]
Version:  beta 2.9 arm64_v8
Download date: 05/08/2017
Android version:  7.0

#### Expected Behaviour

...
Charging subtitles
#### Actual Behaviour

...
Not charging anything
#### Steps to repoduce the behaviour

1. ...choose a film or series
2. ...selct subltitles
3. ...you can't. If you open a film and then select subtitles its the same problem : no subtitles available. Trying to change de default language for subtitles into "French" but still dont work..... 
Without subtitles the app is useless for me and many peoples... 
I precise that the problem is the same on my android Tv so it is not a hardware issue.

**Comment by ChrisAlderson** [comment]
#192

**Comment by fguespe** [comment]
Same problem
