### ISSUE TITLE
Player crashes when connecting from Android to a Chromecast device

### ISSUE THREAD

**Issue by ldmerchan** [popcorn-official/popcorn-android#269]
Version: 0.2.9  
Download date: 8/02/2017
Android version:  5.1.1

#### Expected Behaviour

Cast movie to Chromecast 

#### Actual Behaviour

App shows message of crash issue

#### Steps to repoduce the behaviour

1. Select movie
2. Tap Cast logo
3. Wait for movie to torrent

**Comment by viniciuslmarques** [comment]
Same here

**Comment by ChrisAlderson** [comment]
#247
