### ISSUE TITLE
Moto G5 Plus Chromecast 2 issue

### ISSUE THREAD

**Issue by vinicius3000** [popcorn-official/popcorn-android#272]
Hi guys,

On Moto g5 plus even though other apps find my Chromecast 2 the popcorn time doesn't . I have to reboot both the Chromecast and the phone when I want to transmit my screen. :( 

Any ideas?

Version:  2.9.0
Download date:  01/AUG/2017
Android version:  7.0

#### Expected Behaviour

...

Show Chromecast 2 on the list of available dlna devices.

#### Actual Behaviour

...
Chromecast 2 is not shown 

#### Steps to repoduce the behaviour

1. ... Hook up Chromecast 2 on TV
2. ... Open popcorn time 
3. ... Try both turning Chromecast 2 on first or cell phone first and then try transmitting screen

**Comment by ChrisAlderson** [comment]
#247
