### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by pranaysingh1194** [popcorn-official/popcorn-android#273]
Version:  0.2.9 - armeabi-v7a
Download date:  22 August 2017
Android version:  6.0.1

#### Expected Behaviour

Subtitles are not working in the Android app as well as the Android TV app.Neither the automatically fetched subtitles work nor do the "custom subtitles".I have tried clear the data as well uninstalling+reinstalling the app several times on my phone as well as my Android TV but the problem still persists.Kindly look into the issue ASAP

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
#192
