### ISSUE TITLE
Can't stram subtitles to lg webos tv

### ISSUE THREAD

**Issue by bokiroki** [popcorn-official/popcorn-android#28]
Version:  mobile-armeabi-v7a-development-79.apk (latest version)
Download date:  
Android version:  5.1.1 lolipop

#### Expected Behaviour

...

#### Actual Behaviour

...i cant stream subtitles when casting movie or tv show to lg webos tv, with popcorn time desktop i can stream, so problem must be within android app..when i'm casting with popcorn time desktop i have subtitiles icon on my tv menu, but with android version i dont have that icon on my tv..
i tried with few diferent languages, none of them work

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by pct-team** [comment]
youll never be able to do this
