### ISSUE TITLE
No Data Found

### ISSUE THREAD

**Issue by ruvort** [popcorn-official/popcorn-android#280]
Version:  0.2.9
Download date:  
Android version:  7.1.2

#### Expected Behaviour

Show list of movies for the following categories: Top Rated, Release Date,  Year, and A-Z.
...

#### Actual Behaviour

Instead, the app just displays text saying: "No Data Found"

#### Steps to repoduce the behaviour

1. ...Slide through the categories (Top Rated, Release Date,  Year, and A-Z)
2. ...See the "No Data Found" text
3. ...No more steps

**Comment by mcbrimson** [comment]
Please fix.

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
