### ISSUE TITLE
Loading subs

### ISSUE THREAD

**Issue by Cejvik** [popcorn-official/popcorn-android#282]
Version:  0.2.9 v8a
Download date:  12.9.2017
Android version:  7.1.1

#### Expected Behaviour

...
Play with subtittles
#### Actual Behaviour

...
Play without.

#### Steps to repoduce the behaviour

1. ...open film
2. ... See loading subs long time...
3. ...

**Comment by AntonioRomera** [comment]
Same problem

**Comment by AntonioRomera** [comment]
Same problem

_Version:_ 0.2.9 arm64-v8a
_Android:_ 7.0 & 5.0.1
_Download date:_ 18/09/2017

**Comment by ChrisAlderson** [comment]
#192
