### ISSUE TITLE
Popcorn on Amazon Fire Tv

### ISSUE THREAD

**Issue by AIPS69** [popcorn-official/popcorn-android#285]
Version:  armea-v7a-release-0.2.9.apk
Download date:  18/9/2017
Android version:  Fire OS 5.2.4.2

#### Expected Behaviour

...

#### Actual Behaviour

I went to popcorntime.sh downloaded android version of popcorn time which is compatible with android V 4.03 and above. Once app is downloaded it shows that the app isn't working and it should be updated. I updated the app where only have access to the movies section. When I press the three lines icon to change to Tv shows, videos etc, my amazon tv remote is not able to access the below option yet it remains on movies. Same issue happened to me when I installed popcorn time version which is the same one I'm using on me samsung mobile device v2.8.0-76, I can't control the remote to chooese between the movies, it only scrolls up and down.

#### Steps to repoduce the behaviour

1. Simple install popcorn time to amazon fire tv through www. popcorntime.sh and popcorn-time.to to amazon fire tv.
2. ...
3. ...

**Comment by AIPS69** [comment]
Hi guys, I just installed an application on my mobile phone for amazon tv remote, I switched it to mouse mode then I was able to choose the click and the movies icon and switch between movies and tv shows. Any other solution to control popcorn time with amazon fire tv remote?

**Comment by napsterX** [comment]
Do we know why it's closed? Is there a fix released for this issue? I am still seeing this issue.
