### ISSUE TITLE
Could not find the download botton 

### ISSUE THREAD

**Issue by aleid3** [popcorn-official/popcorn-android#287]
Version:  0.2.9 arm64-v8a
Download date:  20-09-17
Android version:  7.1.1

I just bought a new phone (Sony Xperia XZ premium) and I downloaded the app and I tried the previous version or whatever was the previous version on my old phone (Sony Xperia Z5 premium) . I used to see two bottns action (one for watch and one for download). now I only see for watch? Do have any idea for this issue?

**Comment by ChrisAlderson** [comment]
There is a mangent icon allowing you to download the movie/episode through any torrenting app.
