### ISSUE TITLE
Doesn't play on Android 7

### ISSUE THREAD

**Issue by arthuracco** [popcorn-official/popcorn-android#288]
Version:  0.2.9 arm64-v8a
Download date:  20/09/17
Android version:  7 nougat

#### Expected Behaviour

... It was supposed to play videos.

#### Actual Behaviour

...but when I tap on play button, it just doesn't play anything and appears an message error with this text: "error de vídeo encontrado. O reprodutor de vídeo encontrou um erro grave. O arquivo de vídeo não pode ser aberto e/ou reproduzido. O formato não foi reconhecido."

#### steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by Awais-Ali** [comment]
Getting the same error "Video error encountered" - Any help? @ChrisAlderson @vzamanillo @MrRory @team-pct @arthuracco
