### ISSUE TITLE
Legendas nao carregam

### ISSUE THREAD

**Issue by brunobizarri** [popcorn-official/popcorn-android#304]
Version:  0.2.9 -armeabi-v7a
Download date:  20/11/2017
Android version:  4.3

#### Expected Behaviour

Carregar as legendas para assistir junto com o filme

#### Actual Behaviour

Nao carrega as legendas

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by vickykage** [comment]
Closed #304
