### ISSUE TITLE
Bugs during making videos offline.

### ISSUE THREAD

**Issue by macyapp** [popcorn-official/popcorn-android#308]
Version:  0.2.9
Download date:  23/12/2017
Android version:  7.0

#### Expected Behaviour

I thought the movies are being downloaded in the background.

#### Actual Behaviour

Although, I had disabled the remove cache option, the folder containing the movie vanished and the progress meter was stuck at 99.99% in the notification bar.

#### Steps to repoduce the behaviour

1. Play a movie after disabling the remove cache option.
2. Check the file explorer where the cache resides.
3. Refresh the tab and you'll find the folder disappeared.

**Comment by vickykage** [comment]
Nice Work!!
