### ISSUE TITLE
 Screenshare fail

### ISSUE THREAD

**Issue by Tacho57** [popcorn-official/popcorn-android#311]
Version:  0.2.9 armeabi-V7a
Download date:  10/07/2017
Android version:  7.0

#### Expected Behaviour
 I open the app, touch the icon to share the screen of my cellphone, then the program find my LG SMART TV model LH5700, select this TV and nothing happens, YouTube, AllConnect APK, and others work fine.
...

#### Actual Behaviour

... nothing

#### Steps to repoduce the behaviour

1. ...open apk
2. ...touch screenshare icon
3. ...select the [LG] SMART TV LH5700, NETCAST, DLNA, TV

My TV can do this with: YouTube, AllConnect apk, without any problem, so it support streaming, the cellphone is in the same wifi, all parameters of TV are chequed and well configured. My cellphone is a MOTO G4 with Android 7.0, I think that Popcorn is well configured too.

Many thanks in advance

**Comment by vickykage** [comment]
Great Nice Work!!

Thanks to you.
