### ISSUE TITLE
Doesn't load the subtitle on movies

### ISSUE THREAD

**Issue by folckz** [popcorn-official/popcorn-android#312]
Version:  0.2.9 - armeaby-v7a
Download date: 28/12 
Android version:  7.1.1

#### Expected Behaviour
show me the options to subtitles on movies
...

#### Actual Behaviour

...keeps loading forever and dont show the options to subtitles

#### Steps to repoduce the behaviour

1. ...choose a movie
2. ...go to the subtitles
3. ...and wait them load

**Comment by ChrisAlderson** [comment]
#198
