### ISSUE TITLE
Allow any Android user to watch movies.. Latest Dev build Excluding Older Android Versions?

### ISSUE THREAD

**Issue by computersteve** [popcorn-official/popcorn-android#314]
Version:  0.5.1
Download date:  12/30/17
Android version:  5.0

#### Expected Behavior
Work like 0.4.1 does... 

#### Actual Behavior
0.5.1 App starts & then produces error saying "Uhoh! You're using the wrong version of Butter for Android" 

#### Steps to repoduce the behaviour
Install latest tv-armeabi-v7a-debug.apk from ci.popcorntime.sh
Open Butter 
Your Presented With Message..

**Comment by Persei08** [comment]
Dev builds 139 to 141 are based on another branch.
Try [dev build 138](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Android/138/) instead for the moment

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
