### ISSUE TITLE
Unable to open a-z list

### ISSUE THREAD

**Issue by Rajats888** [popcorn-official/popcorn-android#315]
Version:  0.2.9 arm64 v8a
Download date:  5-12-2017
Android version:33.3.a.1.97

#### Expected Behaviour
Normal function

#### Actual Behaviour
Unable to ooen list in genre and a-z columns

#### Steps to repoduce the behaviour
1. unknown
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
