### ISSUE TITLE
Crash when locking/unlocking device

### ISSUE THREAD

**Issue by doplumi** [popcorn-official/popcorn-android#32]
Version:  0.2.8 (latest)
Download date:  
Android version:  6.0.1
#### Expected Behaviour

App should repropose the movie after unlocking device.
#### Actual Behaviour

App shows a black screen with a toolbar weirdly sized. I think this happens because of the configuration change between the portrait mode forced by lock screen mode and landscape mode forced by popcorn-time.
#### Steps to repoduce the behaviour
1. Start watching smth.
2. Lock the screen.
3. Unlock the screen.

It's frustrating because the screen can be locked by accident when holding the phone in landscape to watch a movie. If this happens when you've already watched an hour, you'll have to wait for the time  to download the whole hour again before seeking past that. I'm filing a distinct issue for this behavior, as it doesn't seem to be a lacking feature (random seeking works on desktop).

**Comment by pct-team** [comment]
this kind of sucks, thanks for the extensive bug report

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/crash-when-locking-unlocking-device/110

**Comment by michaelbar84** [comment]
Hi, I too suffer from this, and indeed in combination with the other bug regarding seeking, this is very cumbersome... Please fix! Thank you.
