### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by Serj1027** [popcorn-official/popcorn-android#322]
Version:  0.2.9
Download date:  2.01.2018
Android version:  7

#### Expected Behaviour
To select a subtitle from my device
...

#### Actual Behaviour

Open subtitle only from Popcorn time server

#### Steps to repoduce the behaviour

1. Open any movie
2. Select subtitle
3. Can't acces a subtitle file from phone.

I would like to select a subtitle file from my phone, not from Popcorn time server!

**Comment by ChrisAlderson** [comment]
#192
