### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by dalopez24** [popcorn-official/popcorn-android#325]
Version:  0.2.9 - arm64-v8a
Download date:  undefined
Android version:  7.0

#### Expected Behaviour
Load subtitles automatically when movie is downloading and broadcasting to dlna or Chromecast
...

#### Actual Behaviour
The app doesn't load any subtitles and plays the movie without anything

#### Steps to repoduce the behaviour
1. Select movie
2. select device to cast
3. play (with subtitles language defined from settings)

**Comment by isipka** [comment]
same

**Comment by Persei08** [comment]
Does the [dev build 138](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Android/138/) work better ? (do not try later dev builds they don't work)
