### ISSUE TITLE
android tv box

### ISSUE THREAD

**Issue by shadowintheface** [popcorn-official/popcorn-android#328]
Version:  0.1.4 -armeabi-v7a
Download date:  24.1.2018
Android version:  7.1.2

#### Expected Behaviour

... I thought that there will funkcion subtitles.

#### Actual Behaviour

... Subtitles are not automatically downloaded and can not be manually loaded

#### Steps to repoduce the behaviour

1. ... Play a movie on android tv box and insert subtitles.
2. ...
3. ...

**Comment by shadowintheface** [comment]
The subtitles do not work on any android, but on linux without any problems.

**Comment by ChrisAlderson** [comment]
#192
