### ISSUE TITLE
Does not load subtitles on android or android tv version

### ISSUE THREAD

**Issue by tclgyn** [popcorn-official/popcorn-android#329]
I believe The issue is due both versions do not allow to log in the open subtitles account... 

The pc version allow it and the subtitles are loaded. 

Version:  android and android tv
Download date:  recent
Android version:  2.9 and 1.4

#### Expected Behaviour

Loading subtitles

#### Actual Behaviour

Does not load subtitles no matter the language 

#### Steps to repoduce the behaviour

1. Open app
2. Select movie
3. Wait for it to load subtitles (it only shows the message "loading subtitles")

**Comment by gustavodaquino** [comment]
Same problem here. Android Tv.

**Comment by melmota** [comment]
Same

**Comment by isipka** [comment]
same

**Comment by ChrisAlderson** [comment]
#192
