### ISSUE TITLE
Seeking to `time` waits for completion of the whole part of the movie before `time` to download before actually occurs 

### ISSUE THREAD

**Issue by doplumi** [popcorn-official/popcorn-android#33]
Version:  0.2.8 (latest)
Download date:  
Android version:  6.0.1

#### Expected Behaviour
Seeking to, i.e. an hour, should start downloading the part of the movie after the first hour and display that asap.

#### Actual Behaviour
Seeking to an hour waits for the app to download the whole first hour of the movie, then occurs.

#### Steps to repoduce the behaviour

1. Start watching smth.
2. Seek to the end minus 5mins.
3. App will take you more than an hour to show you that part. Actually, the time of the movie doesn't stop moving while seeing a black screen only. This is confusing since the actual first paint won't be where you actually select  but where you select plus the time it takes to download the first part instead.

**Comment by pct-team** [comment]
this is pretty logical if you consider that the download always starts at 0% and at the start of the video, the downloader isnt really smart

**Comment by cannnon** [comment]
yes it does work on desktop. but is this the desktop application? no. i already said the downloader isnt really smart.

**Comment by michaelbar84** [comment]
Hi, can you please reopen this? What eat it even closed? This is indeed very annoying, makes the app very unpleasant in comparison to it's big brother. I often need to download the whole movie via an external torrent app just to resume a movie... On a device where bandwidth is often a key issue, this is very illogical. Thanks in advance and yep up the good work. Kind regards, Michael Barton.
