### ISSUE TITLE
[Request] Protocol Encryption

### ISSUE THREAD

**Issue by zero77** [popcorn-official/popcorn-android#334]
Can you please add support for protocol encryption and enable it by default, because to my knowledge all popular torrent clients have this.

Thanks

**Comment by zero77** [comment]
What I could find, webtorrent/webtorrent#69

**Comment by blazsolar** [comment]
PCT is using `libtorrent` library under the hood. By default library tries to use encryption if available. So I guess in a way that is already implemented. What it could be don is to add settings to set that encription is mandatory, turned of or used if available.
