### ISSUE TITLE
Menu button is unreachable 

### ISSUE THREAD

**Issue by doplumi** [popcorn-official/popcorn-android#34]
Version:  0.2.8 (latest)
Download date:  
Android version:  6.0.1

The on-screen buttons overlap the menu button which is unreachable, unclickable. I guess you get this bug only on on-screen buttons devices (I'm on a Nexus 6P atm).

**Comment by UpsCagueime** [comment]
Hello,
Same thing on Nexus 5x.

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/menu-button-is-unreachable/109
