### ISSUE TITLE
Internal player crash

### ISSUE THREAD

**Issue by khaosdoctor** [popcorn-official/popcorn-android#36]
Version:  0.27
Download date:  05.30.2016
Android version:  5.0 Lollipop:  
#### Expected Behaviour

Video player is going to play the whole video. 
#### Actual Behaviour

Player stops reproduction up to 10s from start when watching shows. This is not happening with movies. When going back the whole app goes black and crash. 
#### Steps to repoduce the behaviour
1. Open app
2. Navigate to shows
3. Play a show (I chose Game of Thrones) 
4. Play on internal player
5. Wait up to 10s
6. Player freezes 
7. Try going back
8. App crashes

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/internal-player-crash/106
