### ISSUE TITLE
Titles from A-Z only load til Chewing Gun, then it says "unknow acess" on screen

### ISSUE THREAD

**Issue by rogeriogfo** [popcorn-official/popcorn-android#364]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Cannot reproduce.

Which PT version ?
What content type ? Movies, Series ?

I have tested with dev build 138. In Series, A-Z sorting seem to work correctly... I was able to go after "Chewing Gu**m**" serie... I stopped scrolling around "Gangland".

For movies, A-Z sorting isn't correctly sorted.
