### ISSUE TITLE
Can't watch any movie after my updating service didnt update automaticly

### ISSUE THREAD

**Issue by Tomodovodoo** [popcorn-official/popcorn-android#366]
Version:  2.9
Download date:  23-05-2018
Android version: 7.1.2 N2G47H

#### Expected Behaviour
Getting a torrent and watching the movie
...

#### Actual Behaviour
Only thing it's saying is waiting for torrent. Then it always has an unexpected error.
Same for the non-torrent trailers.
...

#### Steps to repoduce the behaviour
1. Download the app on an xiaomi redmi note 4
2. Redownload a new apk that popcor time just made
3. Try watching anything

**Comment by franloop** [comment]
+1.

Happens in Android TV (ANDROID 6.0) and Moto g 5s Plus (ANDROID7.1) in my case.
