### ISSUE TITLE
[Bug] Not Working On Android 8

### ISSUE THREAD

**Issue by zero77** [popcorn-official/popcorn-android#367]
Version:  2.9
Download date:  today
Android version:  8.0

#### Expected Behaviour
It should get past the start screen and display films and tv shows.

#### Actual Behaviour
Popcorn Time doesn't seem to be compatible on android 8 it doesn't get past the initial start screen after installation.

#### Steps to repoduce the behaviour

1. Install the app
2. Open the app up

**Comment by ChrisAlderson** [comment]
Cannot reproduce.

**Comment by Persei08** [comment]
Download arm64 v8 verison

**Comment by zero77** [comment]
@Persei08 
Thanks
