### ISSUE TITLE
Se bloquea cuando lo mando al crhome cast

### ISSUE THREAD

**Issue by Oswaldovideo** [popcorn-official/popcorn-android#369]
Version:  0.2.9
Download date:  15/05/2018
Android version:  8.0.0

#### Expected Behaviour
trasmit to my crhome cast
...

#### Actual Behaviour

...blocked

#### Steps to repoduce the behaviour

1. ...open te app
2. ...select the movie
3. ...whit te cast signal and then trasmit

**Comment by ChrisAlderson** [comment]
#247
