### ISSUE TITLE
Not working on nVIDIA Shield with Marshmellow (Android TV 6.0)

### ISSUE THREAD

**Issue by somnathjk** [popcorn-official/popcorn-android#37]
Version:  
Download date:  
Android version:  Beta 1.3 ARMv7a

#### Expected Behaviour

Work correctly as intended

#### Actual Behaviour

...
![nvidia_shield_pt_issue](https://cloud.githubusercontent.com/assets/19702404/15768716/0025e20c-2971-11e6-88a1-cd72173addab.jpg)

#### Steps to repoduce the behaviour

1. Sideload the above Beta 1.3 for ARMv7a APK file by copying from/to a USB stick and ES File Explorer
2.Try to run the installation using ES File Explorer , select 'Install' when the pop-up shows up to select between 'Market | Install'
3. See this issue
4. Infact yesterday when i logged into my Shield, i even saw PopCornTime icon prompting me to see a movie (Zootopia) , when i clicked again i get the same Pop-up Error as attached.

**Comment by pct-team** [comment]
Use the arm64 APK from https://ci.popcorntime.sh/job/Popcorn-Time-Android/lastSuccessfulBuild/

**Comment by somnathjk** [comment]
Thanks, issue got resolved with this APK!!
