### ISSUE TITLE
Theo subtitle list isnt loaded

### ISSUE THREAD

**Issue by beuleal** [popcorn-official/popcorn-android#371]
Version:  
Download date:  
Android version:  
6.0.1
#### Expected Behaviour

Load subtitles list
...

#### Actual Behaviour

...
Doesnt load the subtitles list

#### Steps to repoduce the behaviour

1. choose Amy mobile and fale a look ar subtitle lisi
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
#192
