### ISSUE TITLE
Bug with subs

### ISSUE THREAD

**Issue by tiago2hp** [popcorn-official/popcorn-android#372]
Version:  0.29
Download date:  01 of may
Android version:  6.0.1

#### Expected Behaviour

...
load the subs correctly
#### Actual Behaviour

Always loading, never complete
...

#### Steps to repoduce the behaviour

1. Open the app, tap to see a movie. Wait for subtitles
2. ...
3. ...

**Comment by ChrisAlderson** [comment]
#192
