### ISSUE TITLE
Does not work on Samsung galaxy A8(2018)

### ISSUE THREAD

**Issue by ManOfGod** [popcorn-official/popcorn-android#375]
Version:  2.9
Download date:  June 18, 2018
Android version:  7.1

#### Expected Behaviour
App will work normally.
...

#### Actual Behaviour
App does not work.
...

#### Steps to repoduce the behaviour

1. download the apk.
2. install.
3. open the app.

**Comment by ChrisAlderson** [comment]
Cannot reproduce.
