### ISSUE TITLE
Subtitles don't change size and font over Chromecast

### ISSUE THREAD

**Issue by babywin** [popcorn-official/popcorn-android#38]
**App Version:**  0.2.8 - armeabi-v7a
**Android version:**  6.0.1

**Expected behaviour:** Change subtitles size while cast to chromecast. Also add an option to change the font.
**Actual behaviour:** Subtitles size do not always change their size and also there is no option to do this while casting to chromecast. Also there is no option to change the font for a serif one.

**Steps to repoduce the behaviour:**

1. Change the subtitles size on preferences
2. Watch a movie with subtitles and cast to chromecast
3. Remember the actual subtitles size showed on screen
4. Stop casting to chromecast
5. Increase the font size of the subtitle
6. Cast again
7. Compare the new size of the subtitle with the las one
8. There is no increase of the subtitle size at all

**Comment by cannnon** [comment]
our current chromecast implementation doesnt seem to support this, but we could look into changing this

**Comment by babywin** [comment]
Please guys. The other fork ".se" have that support. Maybe their code would help us.
Thanks a lot.

**Comment by cannnon** [comment]
i know how to do this, its just the implementation that makes this a lot of work
and ".se", they're not a fork and they don't have code available that works

**Comment by babywin** [comment]
Thanks for the answer @cannnon. I hope you make it when you have time.
