### ISSUE TITLE
Chromecast fab not there 

### ISSUE THREAD

**Issue by askalburgi** [popcorn-official/popcorn-android#399]
Version:  0.2.9 arm64 v8a
Download date: 
Android version:  Oreo 

#### Expected Behaviour

Chromecast fab on homescreen. It used to do this 

#### Actual Behaviour

Does not have that anymore 

#### Steps to repoduce the behaviour

1. Open the app 
2. No chromecast button appears 
3. ...

**Comment by MrRory** [comment]
there was never a Chromecast floating action button, the chromecast option should be in the appbar
