### ISSUE TITLE
It crash

### ISSUE THREAD

**Issue by BorisBagz** [popcorn-official/popcorn-android#407]
Version:  2.9
Download date:  31 August 2018
Android version:  One Plus 5T Android 8.1.0

#### Expected Behaviour

Play the video

#### Actual Behaviour

After some minutes watching a video it crashes

#### Steps to repoduce the behaviour

1. open the app
2. select a film/serie
3. watch it some minutes

**Comment by danpaul1177** [comment]
I m using a redrhino with no VPN
Used multiple players but still crashes
Any ideas would be great thx
Danny
