### ISSUE TITLE
external USB can't be set as cache folder in Android

### ISSUE THREAD

**Issue by TehKiwiz** [popcorn-official/popcorn-android#41]
Version:  3.9 
Download date:  Latest beta/Latest build from Jek
Android version:  4.4.2

#### Expected Behaviour
Set the cache folder to external USB (fat32 partition)

#### Actual Behaviour
Makes a toast that says "Can't write"

#### Steps to repoduce the behaviour
1. Connect an external storage like a USB
2. Try to set cache folder in preferences to a folder on USB/create folder using popcorn time
3. Get an error

**Comment by cannnon** [comment]
this is the expected behaviour, since the external storage is not writable

**Comment by onurtirpan** [comment]
I am having the same issue. Even that this is the expected behavior, is there any way to work around this issue?
