### ISSUE TITLE
Android TV subtitltes Not Working

### ISSUE THREAD

**Issue by cabarzua** [popcorn-official/popcorn-android#429]
Version:  Android TV 5.0 ARM
Download date:  14 Octubre
Android version:  Android TV 5.0 ARM Xiaomi Mybox

#### Expected Behaviour

1. Select Subtitles
2. Select Custom
3. Select path and select Subtitle.

#### Actual Behaviour

Nothing, not show the subtitles

#### Steps to repoduce the behaviour

1. ...Select buttom cc
2. ...Select Custom
3. ...Select path to subtitles
4. ... Select Subtitles

**Comment by SotiToki** [comment]
I have the same problem :(

**Comment by faogustavo** [comment]
Was this issue fixed?
