### ISSUE TITLE
The android app doesn't cast on chromecast

### ISSUE THREAD

**Issue by marco565** [popcorn-official/popcorn-android#43]
Version: 2.7.5.3
Download date:  08/06/2016
Android version:   6.0

#### Expected Behaviour
Cast the video on google chorme
...

#### Actual Behaviour
it doesn't works, the video continue to play on the phone, and the chrome cast doen' show anything.
...

#### Steps to repoduce the behaviour

1. ... Play a video
2. ... click on cast
3. ...click on chromecast

**Comment by cannnon** [comment]
please give more information about the behaviour and what kind of video youre trying to play
