### ISSUE TITLE
Something went wrong issue

### ISSUE THREAD

**Issue by tejasrana95** [popcorn-official/popcorn-android#431]
Version:  0.2.9
Download date:  24-11-2018
Android version:  8.1

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. top rated not working
2. Release date tab not working
3. A-z not working

**Comment by PragmaticEd** [comment]
Same issue on Note 8 Android 7.1.1

**Comment by remeister1111** [comment]
I see this is closed, guessing I should start new issue report- but just in case- the app has forgotten how to kindergarten, hahaha. I have a screenshot, but can't seem to get it out there.  Oh wells, a "random order"  tab is cool too.
