### ISSUE TITLE
Can't scrub to desired position.

### ISSUE THREAD

**Issue by Syborg49** [popcorn-official/popcorn-android#447]
Version: #162
Download date: 12/30/2018
Android version: 9 (pie)

#### Expected Behaviour
< I expected to skip to any part of the movie / to series that I wanted to>
...

#### Actual Behaviour
< It doesn't do that and instead it just puts a blank screen and I can just see the subtitle passing by>
...

#### Steps to repoduce the behaviour
<!-- What steps do we need to take to find the same bug that you found? --

1. open up any movie/TV show
2. skip to any part you want
3. it won't do that

**Comment by MrRory** [comment]
I've been working on this, the creator of the library we use already had something in place that kind of solved the problem. So I only had to replace some parts and he added extra things for me to work with. It's in this branch: https://github.com/popcorn-official/popcorn-android/tree/tc/torrentstream-server
