### ISSUE TITLE
settings don't update on Android TV version for Mi Box S

### ISSUE THREAD

**Issue by kk47042** [popcorn-official/popcorn-android#449]
Version:  1.4 for Android TV
Download date:  30.12.2018.
Android version:  8.1

#### Expected Behaviour

... App should change selected setting (for example default subtitle language)

#### Actual Behaviour

... App goes back to home screen without changing selected setting.

#### Steps to repoduce the behaviour

1. ... Open preferences.
2. ... Change default subtitle language.
3. ...

**Comment by MrRory** [comment]
I think this is the same as #456, let me know if it isn't
