### ISSUE TITLE
Check for updates loop on Android TV version for Mi Box S

### ISSUE THREAD

**Issue by kk47042** [popcorn-official/popcorn-android#450]
Version:  1.4 for Android TV
Download date:  29.12.2018.
Android version: 8.1

#### Expected Behaviour

... App would update or postpone update.

#### Actual Behaviour

... App is stuck on screen where user has to select wether he wants to install update now or postpone it for later no matter what is selected. 

#### Steps to repoduce the behaviour

1. ... Open Preferences.
2. ... Click Check for updates.
3. ... If there is a new update, app asks wether to install it now or later.
4. ... Whatever you choose, app stays in loop and asks if you want to install it now or later again.

**Comment by MrRory** [comment]
Can you try downloading the arm8a-v64 version and see if it acts the same.

**Comment by kk47042** [comment]
I tried it, but that version couldn't be installed.

**Comment by MrRory** [comment]
What do you mean by that? The Mi Box S should be a arm64 device.

**Comment by MrRory** [comment]
Try this one: https://ci.popcorntime.sh/job/Popcorn-Time-Android/lastSuccessfulBuild/artifact/tv/build/outputs/apk/tv-arm-development-169.apk

**Comment by kk47042** [comment]
Well I'm not sure why, but installation fails and I get "App not installed." message.

**Comment by MrRory** [comment]
Did you install the Ci version build 169?

**Comment by kk47042** [comment]
Yes, from the link you provided in previous comment.

**Comment by palradu** [comment]
I second this, but on the first gen MiBox. Same "Uhoh!" error appears after installing version 169: tv-arm-development-169.apk

**Comment by MrRory** [comment]
File systems are never 32 or 64-bit. But the Android version could be armv6 though

**Comment by MrRory** [comment]
Check https://ci.popcorntime.sh/job/Popcorn-Time-Android/170/

**Comment by palradu** [comment]
Fair enough 😊 Will try it as soon as I get home 😁

**Comment by kk47042** [comment]
Tried it out, works fine!
