### ISSUE TITLE
Android TV - Movies & TV Shows not Up to Date as Mobile App

### ISSUE THREAD

**Issue by a-haan** [popcorn-official/popcorn-android#454]
Version:  162
Download date:  02/01/2019
Android version:  

#### Expected Behaviour
Films and TV shows would be the same on both apps, Popular films that were just released do not show even in search.
...

#### Actual Behaviour
Shows an older list of films
...

#### Steps to repoduce the behaviour
Install the App as normal and browse for Films or TV Shows

**Comment by MrRory** [comment]
I'm not completely sure I grasp the issue. The movies and series in the app are all loaded from the same APIs. Maybe there is a constant that is different, but it should be the same.

**Comment by a-haan** [comment]
my mistake, the films are all there but the Categories aren't the same as what you have on the Mobile App.

For instance on Android TV you have Top Movies, Latest TV Series, More Movies and More Shows.

I would expect having the same Categories as the Mobile App will show the same Movies at the start.

Trending, Popular, Top Rated, Release Date, Year is what you have on the Mobile App.

**Comment by a-haan** [comment]
after further testing the movies do appear after searching, so you can access all films but for discovery purposes I think the Android TV app should be the same as the Mobile version

**Comment by MrRory** [comment]
If I remember correctly the 'More movies' and 'More shows' lanes do give the possibility to access those same filters as the tabs on the mobile version provide. I'm not a designer so I don't know how it would be better on TV.

**Comment by a-haan** [comment]
fixed in build 169 - great work!
