### ISSUE TITLE
Changing settings crashes the app

### ISSUE THREAD

**Issue by sulaimanob** [popcorn-official/popcorn-android#456]
Version:  tv-armeabi-v7a-development-162.apk
Download date:  8Mbps
Android version:  8.0.0

#### Expected Behaviour

...change the settings, saved and work perfectly

#### Actual Behaviour

... Any change in settings crashes the app immediately

#### Steps to repoduce the behaviour

1. go to settings
2. change any settings (example: subtitles default language)
3. app crashes

**Comment by MrRory** [comment]
Fixed in #461
