### ISSUE TITLE
Cannot navigate after selecting a movie

### ISSUE THREAD

**Issue by sulaimanob** [popcorn-official/popcorn-android#457]
Version:  armeabi-v7a-development-162.apk
Download date:  8Mbps
Android version:  8.0.0

#### Expected Behaviour

... Select a movie, navigate to the desired quality, and movie works perfectly

#### Actual Behaviour

Whenever I choose a movie, I cannot navigate to the desired quality, so I cannot start the movie at all

#### Steps to repoduce the behaviour

1. go to movies
2. select any one
3. no navigation after that, only I can go back

**Comment by marcuscarvalho** [comment]
@sulaimanob it is working for android v7 for me. I will double check with android v8 as well. If you could provide more details about your environment and attach a video reproducing the issue would be perfect.

**Comment by MrRory** [comment]
I think we should move this to #443. Since it is mostly the same. If all screenshots and reproductions are posted there we keep a better overview :)
