### ISSUE TITLE
Problems with sharp aquos TV 

### ISSUE THREAD

**Issue by esnover70** [popcorn-official/popcorn-android#46]
Version:  last version 
Download date:  4 days ago 
Android version:  5.0.1

#### Expected Behaviour

... Cast the movie to my sharp smart TV with DLNA communication. 

#### Actual Behaviour

... No cast to the SmartTV. 

#### Steps to repoduce the behaviour

1. ... Check the cast compatibility with sharp SmartTV aquos LC-70SQ17U 
2. ... Define a plug-in, complementary app or new upgrade to cast in Sharp SmartTV using DLNA way.
3. ... Test and release the new version or communicate and help.

**Comment by esnover70** [comment]
The app no cast to my TV.

**Comment by cannnon** [comment]
> Version: last version 
Srsly?
