### ISSUE TITLE
Stop beaming to chromecast 3

### ISSUE THREAD

**Issue by joaoluis89** [popcorn-official/popcorn-android#469]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

expected the app to bean the entire move even running on background or idle mode

#### Actual Behaviour

after a few seconds of beaming the transmission crashes

#### Steps to repoduce the behaviour

1. Choose a movie to watch
2. Beam it to a chromecast 3
3. Wait till it crashes

**Comment by MrRory** [comment]
I do not know what a Chromecast 3 is. Is it the Chromecast revision from 2018?

Anyways, without version, download date or Android version nobody will be able to help you properly. I'm putting this under issue #58 as general need for improvement. If you can gather the logcat output during a crash and post it in that issue that would be awesome.
