### ISSUE TITLE
Provider for a new anime provider

### ISSUE THREAD

**Issue by ChrisAlderson** [popcorn-official/popcorn-android#47]
Since the Haruhichan API does not work anymore I created another API for anime content. So the [`AnimeProvider`](https://github.com/popcorn-official/popcorn-android/blob/development/base/src/main/java/butter/droid/base/providers/media/AnimeProvider.java) needs to be changed to support this provider.

 - API endpoint: https://anime.api-fetch.website/
 - API documentation: http://docs.popcornofficial.apiary.io/

Hope the documentation will suffice, otherwise I'm here if you need me.

**Comment by ChrisAlderson** [comment]
Created the `AnimeProvider` myself, check: d12bf7eee54870b84feffc022ca4236ee15d8007

**Comment by cannnon** [comment]
Please remove all comments from the code (git has a history, so why comments?), do not use `Log.d` but `Timber.d` and confirm that you tested it

**Comment by ChrisAlderson** [comment]
I'll push forward on the `Timber.d` code. Yes I understand git has history, but git is also a tool and so is commenting code. I don't see how comments can 'hurt' the application, but I would like to hear your take on this.

**Comment by gjimenezf** [comment]
Maybe you could use the same that http://playview.io/ use.
