### ISSUE TITLE
Search Causes Crash/Reset

### ISSUE THREAD

**Issue by marbuser** [popcorn-official/popcorn-android#470]
Version: CI Build 170
Download date:  Today
Android version:  Android Pie
Box: Xiaomi Mi Box S

#### Expected Behaviour

The search should function correctly and display results.

#### Actual Behaviour

When typing in the search bar, the field resets back to the main screen without displaying search results.

#### Steps to repoduce the behaviour

1. Open Popcorn Time.
2. Click Search.
3. Type something in.

**Comment by Hangman228** [comment]
Here is a logcat of this issue :

W/GridLayoutManager:2131951980(29940): setSelectionSmooth should not be called before first layout pass
E/AndroidRuntime(29940): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime(29940): Process: pct.droid.tv.dev, PID: 29940
E/AndroidRuntime(29940): java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
E/AndroidRuntime(29940): 	at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2586)
E/AndroidRuntime(29940): 	at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeRemoved(RecyclerView.java:4967)
E/AndroidRuntime(29940): 	at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeRemoved(RecyclerView.java:11391)
E/AndroidRuntime(29940): 	at android.support.v7.widget.RecyclerView$Adapter.notifyItemRangeRemoved(RecyclerView.java:6811)
E/AndroidRuntime(29940): 	at android.support.v17.leanback.widget.ItemBridgeAdapter$1.onItemRangeRemoved(ItemBridgeAdapter.java:160)
E/AndroidRuntime(29940): 	at android.support.v17.leanback.widget.ObjectAdapter$DataObservable.notifyItemRangeRemoved(ObjectAdapter.java:98)
E/AndroidRuntime(29940): 	at android.support.v17.leanback.widget.ObjectAdapter.notifyItemRangeRemoved(ObjectAdapter.java:209)
E/AndroidRuntime(29940): 	at android.support.v17.leanback.widget.ArrayObjectAdapter.remove(ArrayObjectAdapter.java:129)
E/AndroidRuntime(29940): 	at butter.droid.tv.fragments.TVSearchFragment.addRow(TVSearchFragment.java:173)
E/AndroidRuntime(29940): 	at butter.droid.tv.fragments.TVSearchFragment.access$100(TVSearchFragment.java:49)
E/AndroidRuntime(29940): 	at butter.droid.tv.fragments.TVSearchFragment$2.onSuccess(TVSearchFragment.java:159)
E/AndroidRuntime(29940): 	at butter.droid.base.providers.media.MediaProvider$1.onResponse(MediaProvider.java:196)
E/AndroidRuntime(29940): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
E/AndroidRuntime(29940): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/AndroidRuntime(29940): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(29940): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(29940): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  552):   Force finishing activity 1 pct.droid.tv.dev/butter.droid.tv.activities.TVSearchActivity
W/InputDispatcher(  552): channel '10e72383 pct.droid.tv.dev/butter.droid.tv.activities.TVMainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  552): channel '10e72383 pct.droid.tv.dev/butter.droid.tv.activities.TVMainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  552): Attempted to unregister already unregistered input channel '10e72383 pct.droid.tv.dev/butter.droid.tv.activities.TVMainActivity (server)'
W/ActivityManager(  552): Service crashed 2 times, stopping: ServiceRecord{33d116fe u0 pct.droid.tv.dev/butter.droid.base.torrent.TorrentService}
W/VLC/VLCApplication(27666): onTrimMemory, level: 60


Hope this can help

**Comment by gitfamhub** [comment]
Happening to me too on an Nvidia Shield

**Comment by daviporciuncula** [comment]
Also have this issue on my Mi Box running Oreo
