### ISSUE TITLE
TV Series not loading correctly

### ISSUE THREAD

**Issue by a-haan** [popcorn-official/popcorn-android#471]
Movies are working perfectly at the moment other than a minor issue of the background art disappearing when watching a film then pressing back on the remote to go back to the Movie listing. When you do this the background art is gone.

TV Shows don't work when you first launch the app and pick a show from the 'Latest TV Series' Section they will show 'No synopsis available'. If you then go to 'More Shows' and choose any filter from the list such as 'top rated' and then into a show, the episodes will be present. you can then go back to the Home screen and the and use the 'Latest TV Series' as expected with all the episodes working. very strange behaviour. Once you do this Movies stop working unless you do a similar workaround as TV, got to More Movies and choose a filter then go to a random film then you're able to select a film quality.

**Comment by MrRory** [comment]
Could you please use the issue template and split the issue into two? One here, one new.

**Comment by a-haan** [comment]
Version:  170
Download date:  12/01/19
Android version:  Oreo

#### Expected Behaviour

... Play TV shows as soon as you open the app by navigating to a show

#### Actual Behaviour

... When I navigate to a TV show it says no synopsis found, please see this video which shows the issue on the Nvidia shield https://youtu.be/GBwXNSW1VzI

#### Steps to repoduce the behaviour


1. ... Launch app
2. ... Navigate to a TV show
3. ... No synopsis found, workaround in video

**Comment by a-haan** [comment]
New version of PCT is an improvement but, this but still exists.

**Comment by itumi** [comment]
same issue and same workaround on android tv app version 0.1.5 arm (0.1.6 arm cannot be tested because it closes after opening)
