### ISSUE TITLE
compile error   

### ISSUE THREAD

**Issue by zz5221** [popcorn-official/popcorn-android#472]
Version:  
Download date:  
Android version:  

Duplicate files copied in APK lib/x86_64/libjlibtorrent-1.2.0.16.so
	File1: D:\Users\lenovo\.gradle\caches\modules-2\files-2.1\com.frostwire\jlibtorrent-android-x86_64\1.2.0.16\1c173b58651917666334dcf1ce14867af2d20fab\jlibtorrent-android-x86_64-1.2.0.16.jar
	File2: E:\tv1\popcorn-android\base\build\intermediates\bundles\default\jni

**Comment by team-pct** [comment]
Try Disable NDK BUNDLE and retry
