### ISSUE TITLE
No data found

### ISSUE THREAD

**Issue by demac22** [popcorn-official/popcorn-android#474]
Version:  0.2.9
Download date: 1/12/19
Android version: 8.1.0 

#### Expected Behaviour
To load movies and shows
...

#### Actual Behaviour
It doesn't load movies and shows
It show message 'No data found' and 'Something went wrong'
...

#### Steps to repoduce the behaviour

1. ...I don't fuckin' know
2. ...
3. ...

**Comment by MrRory** [comment]
Can you confirm that this is still an issue?
