### ISSUE TITLE
Improve video player controls

### ISSUE THREAD

**Issue by sweatycorndog19000** [popcorn-official/popcorn-android#475]
The internal video player is great. But it would be nice to have the option to disable the volume controls and the seeking controls when you swipe your finger up or down or right or left. Also a nice feature would be to double tap on the left or right side of the screen and have it go forward or backwards 10 seconds.

**Comment by thamaraiselvam** [comment]
You can change the default player from to your favorite video player in preferences.

**Comment by MrRory** [comment]
> Also a nice feature would be to double tap on the left or right side of the screen and have it go forward or backwards 10 seconds.
I totally agree, this works great in the Youtube app.
