### ISSUE TITLE
Big Little Lies episodes missing

### ISSUE THREAD

**Issue by maharajc** [popcorn-official/popcorn-android#476]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

Episodes 1 to 7 should be there

#### Actual Behaviour

episodes 1,2,4,5 are missing

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by MrRory** [comment]
This is not the place to report these kinds of issues, please use the forum or reddit.
