### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by javivi235** [popcorn-official/popcorn-android#480]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by thamaraiselvam** [comment]
@javivi235  all data are empty

**Comment by MrRory** [comment]
Please use the complete template to provide us information. We cannot do anything without information :/

**Comment by javivi235** [comment]
How do i do that?
