### ISSUE TITLE
Material Design 2.0

### ISSUE THREAD

**Issue by rakleed** [popcorn-official/popcorn-android#481]
Could you please make the design of the application in the style of the updated Material Design (or Material Design 2.0)? Examples of applications with updated design: Google Keep, Google Contacts, Google News, Android Messages, Google Fit, Solid Explorer, Google Photos, Google Maps.

**Comment by MrRory** [comment]
What is Material Design 2.0 according to you? What should change? We're not designers and I honestly don't see a big difference.

**Comment by Rakleed** [comment]
> What is Material Design 2.0 according to you?

Updated icons, active use of contrasting colors, Google Sans, rounded edges, transparent elements, minimalism.

**Comment by MrRory** [comment]
So you're looking at Google's [Material Theming](https://material.io/design/material-theming/overview.html#using-material-theming) implementation of Material Design. Google Sans is not open for use by everyone, you can use Material Design with every kind of edge, icon or element types. If we would decide to use the same colors there wouldn't be very much of a difference I think.

**Comment by Rakleed** [comment]
> If we would decide to use the same colors there wouldn't be very much of a difference I think.

When Google announced the updated Material Design, it was said that the updated design will provide more opportunities for creating individual design. Well, I'm not a designer, I just like what design Google does in its products.
