### ISSUE TITLE
App freezes whenever I want to watch a TV Show.

### ISSUE THREAD

**Issue by CrystalDynamic5** [popcorn-official/popcorn-android#483]
Version: 4.0.3 and above
Download date:  20 January 2019
Android version:  6.0

#### Expected Behaviour
 
Play the TV Show normally without freezing.

#### Actual Behaviour

The app freezes and doesn't download anything.

**Comment by MrRory** [comment]
> Version: 4.0.3 and above

We don't have these kind of version numbers. Our latest release is 0.2.9.
