### ISSUE TITLE
Series and anime doesn't load 

### ISSUE THREAD

**Issue by maythhew** [popcorn-official/popcorn-android#487]
Version:  0.2.9
Download date:  25/01/2019
Android version:  4.0.3+

#### Expected Behaviour

Open shows or anime without freezing

#### Actual Behaviour

In the shows it opens but freezes when "waiting for torrent" then closes. In the anime tab font evento open. Móveis are normal

#### Steps to repoduce the behaviour

1. Open popcorn time on 4.0+ devices
2. Open any episode of any show
3. Or open anime tab

**Comment by maythhew** [comment]
![screenshot_2019-01-29-20-38-55](https://user-images.githubusercontent.com/47164444/52006124-28db1f00-24aa-11e9-9b93-dc6ee775ab7a.png)

In shows it freezes like this

In the anime tab i cant even make the screenshot

> Version: 0.2.9
> Download date: 25/01/2019
> Android version: 4.0.3+ (Android box)
> 
> #### Expected Behaviour
> Open shows or anime without freezing
> 
> #### Actual Behaviour
> In the shows it opens but freezes when "waiting for torrent" then closes. In the anime tab font evento open. Móveis are normal
> 
> #### Steps to repoduce the behaviour
> 1. Open popcorn time on android box devices
> 2. Open any episode of any show 
> 3.

**Comment by MrRory** [comment]
Does the progress bar move?

**Comment by maythhew** [comment]
Nop. Just stops and after sometime closes

**Comment by maythhew** [comment]
Btw i use the mobile version(v7a) cause the TV onde doesnt work (install) here :)

**Comment by MrRory** [comment]
So it moves at first?

**Comment by maythhew** [comment]
Yup

**Comment by MrRory** [comment]
Hmm. What kind of Android box is this? Sounds like the native library that handles the torrents doesn't run really smoothly.
