### ISSUE TITLE
Android TV Box 6.0 Status Bar Not Hiding

### ISSUE THREAD

**Issue by soavarice** [popcorn-official/popcorn-android#49]
**Version:**  3.9 (Adroid 1.3)
**Download date:**  09.10.2016
**Android version:**  6.0
**Photo:** http://i.imgur.com/4EUev3l.jpg

**Expected Behaviour**
Hide the top bar when app is started

**Actual Behaviour**
Bar is still visible and its not nice when watching the movie

**Steps to repoduce the behaviour**

1. Start the App on 6.0 Android
2. See the line on top
3. Start the movie and the bar still visible

**Comment by cannnon** [comment]
Try the Android TV version, much better in this usecase
