### ISSUE TITLE
Subtitles not casted to tv

### ISSUE THREAD

**Issue by EvaVonBraun** [popcorn-official/popcorn-android#492]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...
I thought I would see the subtitles on my smarttv. 
#### Actual Behaviour

Not showing them ...

#### Steps to repoduce the behaviour

1. Fix this, please. ...
2  I get subtitles, but then the screen format is not right. It fills up the whole TV screen, which does not give me the right images. The people are stretched vertical, but with subtitles and that is not how you meant it. On my phone I can see it, like you meant it, but something goes wrong while I cast it  I can't change it in the 'tmenu. . ...
3. ...

**Comment by MrRory** [comment]
Please enter all information in the issue template, without this information we are unable to help you.
