### ISSUE TITLE
Spider man 1\spider man 3

### ISSUE THREAD

**Issue by lolpowerluke** [popcorn-official/popcorn-android#494]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

Let me see the right movie

#### Actual Behaviour

Let me see the wrong movie

#### Steps to repoduce the behaviour

1. Search spider man
2. Choose spider man 1
3. You will see spider man 3 instead of spider man 1

**Comment by MrRory** [comment]
First I'd like to ask you to enter the complete issue template next time you open an issue.

This issue is more related to the results we get back from the server and cannot be solved in the app. Open an issue in the popcorn-api repository.
