### ISSUE TITLE
Popcorn Time

### ISSUE THREAD

**Issue by ossamatalaat** [popcorn-official/popcorn-android#495]
Version:  2018
Download date:  
Android version:  0.2.9 - arn

#### Expected Behaviour
 casting on tv
...

#### Actual Behaviour

... Rarely do the casting, sometimes casting option is not even available

#### Steps to repoduce the behaviour

1. ... try to cast
2. ... I usually have to disconnect from network and reconnect in order to have the casting botton
3. ... When clicking it doesn't work properly

**Comment by MrRory** [comment]
Please enter the issue template completely. Without information we cannot help you.
