### ISSUE TITLE
Chromecast don't appear

### ISSUE THREAD

**Issue by misumma** [popcorn-official/popcorn-android#496]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ... Open the aop
2. ... Push the button to cast the video
3. ... Samsung dlna is there but Chromecast isn't

**Comment by recamartin** [comment]
I have the same problem

**Comment by misumma** [comment]
At me Chromecast appear like option after a long time, like 10-15 minutes .... 
Now it work!
Regards,

**Comment by MrRory** [comment]
See #58 #74 and #181
