### ISSUE TITLE
Pelis Magnet Keeps Stopping 

### ISSUE THREAD

**Issue by MissBastet** [popcorn-official/popcorn-android#504]
Version:  0.3.0 - armeabi-v7a
Download date:  2/27/19
Android version:  8.0.0.

#### Expected Behaviour

I thought the app would open the torrent either on the internal player or my external player 

#### Actual Behaviour

...
as soon as I click on the play button I get an error message saying pelis magnet keeps stopping and kicks me out. I this seems to happen with shows only because movies just say esperando torrent and nothing happens. I've tried using a VPN using a different player restarting my phone ect

#### Steps to repoduce the behaviour

1. ... got to series
2. ...click on The Flash
3. ... click season 5 ep 1

**Comment by MrRory** [comment]
We don't have a version 0.3.0
