### ISSUE TITLE
Game of Thrones

### ISSUE THREAD

**Issue by ja920ke** [popcorn-official/popcorn-android#506]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

Play Game of Thrones season 4 episode 7

#### Actual Behaviour

Freezes while trying to load show or it starts and then freezes. I have only got it to olay 4 minutes of the show then it stops

#### Steps to repoduce the behaviour

1. Click shows
2. Find game of thrones
3. Play season's 4 episode 7

**Comment by MrRory** [comment]
Please fill out the complete issue template, without any info we cannot help you.
