### ISSUE TITLE
Chrome cast not being detected

### ISSUE THREAD

**Issue by EberliAugusto** [popcorn-official/popcorn-android#509]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

 Most of the times chromecast  is not detected.

#### Steps to repoduce the behaviour
Just open the app on wifi, the chromecast most likely wont be detected.

**Comment by MrRory** [comment]
Please fill out the complete issue template, without any info we cannot help you.

Also, duplicate of #58.
