### ISSUE TITLE
Audio language selection is absent in android 

### ISSUE THREAD

**Issue by andreykuzin** [popcorn-official/popcorn-android#510]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

There must be option to select various languages of audio as it is available in TV version.

#### Actual Behaviour

Does not have this option.

#### Steps to repoduce the behaviour

1. Try to find language selection button.
2. ...
3. ...

**Comment by MrRory** [comment]
I'm not sure what you're talking about, but the Android mobile, tv and the desktop app all do not allow any audio selection.
