### ISSUE TITLE
App launched with 'No Connection' status for movies and shows - Seems Apis not working

### ISSUE THREAD

**Issue by Awais-Ali** [popcorn-official/popcorn-android#512]
Version:  
Download date:  
Android version:  8.0

#### Expected Behaviour

...Should show movies/shows on the main screen

#### Actual Behaviour

... NOT showing/loading movies and shows on the main screen

#### Steps to reproduce the behaviour
 I got the code from your website (Not GitHub) https://getpopcorntime.is/source.html for ANDROID APP

This code doesn't have any URL to fetch movies and all....can you please help me as I don't see any movie on App Launch.

1. ...
2. ...
3. ...

**Comment by Awais-Ali** [comment]
@MrRory @team-pct @vzamanillo @hackhackhack Please help!

**Comment by vzamanillo** [comment]
https://getpopcorntime.is is not popcorn-official, https://popcorntime.sh/ is and you can download or checkout the code here, on popcorn-official/popcorn-android GitHub.

**Comment by Awais-Ali** [comment]
I also got it from GitHub repo but it gives me this error

Android resource compilation failed
Output:  D:\Reports\popcorn-android\mobile\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:656: error: duplicate value for resource 'attr/fontFamily' with config ''.
D:\Reports\popcorn-android\mobile\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:656: error: resource previously defined here.

Command: C:\Users\appla\.gradle\caches\transforms-2\files-2.1\6ec468dfad2af49e106f3ce248dcc756\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        D:\Reports\popcorn-android\mobile\build\intermediates\res\merged\debug \
        D:\Reports\popcorn-android\mobile\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

**Comment by Awais-Ali** [comment]
@vzamanillo 

Android resource compilation failed
D:\Reports\popcorn-android\mobile\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:4029: error: duplicate value for resource 'attr/fontFamily' with config ''.
D:\Reports\popcorn-android\mobile\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:4029: error: resource previously defined here.

**Comment by Awais-Ali** [comment]
@vzamanillo this error is with '**development**' branch - I would be glad if you can send me a working project.

**Comment by MrRory** [comment]
You should not have updated any of the dependencies. Just clone the repo and install SDK 25 with build tools 25.0.3.

**Comment by Awais-Ali** [comment]
Please update the SDK to latest one 28/29. We have to integrate it with another SDK that requires the latest SDK.

gradle 5.2.1

support libs 28.0.0
build tools 28.0.3
compile/target sdk 28
min sdk 16
