### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PhelipeMT** [popcorn-official/popcorn-android#516]
Version:  
Download date: 24/03/2019
Android version:  0.2.9

#### Expected Behaviour
 assistir filmes e séries 
...

#### Actual Behaviour
 o aplicativo fecha sozinho
...

#### Steps to repoduce the behaviour

1. ...abra o aplicativo 
2. ...abra o filme 
3. ... ele irá fechar sem minha permissão

**Comment by MrRory** [comment]
Sorry, we only speak English
