### ISSUE TITLE
Play error

### ISSUE THREAD

**Issue by damiene92** [popcorn-official/popcorn-android#517]
Version:  0.2.9
Download date:  
Android version:  One Ui

#### Expected Behaviour

...play the movie correctly

#### Actual Behaviour

...plays up to 1 minute then freezes, its on every movie, ive redownloaded on multiple occasions and nothing helped.
#### Steps to repoduce the behaviour

1. ...pick a movie and play it
2. ...
3. ...

**Comment by MrRory** [comment]
Please give us some more information, what kind of phone do you have? Wi-Fi or cellular connection?
