### ISSUE TITLE
Não sai da tela "esperando por torrent"

### ISSUE THREAD

**Issue by Gabis0408** [popcorn-official/popcorn-android#518]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ... Não consigo ver séries pois o vídeo não carrega 
2. ... Não sai da tela esperando por torrent
3. ... Aparece que carregou quase tudo e logo em seguida trava

**Comment by MrRory** [comment]
I'm sorry, without version information we cannot help you.
