### ISSUE TITLE
Subtitles doesn't work with chromecast

### ISSUE THREAD

**Issue by idanlo** [popcorn-official/popcorn-android#520]
Version:  0.2.9 - arm64-v8a
Download date:  
Android version:  9

#### Expected Behaviour
Streaming movies to chromecast should also show subtitles and it does not (even after setting default subtitle language in settings). 
...

#### Actual Behaviour
Subtitles are not showing up on chromecast.

**Comment by MrRory** [comment]
I'm referencing #58  for general Chromecast problems and marking this as duplicate.

**Comment by idanlo** [comment]
@MrRory the issue you referenced has been closed for 2 years
