### ISSUE TITLE
Playing a show

### ISSUE THREAD

**Issue by faizanw98** [popcorn-official/popcorn-android#522]
Version:  
Download date:  
Android version:  

#### Expected Behaviour
Play game of thrones
...

#### Actual Behaviour

...Showed a photo and didn't respond

#### Steps to repoduce the behaviour

1. ...Open game of thrones
2. ...Select season 1 episode 1
3. ...Play the episode

**Comment by MrRory** [comment]
I'm sorry, without version information we cannot help you.
