### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by GabriellaPerico** [popcorn-official/popcorn-android#524]
Version:  0.2.9 arm
Download date:  April 22
Android version:  8.1.0

#### Expected Behaviour

...

#### Actual Behaviour

... When I transmit the movie to the smartTv the subtitles don't appear, but while is just in the cellphone, works perfectly and sometimes the app stops working when I transmit

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by GugaVaz** [comment]
Please... I'm having te same problem. How did you solved it?
