### ISSUE TITLE
Trailers do not work on AndroidTV

### ISSUE THREAD

**Issue by marbarfa** [popcorn-official/popcorn-android#53]
Operating System Version:
Nexus Player - 6.0.1

Popcorn Time Version:
0.1.3

Download date:
2015

Expected Behaviour

Play the trailer
Actual Behaviour

The app crashes
Steps to reproduce the behaviour

Select a movie
Select "play trailer"

**Comment by MrRory** [comment]
The trailer value is most likely 'null'
