### ISSUE TITLE
Tv Shows are freezing on buffering screen. Only can see picture.

### ISSUE THREAD

**Issue by pabloalbella** [popcorn-official/popcorn-android#531]
Version:  lastest
Download date:  5.2.2019
Android version:  8

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by garebello** [comment]
Same issue here.

Version 0.2.9 arm, android 7.1.1
Load only movies, the app crashes on buffering screen after a while.

**Comment by MrRory** [comment]
Please provide a version in your bug reports.
