### ISSUE TITLE
App Crashes when play daredevil

### ISSUE THREAD

**Issue by thamaraiselvam** [popcorn-official/popcorn-android#534]
Version:  
Download date:  10/May/2019
Android version:  8.0

#### Expected Behaviour
Should play daredevil series session 1 episode 1

#### Actual Behaviour
App crashes

#### Steps to repoduce the behavior 
1. Go to series page and search daredevil
2. Try to play episode 1 from session 1
![Screenshot_20190510-224257](https://user-images.githubusercontent.com/6559664/57544588-625ada80-7375-11e9-83bb-7a36ff5620b3.jpg)

**Comment by MrRory** [comment]
Please provide more information in your bug reports.

**Comment by thamaraiselvam** [comment]
What more information you want? I gave all instructions to reproduce the issue.
