### ISSUE TITLE
subtitles PT-BR

### ISSUE THREAD

**Issue by Bobbyhw** [popcorn-official/popcorn-android#535]
Version: 3.10
Download date: 10/05/2019 // 14:41  
Android version: PC

#### Expected Behaviour
Watch Doctor Strange with the subtitles correct

#### Actual Behaviour
I'm trying to watch Doctor Strange in the caption in PT-BR, but the caption is very advanced, the caption appears and the character speaks only after a long time

#### Steps to repoduce the behaviour
just watch Doctor Strange in PT-BR subtitles

OBS: My English is very bad, so...

**Comment by Persei08** [comment]
This is not a bug, subtitles are just bad sometimes. Popcorntime cannot garantee the subtitle quality, it just try to find the best one from opensubtitles.org, download it, and display it. 

Check on opensubtitles and report the bad subtitles there
