### ISSUE TITLE
Android TV: Search causes the Android TV Popcorn Time to refresh

### ISSUE THREAD

**Issue by dwm1909** [popcorn-official/popcorn-android#538]
Version:  
Download date:  
Android version:  170

#### Expected Behaviour
Be ablet to write a search or use voice with out a frefresh. 
...

#### Actual Behaviour
When you write 3 charters into search by keyboard, the app shutdown search keyboard by refresh and go back to homescreen, voice input dosent work. 
...

#### Steps to repoduce the behaviour
Press search and use keyboard on atlest TCL Android TV 8.0 and the make a full search. 

1. ...
2. ...
3. ...

**Comment by MrRory** [comment]
Please provide more information in your bug reports.
