### ISSUE TITLE
Loading/buffer issue **critical**

### ISSUE THREAD

**Issue by nvivek1** [popcorn-official/popcorn-android#539]
Version:  latest 
Download date:  15th may 2019
Android version:  8.1 oreo 
                 Redmi note 5 pro (whyred)

#### Expected Behaviour
it kept on buffering in the background while the video kept playing....
...

#### Actual Behaviour

...the app stops playing video but plays videos only for some time that ,only the initial buffer before playing the video only that plays and goes still forever after that

#### Steps to repoduce the behaviour

1. ...open app
2. ...select video and wait till it buffers it opens a player and starts playing 
3. ...and it stops after sometime the video freezes as it is stuck

**Comment by MrRory** [comment]
Please provide more information. Version for example.
