### ISSUE TITLE
Se detiene cada 2 minutos

### ISSUE THREAD

**Issue by Luisbonillat** [popcorn-official/popcorn-android#54]
Version: 0.3.0-armeabi-v7a
Download date:  octubre 15 de 2016
Android version:  5.0

#### Expected Behaviour

...se cierra no deja ni explorar y menos ver una película streaming 

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...la abro
2. ...estoy viendo y aveces no pasa ni dos minutos
3. ..pelismeg.net se detubo

**Comment by Luisbonillat** [comment]
Saber si la versión es compatible o es otro error

**Comment by ChrisAlderson** [comment]
English
