### ISSUE TITLE
No subtitles in DLNA casting. Chromecast support?

### ISSUE THREAD

**Issue by vlbastos** [popcorn-official/popcorn-android#540]
Version:  0.2.9 - arm
Download date:  05/16/2019
Android version:  8.0.0

#### Expected Behaviour
1. Cast movies WITH SUBTITLES to DLNA TVs, or
2. Support Chromecasting WITH SUBTITLES. - EDIT: Chromecast support started working out of nowhere, and subtitles DO WORK with Google Casting.

#### Actual Behaviour
1. NO SUBTITLES when casting to my DLNA Smart TV (LG WebOS 05.80.15), and
2. No support for Chromecast. - EDIT: Yes it does support.

#### Steps to repoduce the behaviour
1. Choose any movie
2. Configure any subtitle
3. Start playing
4. Cast to DLNA TV
5. No subtitles are shown

**Comment by MrRory** [comment]
DLNA has never had official subtitle support, only half-baked implementations. The app does it's best to use those but it won't always work.
