### ISSUE TITLE
Series never work

### ISSUE THREAD

**Issue by srfayad** [popcorn-official/popcorn-android#542]
Version:  0.2.9 - arm64-v8a
Download date: 25/05/2019
Android version:  Galaxy s6 edge

#### Expected Behaviour

...
Allow me to watch movies and series

#### Actual Behaviour

...
Dont allowed me to watch movies and series
#### Steps to repoduce the behaviour

1. ... i just open the stream and ot freezes
2. ...
3. ...

**Comment by MrRory** [comment]
Please provide more information in your reports.
