### ISSUE TITLE
Popcorntime does not work with the Orange internet provider.

### ISSUE THREAD

**Issue by rubenbraek1** [popcorn-official/popcorn-android#543]
Version:  any
Download date:  30/05/2019
Android version:  8.10

#### Expected behaviour
Watching movies.

#### Actual Behaviour
Does not load anything at all.

#### Steps to repoduce the behaviour
Open the app with Orange as your internet provider.

**Comment by Persei08** [comment]
Issue related to ISP network settings... Orange probably faking DNS entries to block Popcorn API... You should be able to bypass that by switching your DNS for google DNS or Cloudflare DNS

**Comment by rubenbraek1** [comment]
Thanks for the help, it worked.
