### ISSUE TITLE
While watching a serie

### ISSUE THREAD

**Issue by savvikos** [popcorn-official/popcorn-android#544]
Version:  0.2.9
Download date:  
Android version:  9

#### Expected Behaviour

To normally play the episodes without bugging

#### Actual Behaviour

Stuck to a point where it was buffed and start the episode from the beginning and also the speed of the internet my phone shows me that is used isn't similar to what the app shows when it downloads the episode.

#### Steps to repoduce the behaviour

1. open and episode
2. let the episode play until it will stuck

**Comment by MrRory** [comment]
Please provide more information in your reports.
