### ISSUE TITLE
Problem with search

### ISSUE THREAD

**Issue by mikednite** [popcorn-official/popcorn-android#547]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...tried to search by release date ?

#### Actual Behaviour

...app closed unexpectedly

#### Steps to repoduce the behaviour

Open in android move from trending past popular to release date and search always closes unexpectedly on release date and year search I just did a factory reset and it started doing this but it's a fresh install
1. ...
2. ...
3. ...

**Comment by MrRory** [comment]
Please provide more information in your reports.
