### ISSUE TITLE
App freezes when type of connection is switched

### ISSUE THREAD

**Issue by ecavicc** [popcorn-official/popcorn-android#549]
Version:  0.2.9 - arm
Download date:  second half of April
Android version:  9
Phone: Xiaomi Redmi Note 7
MIUI version: Global 10.3.4 Stable

#### Expected Behaviour

When switching to mobile data from WiFi or vice versa the app should continue to function normally and keep downloading what the user is watching.

#### Actual Behaviour

The app freezes even when browsing movies or TV series (not downloading) if the type of connection is switched. The only way to make it work again is a force close.

#### Steps to reproduce the behaviour

1. Open the app while using WiFi or mobile data
2. Switch to the type of connection not used in pt. 1

**Comment by MrRory** [comment]
https://github.com/popcorn-official/popcorn-android/issues/486
