### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by kasparov1997** [popcorn-official/popcorn-android#550]
Version:  0.2.9 - arm
Download date:  25/04/2019
Android version:  9

#### Expected Behaviour

...
To stream anime 
#### Actual Behaviour

...app crashes when i open anime and press play button to stream 

#### Steps to repoduce the behaviour

1. ...open the app
2. ...go to anime section and choose any show 
3. ..press play button to start stream

**Comment by MrRory** [comment]
Please provide more information in your reports.
