### ISSUE TITLE
Bug with series, animes and some movies

### ISSUE THREAD

**Issue by popcornbae** [popcorn-official/popcorn-android#551]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

... I thought it should play movies, series and animes correctly without any bug.

#### Actual Behaviour

...  Is not loading the series and anime, and sometimes takes so long that the cell phone hangs. And some movies are too slow to start.

#### Steps to repoduce the behaviour

1. ... Choose a serie or anime
2. ... Select season and episode
3. ... Press play.

**Comment by MrRory** [comment]
Please provide more information in your reports.
