### ISSUE TITLE
No caption on Android TV variant

### ISSUE THREAD

**Issue by christopherney** [popcorn-official/popcorn-android#553]
Version:  
Download date: 13 July 2019 - tv-armeabi-v7a-release-0.1.4.apk
Android version: Android TV 7.0

#### Expected Behaviour
Be able to select subtitle - like French

#### Actual Behaviour
Only two options available :  "No Subtitle" or "Custom"

#### Steps to reproduce the behaviour
1. Start a movie
2. Clic on caption button
3. The caption Pop-up selection is open, but no way to select caption

**Comment by MrRory** [comment]
Sounds like this was when the API wasnt working
