### ISSUE TITLE
How can I change audio language for the movies? For example, in settings we have Default Language for subtitles, I want another one for audio. Thanks 

### ISSUE THREAD

**Issue by davidgamez604** [popcorn-official/popcorn-android#554]
Version:  
Download date:  7-15-2019
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. Add audio Track for movies
2. ...
3. ...

**Comment by Persei08** [comment]
You can't... This feature don't exist at the moment

**Comment by davidgamez604** [comment]
Is there a way to change the default video player for android TV app v0.1.4?
Thanks

**Comment by davidgamez604** [comment]
Is there a way to change the default video player for android TV app v0.1.4/ The option is available in android mobile app but not in android TV? ( I want to set VLC as default player)
Please help me to make changes in code
Thanks

**Comment by Persei08** [comment]
I have no idea, I'm not an android dev

**Comment by MrRory** [comment]
Our API does not provide this options
