### ISSUE TITLE
Every time I start a movie or show I starts to play then  in a minute or so it shuts down How do I fix this problem?

### ISSUE THREAD

**Issue by Frederickstewartss** [popcorn-official/popcorn-android#555]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
Can't reproduce. Provides more details

**Comment by MrRory** [comment]
Please provide more information.
