### ISSUE TITLE
Android 9. Problems with app.

### ISSUE THREAD

**Issue by Kvd18** [popcorn-official/popcorn-android#559]
Version:  0.29 arm
Download date:  August 12, 2019
Android version:  9.0 Pie

#### Expected Behaviour
 Work like desktop version.
...

#### Actual Behaviour

... Don't download, don't show progress, the sound starts without play and it can't be stopped, can't continue the download after close the application (The clear cache option its off) delete the progress and starts again

#### Steps to repoduce the behaviour

1. ... Open the application
2. ... Play a movie (I do with two different)
3. ... Paused it and turn off the screen. When you unblock the device it will play the sound.

Samsung J6

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
