### ISSUE TITLE
Wi-fi bug

### ISSUE THREAD

**Issue by ThomasRamos** [popcorn-official/popcorn-android#562]
Version:  
Download date:  08/09/2019
Android version:  9

#### Expected Behaviour

i wasnt expected the app used my data tô download.

#### Actual Behaviour

Even the option of "only use wi-fi" is unable, this app fucked up my whole internet data.

#### Steps to repoduce the behaviour

1. download a movie while the wi-fi is off and the " use only with wi-fi" option is enable?
2. ...
3. ...

**Comment by MrRory** [comment]
Please provide more information.
