### ISSUE TITLE
Cannot open with WiFi enabled 

### ISSUE THREAD

**Issue by Bradley-99** [popcorn-official/popcorn-android#565]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...ooen amd play movies over WiFi

#### Actual Behaviour

... Only opens with lte on if wifi is on i get a blank screen. 

#### Steps to repoduce the behaviour

1. ...have a LG stylist 4
2. ... Sideload the app 
3:'... Open it sheet install with lte and worked fine although i have not played something yet
4: ... Turn on WiFi so i could watch something then it froze my whole oho6ne then i cleared it stared it again. Few time and it was just a blank screen all ten time i tried. 
5: ... Contacted you guys to fix the bug or fix what I'm doing worng but I'm tech savvy so i know i didn't do anything wrong.

**Comment by MrRory** [comment]
Please provide more information. Version for example.
