### ISSUE TITLE
How to change the default player on Popcorn Time 1.4 For Android TV 5.0 and above (ARM v7a)?

### ISSUE THREAD

**Issue by srLinares** [popcorn-official/popcorn-android#567]
Version:   Popcorn Time 1.4 For Android TV 5.0 and above (ARM v7a)
Download date:  19-09-19
Android version:  6.0

#### Expected Behaviour

Give the option to change the default player. 

#### Actual Behaviour

No option for changing anymore. Before you were able to choose between MX Player or the integrated one.

#### Steps to repoduce the behaviour

1. Open
2. Settings
3. No option for changing the Default player!

**Comment by kikoncuo** [comment]
Horrible decision, just a power grab by other devs to force us to use a default player full of commercials...
