### ISSUE TITLE
Windows 10 - blank screen on any build.

### ISSUE THREAD

**Issue by NesooseN** [popcorn-official/popcorn-android#57]
Version:  Build #159
Download date:  21 Oct 2016
Windows version:  Windows  10

#### Expected Behaviour

... It should load movies, but it just show blank space

#### Actual Behaviour

... Nothing, load load and then show blank page.

#### Steps to repoduce the behaviour

1. ... Install on Windows 10 version 1607
2. ... Start 
3. ... Nothing is showing

**Here error from Developer console:** http://pasteboard.co/hEExG3WxJ.jpg

Normal installation from https://popcorntime.sh/en is working OK, but any development build that I tested do not work, just blank space where it should show movies/series

**Comment by ChrisAlderson** [comment]
This repo is about the android version, not the desktop version.
