### ISSUE TITLE
Player freeze 

### ISSUE THREAD

**Issue by derhabdu** [popcorn-official/popcorn-android#570]
When i watch a video and s roll past buffered region the entire app freezes.

**Comment by joao-neves95** [comment]
I also have this issue

**Comment by Franchute13** [comment]
Same problem
Tested with Android 6 and Android TV 8 (both ARM)
Popcorn version, # 170 9/1/2019

**Comment by MrRory** [comment]
https://github.com/popcorn-official/popcorn-android/issues/486
