### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by fenice1984** [popcorn-official/popcorn-android#572]
Version:  0.2.9 - arm
Download date:  06 octber 2019
Android version:  9 PKQ1. 180729.001

#### Expected Behaviour

I can't fix subtitle

#### Actual Behaviour

doesn't working options subtitle

#### Steps to repoduce the behaviour

1. ...?
2. ...
3. ...

**Comment by MrRory** [comment]
Please provide more information.
