### ISSUE TITLE
Popcorn Time Media Player won't let me buffer time skip movie / show

### ISSUE THREAD

**Issue by RFL0WGitPR** [popcorn-official/popcorn-android#573]
Version:  Popcorn Time apk ver. 2.9
Download date:  
Android version: Android 9 Pie / Android 10

#### Expected Behaviour
Would allow me to Fast Forward the Movie or Scene Skip to The Timeline on the Movie where I wanted the Movie to Play like normally
...

#### Actual Behaviour

... Won't let me fast forward / skip / scrub jump to scene during movie or show 

Players Controls stop working after a while

#### Steps to repoduce the behaviour

1. ...Play any Movie or Show on Popcorn Time on a Samsung Galaxy S8/S9 running Android 10 / Android Pie 
2. ...Try to time skip or Fast Forward a Movie using a Samsung Galaxy S9 / S8
3. ...Let the movie load for a while and things start to be innoperable

**Comment by Stephan2620** [comment]
I have the same problem

**Comment by MrRory** [comment]
https://github.com/popcorn-official/popcorn-android/issues/486
