### ISSUE TITLE
chromecast from mobile or desktop , never worked for me , any idea why

### ISSUE THREAD

**Issue by Tarekkh92** [popcorn-official/popcorn-android#574]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

show my mobiles screen video from popcorntime 

#### Actual Behaviour

...
says connected and its not

#### Steps to repoduce the behaviour

1. cast anything from mobile or pc , android or windows
2. click the cast
3. wait for cast to come up , bever does

**Comment by MrRory** [comment]
Duplicate of #247
