### ISSUE TITLE
Slow mobile download

### ISSUE THREAD

**Issue by dcerovic** [popcorn-official/popcorn-android#575]
Version:  0.2.9
Download date:  1 month ago
Android version:  9 PKQ1.190302.001

#### Expected Behaviour
 Download at a comparable speed to the desktop version (and the mobile version on previous phone) when the number of peers is high
...

#### Actual Behaviour

Much slower download for same files as the desktop version. Even with 50+ peers on blockbuster movies and external magnet links, the download stays below 100kbps

#### Steps to repoduce the behaviour

1. Try downloading anything on Xiaomi 9T
2. ...
3. ...

**Comment by MrRory** [comment]
Duplicate
