### ISSUE TITLE
Not responding after 5-10 mins in a movie.

### ISSUE THREAD

**Issue by xMikeyHD** [popcorn-official/popcorn-android#577]
Version: 0.2.9
Download date: 17 Oct, 2019  
Android version: 10.0.1 

#### Expected Behaviour

Launch a movie, play it and being able to pause etc. Normal behaviour.

#### Actual Behaviour

After 5 minutes the subtitles freeze, the screen continues playing movie but on touch nothing appears and if touched enough times, a pop up says that the app isnt responding. Happens every time with every movie.

#### Steps to repoduce the behaviour

1. Download via popcorntime.sh
2. Own a OnePlus 7Pro
3. Resolution set to 1080p
4. Same version.
5. Subtitles on

**Comment by MrRory** [comment]
https://github.com/popcorn-official/popcorn-android/issues/486
