### ISSUE TITLE
App continuously becomes unresponsive 

### ISSUE THREAD

**Issue by BenPhilpott99** [popcorn-official/popcorn-android#580]
Version:  latest
Download date:  24/11/19
Android version:  latest

#### Expected Behaviour

...
Work without problems 
#### Actual Behaviour

...app continously "does not respond" during videos playing, making the video pause and go to a black screen that makes phones unresponsive. App becomes completely unresponsive and unusable with a black screen continuously with "app is not responding" being shown on screen

#### Steps to repoduce the behaviour

1. ... Use the app
2. ... It won't work
3. ... Freezes

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
