### ISSUE TITLE
App stuck

### ISSUE THREAD

**Issue by sandeep-sriramula** [popcorn-official/popcorn-android#581]
Version:  0.2.9 -arm
Download date:  25/11/19
Android version:  8.0

#### Expected Behaviour

When I switch mobile data to wifi or wifi to mobile data app gets stuck and needs to be restarted.Even we reopen the application it wont open.We need to open any other application and later we need open this app.

#### Actual Behaviour

App gets stucked and won't respond until we restart it.we need to reopen the application after opening any other app.

#### Steps to repoduce the behaviour

1. Open App
2. Switch from mobile data to wifi or wifi to mobile data
3. It'll get stuck and won't respond
Solution:
1.close app
2.open any other app
3.reopen popcorntime

**Comment by MrRory** [comment]
https://github.com/popcorn-official/popcorn-android/issues/486
