### ISSUE TITLE
can't search 

### ISSUE THREAD

**Issue by Stephan2620** [popcorn-official/popcorn-android#582]
Version:  0.2.9 - arm
Download date:  30/11 - 2019
Android version:  9.1.0

#### Expected Behaviour
 
search on the search button

#### Actual Behaviour

... Fail

#### Steps to repoduce the behaviour

1. ... Open the app
2. ... Press search button 
3. ...😅

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
