### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by lechugaxthz** [popcorn-official/popcorn-android#583]
Version:  0.2.9-arm
Download date:  -
Android version:  9

#### Expected Behaviour

...
I thought that when I passed the series or movie to TV I was going to spend it together with the subtitles.
#### Actual Behaviour

...
Play videos correctly but without subtitles 
#### Steps to repoduce the behaviour

1. ...Start playback with the titles indicated from the mobile 
2. ...Go to play on TV
3. ...See the title you chose without the subtitles

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
