### ISSUE TITLE
App not playing videos

### ISSUE THREAD

**Issue by facubarrera80** [popcorn-official/popcorn-android#585]
Version:  2.9
Download date:  n/a
Android version:  7.0

#### Expected Behaviour

It was supposed to reproduce the series y chose

#### Actual Behaviour

It froze in the loading image

#### Steps to repoduce the behaviour

1. Select a series
2. Reproduce it

It just doesn't load

**Comment by kuffum2011** [comment]
It's still freezing

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
