### ISSUE TITLE
Offline subtitle

### ISSUE THREAD

**Issue by neobie** [popcorn-official/popcorn-android#586]
Version:  3.6.4.190
Download date:  2019-12-18
Android version:  10.0

#### Expected Behaviour
Offline subtitle should be cached after play back
...

#### Actual Behaviour
No subtitle if the phone is offline.
...

#### Steps to repoduce the behaviour

1. Playback video online with subtitle
2. turn phone offline, quite app. 
3. Play video, no more subtitle.

**Comment by MrRory** [comment]
You need internet to use this app, duh.
