### ISSUE TITLE
Search Bar Misbehaving

### ISSUE THREAD

**Issue by ElmerIV** [popcorn-official/popcorn-android#587]
Version:  0.2.9
Download date:  12/17/19
Android version:  9

#### Expected Behaviour

...I used the search bar ad expected to find a movie that I had once looked up and found.

#### Actual Behaviour

...Though perviously operating as expected, now whenever I use the search bar or any filters, I get "No Results Found' and "Something went wrong" on my screen

#### Steps to repoduce the behaviour

1. ...Open App
2. ...Search for movie or tv show
3. ...This should give you the same result

**Comment by stenoz** [comment]
Same here

**Comment by SscSPs** [comment]
This i believe happens where there is some network issue, can you veryfy the internet is working fine and try again given the internet is connected?

**Comment by ElmerIV** [comment]
I have done so and received the same result. The streaming itself is
preforming fine and as I assume it was intended to, but the search bar
doesn't really work. It's just a little inconvenient to have to find ever
show and movie in the A-Z section is all.

**Comment by MrRory** [comment]
The results are received from the API, not inside the app.
