### ISSUE TITLE
Using Popcorn Time Android With A Remote

### ISSUE THREAD

**Issue by jardinc001** [popcorn-official/popcorn-android#591]
Version:  2.9
Download date:  December 29, 2019
Android version:  5.1.1

There is an issue in using Popcorn Time Android with a remote. I have Android installed on my TV box which I use a remote to control (it's is not Android TV though, just normal Android). When I downloaded Popcorn Time Android I noticed some issues involving using the app with my remote which is the only way I can use it:

1: When I go to genres, the genre that I am on before I press OK and select that genre doesn't get highlighted as I am scrolling through them (kind of like how the genres and trending options get highlighted when I have clicked left or right) so I kind have just have to guess before choosing what genre I'm on. The genre does get highlighted when I click on it though.

2: The movies that I am on when I am scrolling through the movies with my TV remote are darkened very briefly that it is almost unnoticeable. I have to squint my eyes to see what movie I'm on. Not a big issue though but I hope this could be changed somehow.

3: Probably the biggest issue, is that when I would press OK on my remote on the other popcorn time version (popcorntime.is) the menu with the pause, fast forward, and rewind section would come up. However, on this version of Popcorn Time it doesn't come up so I have no way of pausing or rewinding. The only way I could bring this menu up is by pressing the RETURN button which acts as a "back" button which then prompts the app to ask me if I would like to leave the movie. I say no and then I can play around with the pause and fast forward options for about a second before it completely leaves even when I am still moving the arrows around.

Thank you for reading this and I hope using a remote for this app will be better integrated soon. Have a good day.

Regards,
Christopher Jardine

**Comment by MrRory** [comment]
This app was built for touchscreens, there is no support for remotes.
