### ISSUE TITLE
can't play TV shows

### ISSUE THREAD

**Issue by sailseed** [popcorn-official/popcorn-android#594]
Version:  0.2.9 arm
Download date:  7 January 2020
Android version:  7.0

#### Expected Behaviour

...Play any TV Series episode

#### Actual Behaviour

...Preview image opens full screen, no buttons, phone slows down. Restarting app results in crash dialogue

#### Steps to repoduce the behaviour

1. ... Open app
2. ...Select shows
3. ...Tap any show
4. Select any episode
5. Tap play button

**Comment by hulkyboi** [comment]
I'm also facing this issue

**Comment by MrRory** [comment]
Please provide more information.
