### ISSUE TITLE
Anime 

### ISSUE THREAD

**Issue by andrew32792** [popcorn-official/popcorn-android#596]
Version:  0.2.9
Download date:  n/a
Android version:  10

#### Expected Behaviour

... 

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ... open app
2. ...attempt to watch anime
3. ... attempt to connect to a chromecast.

**Comment by MrRory** [comment]
https://github.com/popcorn-official/popcorn-android/issues/487
