### ISSUE TITLE
Magnet links cannot be copied

### ISSUE THREAD

**Issue by jdarias** [popcorn-official/popcorn-android#597]
Version:  0.2.9 arm64
Download date:  
Android version:  

#### Expected Behaviour
Would like to copy the magnet link of a download so i can put it in a web app
...

#### Actual Behaviour
There's no option to copy the link
...

#### Steps to repoduce the behaviour
1. Pick a content you're interested in
2. Try to find a way to copy the magnet link

**Comment by MrRory** [comment]
There should be a magnet button on each content detail
