### ISSUE TITLE
[ATV] Can't go forward or backwards

### ISSUE THREAD

**Issue by ghiamar** [popcorn-official/popcorn-android#6]
Hi I have a Nvidia Shield TV and installed tv-arm64-v8a-release-0.1.2.apk build #40. I can play movies very well but I can't go forward or backward. If I try to go forward, it keeps waiting and does nothing, I can only go forward all the way of the current loaded movie, but if the movie didn't fully load, then It does nothing.

I spect to work as the desktop version, where I can go forward even if that part of the movie didn't load, so it starts streaming from that point.

If youn need some log or something, just point me to it.

**Comment by pct-team** [comment]
You cannot do this.
