### ISSUE TITLE
popcorn time won't steam shows reliably

### ISSUE THREAD

**Issue by gfliger51** [popcorn-official/popcorn-android#600]
Version:  
Download date:  2/7/2020
Android version:  6.0.1

#### Expected Behaviour

Run torrent, butter then stream.

#### Actual Behaviour

Just sits there for a minute or so then goes back to the shows menu.

#### Steps to repoduce the behaviour

1. ... Start the app
2. ... Pick a show
3. ... Hit play

**Comment by sohojmanush** [comment]
same for me on android tv.

**Comment by MrRory** [comment]
Please provide more info.
