### ISSUE TITLE
Downloads drop to 0 if external storage cache/freezes device

### ISSUE THREAD

**Issue by Charmandrigo** [popcorn-official/popcorn-android#601]
Version:  3.6.4
Download date:  January 2020
Android version:  Fire OS 6.2.6.8

#### Expected Behaviour

Download movies to my external storage set as cache

#### Actual Behaviour

Downloads drop to 0b/s even with a lot of seeds, then app starts to freeze the whole device, app crashes, then it's impossible to open it again or open any app that can read the external USB storage unless the device is reset

#### Steps to repoduce the behaviour

1. Fire TV stick 4k with a usb hub reader plugged, formats new usb as fat32
2. Set popcorn time cache folder to external storage detected 
3. Download a movie and expect the download to drop to 0b/s and start to freeze the whole device in about 30 seconds of playing a movie

**Comment by MrRory** [comment]
3.6.4 is not a version that we ever released
