### ISSUE TITLE
Os filmes não abrem

### ISSUE THREAD

**Issue by Edna594** [popcorn-official/popcorn-android#602]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. .
2. ...
3. ...não consigo assistir nenhum filme , eles trava e não abrem mais

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.

**Comment by Carloscostta7** [comment]
Nem eu consigo assistir porra de filme nenhum
