### ISSUE TITLE
Several issues AndroidTV MiBox4

### ISSUE THREAD

**Issue by Michiel-celis-code** [popcorn-official/popcorn-android#603]
Version:  0.1.4 - armeabi-v7a
Download date:  18/02/2020
Android version:  9
Device: MIBOX 4 (xiami mibox s)

#### Behavior
Playback interrupts / download of 1080p movies often doesn't start
#### Likely Cause
Not enough room on device's primary storage (4GB left)
#### Solution
Adding an option to store downloaded content 
on external storage

#### Behavior
Shows only 3 movies in homeview channel.
Loads slow, which results in the channel being placed at the bottom of the homescreen.
#### likely cause
Lack of programming done for AndroidTV version
#### Solution
Add multiple channels to choose from, and load +20 items, fix slow response problem

#### behavior
Audio jitter after exiting movie with multiple presses on 'back' instead of long press.
Jitter doesnt stop when opening other app with playback
#### likely cause
Not stopping playback completely after exiting app

## Suggestions 
* set app color charcoal grey
* higher resolution for background images

Hope this is usefull

**Comment by MrRory** [comment]
Please split this in multiple issues
