### ISSUE TITLE
Issue for popcorntime

### ISSUE THREAD

**Issue by NezukoChan0w0** [popcorn-official/popcorn-android#604]
Version:  2.9
Download date:  
Android version:  9.0

#### Expected Behaviour
 Normally play movies no lag then just close app normally
...

#### Actual Behaviour
Plays movies but lags, screen freezes sound only starts in one ear phone and when I exit the app it says popcorn running in background and I can't stop it. 
...

#### Steps to repoduce the behaviour

1. ...
2. ...
3. ...

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
