### ISSUE TITLE
Unable to cast to Chromecast

### ISSUE THREAD

**Issue by zaneperry** [popcorn-official/popcorn-android#607]
Version:  0.2.9 ARM
Download date: 3/18/20  
Android version:  10

#### Expected Behaviour

Unable to find Chromecast on cast to screen

#### Actual Behaviour

I see TV models (Like my Roku TV) but no Chromecasts

#### Steps to repoduce the behaviour

1. Open App
2. Click cast to screen
3. No Chromecast present

I am connected to WiFi and can cast from any other app.

**Comment by demetriusqs** [comment]
The same problem happens to me

**Comment by MrRory** [comment]
Duplicate of #247
