### ISSUE TITLE
There is a problem with storage location (again)

### ISSUE THREAD

**Issue by memelordhokage** [popcorn-official/popcorn-android#608]
Version:  0.2.9
Download date:  19/3/2020
Android version:  10

#### Expected Behaviour

I expected the app to give me the option to save between SD Card and Internal Storgae

#### Actual Behaviour

The app gives option of automatic and choose. On selecting choose, only internal storage options are available. No way of going to SD Card. 

#### Steps to repoduce the behaviour

1. Open the app and click 3 bars on top left
2. Select preferences and scroll down to Storage Locations
3. Click on it and select Choose Location

**Comment by MrRory** [comment]
This means your phone blocks more access.
