### ISSUE TITLE
Application crashes when trying to play anime episode

### ISSUE THREAD

**Issue by pavan167869** [popcorn-official/popcorn-android#610]
Version:  0.2.9 - arm
Download date:  19-03-2020
Android version:  10

#### Expected Behaviour

The app show allow me to play the selected anime episode.

#### Actual Behaviour

As soon as I click on any episode of anime, the app crashes. This does not happen while playing "Shows" or "Movies".

#### Steps to repoduce the behaviour

1. Open the application.
2. Open the menu from three horizontal lines from top left side of the application.
3. Select Anime option.
4. Select any anime.
5. Click on Season 1
6. Click on any episode.
7. The application shall crash.

**Comment by paritosh9199** [comment]
Same here but it also happens when an episode or a movie is halfway

**Comment by MrRory** [comment]
Please provide adb logs and re-open.
