### ISSUE TITLE
Images of the movies are not coming on the menu

### ISSUE THREAD

**Issue by anshmahana** [popcorn-official/popcorn-android#611]
Version:  0.2.9 arm
Download date: 20 March 2020 
Android version:  7.0

#### Expected Behaviour
 it was going to show me the images of the movie in the menu but it didn't
...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. ... Open the app 
2. ...on the menu the images of the film's were not coming 
3. ...the images of the film's were not coming.

**Comment by RealBlackB1RD** [comment]
Experiencing this issue too.
I'm using Samsung Galaxy S10 Plus, Android 10, One UI v2, Popcorn Time v0.2.9-arm.
Already cleaned the data of the application and force stop it to launch it clean, and still the same. Even when I'm accessing the movie the thumbnail isn't loading...

**Comment by Afnisse** [comment]
Yeah I have the same problem

**Comment by MrRory** [comment]
This sounds like a temporary API problem
