### ISSUE TITLE
Freezes after streaming starts.

### ISSUE THREAD

**Issue by shorif2000** [popcorn-official/popcorn-android#616]
Version:  2.9

#### Actual Behaviour
App freezes once streaming starts. Have to restart phone if i want to open app again

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.

**Comment by shorif2000** [comment]
Using samsung galaxy s10 plus. 

When the app is opened and i click on watch it now. Once it start playing none of the touch controls work on the screen. Like pause video
