### ISSUE TITLE
Crashed Popcorn App on my Note 10 Plus

### ISSUE THREAD

**Issue by ashiqash** [popcorn-official/popcorn-android#617]
Version:  0.2.9
Download date:  30 March 2020
Android version:  10

#### Expected Behaviour

Open the movie or episode normally without any problems as i am using a Note 10 plus

#### Actual Behaviour

...buffered for nearly 10 minutes and broke and the app crashed every single time i open a movie or episode

#### Steps to repoduce the behaviour

1. Open any movie
2. ...
3. ...

**Comment by MrRory** [comment]
Update to 0.2.10
