### ISSUE TITLE
App not working properly

### ISSUE THREAD

**Issue by vatsalshah007** [popcorn-official/popcorn-android#618]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...It should simply keep loading the video and keep playing it

#### Actual Behaviour

...It keeps on crashing again and again. It doesn't play continuously, it suddenly freezes inbetween and I have to minimise the app and let the video load and then it starts to play again.

#### Steps to repoduce the behaviour

1. ...I found it repeating in the 6 underground movie so you should try that
2. ...
3. ...

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
