### ISSUE TITLE
Problemas

### ISSUE THREAD

**Issue by SwaeMin** [popcorn-official/popcorn-android#621]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to repoduce the behaviour

1. Quando escolho um filme/série ele encrava logo nos primeiros minutos, e aparece logo uma caixa de texto a dizer "PopCorn Time parou", e pede para fechar a aplicação, tentei mudar o aplicativo de vídeo e continuou com o mesmo problema 
2. ...
3. ...

**Comment by MrRory** [comment]
No hablo espanol.
