### ISSUE TITLE
can not play episodes on shows. android 9 and android tv

### ISSUE THREAD

**Issue by guidosanchez** [popcorn-official/popcorn-android#624]
Version: 0.2.9
 Download date:  
Android version:  9 and android tv

#### Expected Behaviour

Show series info or play. When I choose a chapter.

#### Actual Behaviour

...
Crashes on phone. On android tv no option can be chosen once I select the chapter. I can only go back
#### Steps to repoduce the behaviour

1. Choose a chapter on any show
2. Only on shows. Not on movies

**Comment by MrRory** [comment]
Duplicate.
