### ISSUE TITLE
I want to report a bug

### ISSUE THREAD

**Issue by galiaham** [popcorn-official/popcorn-android#627]
Version:  the movie got stuck in the middle and not continuing after that.
Download date:  04/05/2020
Android version:  9 PKQ1.180904.001

#### Expected Behaviour

...  All the movies will work

#### Actual Behaviour

... Not all the movies are working

#### Steps to repoduce the behaviour
 

1. ... The movie is : X-Men : the last stand
2. ... The problem is in the application : Popcorn Time.
3. ... Check the problem and fix it.

**Comment by MrRory** [comment]
Please provide more information.
