### ISSUE TITLE
Subtitles still broken

### ISSUE THREAD

**Issue by aanev22** [popcorn-official/popcorn-android#629]
Version:  0.2.10
Download date:  06.04.2020
Android version:  9.0

#### Expected Behaviour
When you click on any movie and go on subtitles you see No Subtitles and click to select from plenty of subtitles.

#### Actual Behaviour
Since 04.04.2020 it is stuck on Loading Subtitles and it never loads, probably something is changed with the provider of subtitles.
#### Steps to repoduce the behaviour
1. Click on any movie
2. Loading Subtitles click
3. Not single subtitle shows

**Comment by MrRory** [comment]
I think this was fixed.
