### ISSUE TITLE
The app isn't showing the subtitles!

### ISSUE THREAD

**Issue by LimonGats** [popcorn-official/popcorn-android#631]
Version:  latest one
Download date:  04/09/2020
Android version:  9

#### Expected Behaviour

Show the subtitles options

#### Actual Behaviour

The app is not showing any subtitles

#### Steps to repoduce the behaviour

1. Choose a movie
2. Select subtitles
3. There are no subtitles

**Comment by MrRory** [comment]
I think this was fixed.
