### ISSUE TITLE
Popcorn time subtitles

### ISSUE THREAD

**Issue by kossttask** [popcorn-official/popcorn-android#634]
Version:  0.2.9-arm
Download date:  04/04/2020
Android version:  Oxygen 10.0.4.GM57BA

#### Expected Behaviour
Subtitles
Custom ...
Show files to select one

#### Actual Behaviour
Subtitles
Custom ...
Shows files to select only the first time I run the app and never again during the day or more

#### Steps to repoduce the behaviour

1. Play a movie
2. Subtitles --> Language
3. Custom ...
more than once

**Comment by MrRory** [comment]
I think this was fixed.
