### ISSUE TITLE
I want to report a bug in a movie

### ISSUE THREAD

**Issue by galiaham** [popcorn-official/popcorn-android#635]
Version:  got stuck in the middle of the movie and not continuing after that
Download date:  04/12/2020
Android version:  9 PKQ1. 180904.001

#### Expected Behaviour 

... The movie won't get stuck

#### Actual Behaviour

... The movie stuck and I didn't accept it

#### Steps to repoduce the behaviour

1. ... The movie is "Venom"
2. ... Check the problem
3. ... Fix it.

**Comment by MrRory** [comment]
I think this was fixed.
