### ISSUE TITLE
Movie got stuck again!

### ISSUE THREAD

**Issue by galiaham** [popcorn-official/popcorn-android#638]
Version:  movie got stuck in the middle and not continuing after that.
Download date:  04/13
Android version:  9 PKQ1. 180904.001

#### Expected Behaviour

... I thought that this app won't let the movie get stuck!

#### Actual Behaviour

... Almost all the movie get stuck and not continuing after that!

#### Steps to repoduce the behaviour

1. ... The movie is suicide squad 
2. ... Check the problem
3. ... Fix it!!

**Comment by MrRory** [comment]
Please provide more information.
