### ISSUE TITLE
FIX IT.....!!! ASAP!

### ISSUE THREAD

**Issue by tyo420** [popcorn-official/popcorn-android#640]
Version:  0.21.10 - arm
Download date:  April 15 2020
Android version:  Nougat (7.1.1)

#### Expected Behaviour

...  provides a variety of movies and shows with smooth connections and various subtitles with a simple mechanism

#### Actual Behaviour

... Many movies and shows but lacks of connections and subtitle and complicated mechanism
#### Steps to repoduce the behaviour

1. cant click the categories/genres button
2. Navigation button on popcorn time player didnt work
3. no 480p option on many movies and shows

**Comment by MrRory** [comment]
Please split this in multiple reports detailing your _exact_ problems.
