### ISSUE TITLE
Something went wrong.

### ISSUE THREAD

**Issue by galiaham** [popcorn-official/popcorn-android#642]
Version:  the app is not working properly.
Download date:  I didn't download anything
Android version:  9 PKQ1. 180904.001

#### Expected Behaviour

... To work.

#### Actual Behaviour

... The app is not working.

#### Steps to repoduce the behaviour

1. ...  Check this
2. ... Fix it
3. ...

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
