### ISSUE TITLE
Subtitle not Casting

### ISSUE THREAD

**Issue by aanev22** [popcorn-official/popcorn-android#644]
Version:  0.2.10 -176 on jenkins
Download date:  15.04.2020
Android version:  9

#### Expected Behaviour
Choose movie WITH subtitle and Cast and on TV everything OK ( version 0.2.09 -170 on jenkins was working perfect)

#### Actual Behaviour
Choose movie WITH subtitle and Cast and on TV there is NO subtitle, only in the player.

#### Steps to repoduce the behaviour
1. Choose movie
2. Loading subtitle(this is working)
3. Cast to DLNA - Video on TV is without subtitle

**Comment by MrRory** [comment]
Duplicate of #247
