### ISSUE TITLE
0.2.9-armeabi-v7a just stopped working

### ISSUE THREAD

**Issue by chaesaerts** [popcorn-official/popcorn-android#647]
Version:  0.2.9-armeabi-v7a
Download date:  08-04-2017
Android version:  4.1.1

#### Expected Behaviour

...

#### Actual Behaviour

...after startup I get the following message: no data found
something went wrong

nothing isvisible on thescreen. thisstarted a couple of days ago

#### Steps to repoduce the behaviour

1. ...start the app
2. ...
3. ...

**Comment by MrRory** [comment]
Update to 0.2.10
