### ISSUE TITLE
It doesnt show movies

### ISSUE THREAD

**Issue by denisabramic** [popcorn-official/popcorn-android#649]
Version:  
Download date:  
Android version:  

#### Expected Behaviour
show movies
...

#### Actual Behaviour

...it shows that there are no data found

#### Steps to repoduce the behaviour

I opened the app and saw that there are no data found. Please fix this bug!!
1. ...
2. ...
3. ...

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
