### ISSUE TITLE
Crashes a lot. 

### ISSUE THREAD

**Issue by LaOruga** [popcorn-official/popcorn-android#656]
Version:  0.2.9 Arm
Download date: Abr/18/2020
Android version:  10

#### Expected Behaviour

...at the beginning was working well

#### Actual Behaviour

...instead  ow crashes a lot

#### Steps to repoduce the behaviour

1. ...open app
2. ...begin watching movie or TV show
3. ...crashes

**Comment by adityachotalia** [comment]
Same problem cant even start the app

**Comment by MrRory** [comment]
Please provide more information in your reports.

**Comment by LaOruga** [comment]
The program. Don't give me a log that I can share..

Regards,
Alejandro Rodriguez
________________________________
