### ISSUE TITLE
Popcorn Time 2.10 crashes immediately

### ISSUE THREAD

**Issue by 4rthis** [popcorn-official/popcorn-android#659]
Version:  2.10
Download date:  04.2020
Android version:  9 (Pie)

#### Expected Behaviour

...

#### Actual Behaviour

- Crashes immediately when a network is connected (Wifi or 4G).
- Can run with airplane mode but crahes a few seconds after turning on a network, when posters begin to appear.
- Arm doesn't mater
- Tried to empty cache / data, uninstall and reinstall, same thing happens.

#### Steps to repoduce the behaviour

1. Turn on wifi or 4G on Pie
2. Launch Popcorn 2.10
3.

**Comment by team-pct** [comment]
Try https://ci.popcorntime.sh/job/Popcorn-Time-Android/180/

**Comment by Kirioz** [comment]
Same problem here.
Android 8 and a samsung s7.
The revision 180 fix it. Thanks

**Comment by adityachotalia** [comment]
Can you help me how to fix it ...cant install revision180

**Comment by MrRory** [comment]
This was fixed in a later release.
