### ISSUE TITLE
Search problems

### ISSUE THREAD

**Issue by harshm86** [popcorn-official/popcorn-android#664]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...when I search for Indian films it doesn't shows

#### Actual Behaviour

...but when I check in years category it shows all the indian films

#### Steps to repoduce the behaviour

1. ... create a section for Indian flims
2. ... Or fix the Search bug
3. ...

**Comment by MrRory** [comment]
Please provide more information in your reports.
