### ISSUE TITLE
App not showing Anime

### ISSUE THREAD

**Issue by 1ghostfighter15** [popcorn-official/popcorn-android#665]
Version:  0.2.10 - arm
Download date: 28 April 2020
Android version: Android(Nougat)
#### Expected Behaviour

... I thought I can watch anime

#### Actual Behaviour

... The app is not showing any anime.

#### Steps to repoduce the behaviour

1. ... Please bring anime
2. ...
3. ...

**Comment by MrRory** [comment]
The app does not determine content
