### ISSUE TITLE
Don't work, The screen is black

### ISSUE THREAD

**Issue by Gustavocrts** [popcorn-official/popcorn-android#669]
Version:  0.2.9 arm64 v8a
Download date:  15 may 2020
Android version:  10

#### Expected Behaviour
 work
...

#### Actual Behaviour
 do noting, black screen
...

#### Steps to repoduce the behaviour

1. ..Open the app.
2. ...don't charge anything, all the screens are black
3. ...
![Screenshot_20200515-214708](https://user-images.githubusercontent.com/65433200/82108695-e3218480-96f5-11ea-8bfd-aabb9d2f5176.png)

**Comment by MrRory** [comment]
Please provide more information in your reports.
