### ISSUE TITLE
Android TV microphone permission is required

### ISSUE THREAD

**Issue by Spartacusboy** [popcorn-official/popcorn-android#678]
Version:  0.4.4
Download date:  6.6.2020
Android version:  nougat (7.0.0)

#### Expected Behaviour
 Not to ask for microphone permission or at least open without it
...

#### Actual Behaviour
 Ask for microphone permission and didn’t open without it
...

#### Steps to repoduce the behaviour

1. ... install the arm v7a apk for Android TV
2. ... open it
3. ... that’s it

**Comment by MrRory** [comment]
0.4.4? That's not a version we ever released

**Comment by superbonaci** [comment]
Same request as https://github.com/popcorn-official/popcorn-android/issues/804
