### ISSUE TITLE
Popcorn time issue

### ISSUE THREAD

**Issue by wazz27** [popcorn-official/popcorn-android#679]
Version:0.2.10 - arm
Download date:  8-6-2020
Android version:  s10 

#### Expected Behaviour
 
When I go the search option and search for any movie , the search doesn't find anything and the message something is wrong comes up.

I have tried to delete it and install it and rebooted my phone and then tried it again but the same thing happens.  

Thank you for your help

#### Steps to repoduce the behaviour

1. ...go to search on popcorn time
2. ...try looking for any movie 
3. ...you will not find anything no matter what you search

**Comment by dabs40** [comment]
Hi all.
I have nvidia shield and not able to install popcorn time on it as it says this version is not compatible with this device yet ( for ANY version...tried them all).

nvidia shield pro 16gb,version 9. android security patch level 05/12/2019, build ppr1.180610.011.4199437_1915.8582, shield android tv sw version 8.1.1( 32.7.301.99).
To be honest, I managed to install it once or twice and every time it comes up with an error message ( something went wrong) and I only get the categories and the settings but no films/tv series are loading.
Any thoughts?
Any help would be appreciated.thanks.
p.s: not using vpn.
app works on my pc,on my phone and even on my other android box (t95 max).

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
