### ISSUE TITLE
Building Not Producing APK on Debug

### ISSUE THREAD

**Issue by team-pct** [popcorn-official/popcorn-android#68]
Since last commit https://github.com/popcorn-official/popcorn-android/commit/632aa2d79c86419fb13d9ffe8342688a305831d0

CI is failing to find any apK after the build finish 

@vzamanillo

**Comment by vzamanillo** [comment]
I think the problem is not related with the apk building itself, is related to the build destination path after the gradle dependency change. I am doing some tests.

**Comment by team-pct** [comment]
@vzamanillo 
```

find . | grep ".apk" | xargs rm -rf
if [ "$RELEASE_TYPE" = "release" ]; then
	./gradlew assembleRelease
else
	./gradlew assembleDebug
fi
find . | grep "unaligned.apk" | xargs rm
if [ "$RELEASE_TYPE" = "release" ]; then
scp mobile/build/outputs/apk/* jenkins@get.popcorntime.sh:/srv/repo/android/0.2.9/
scp tv/build/outputs/apk/* jenkins@get.popcorntime.sh:/srv/repo/build/0.1.4/
fi
```

**Comment by vzamanillo** [comment]
Sorry, but I need to check the post-build step configuration on jenkins.

**Comment by vzamanillo** [comment]
Ok, with gradle => 2.2 the apks are generated aligned thats because there are one and only apk in the output folder. I have to do some changes in the main build file related to the output files renaming. 

In the other hand, we do not need additional steps to find and remove apk files in pre or post build steps, it is easy as run gradle with clean parameter,  so we must change some jenkins configuration too.

**Comment by team-pct** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Android/116

**Comment by vzamanillo** [comment]
We can simplify the jenkins build removing the unneccesary steps for finding and removing the previous apks, it is more crear the use of 'gradle clean assembleX'

**Comment by team-pct** [comment]
Something like that? 

```
if [ "$RELEASE_TYPE" = "release" ]; then
	./gradlew clean assembleRelease
	./gradlew assembleRelease
else
	./gradlew clean assembleDebug
	./gradlew assembleDebug
fi

```

**Comment by vzamanillo** [comment]
First gradle line only for both conditions. It works like maven clean, in the same execution clean the output folder before start building.
