### ISSUE TITLE
Don't Working in Android Kit Kat 4.4

### ISSUE THREAD

**Issue by jordirar** [popcorn-official/popcorn-android#680]
Version:  
Download date:  13/06/2020
Android version:  4.4.4

#### Expected Behaviour

...installs correctly but doesn't work

#### Actual Behaviour

...Black Screen

#### Steps to repoduce the behaviour

1. ...Install
2. ...Start
3. ...shows black screen, no movies. in some cases it stops working

**Comment by MrRory** [comment]
You should really consider getting a newer version of Android.
