### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by K1NGM4RV** [popcorn-official/popcorn-android#681]
Version: 0.2.10 (latest)
Download date: ~09.06.2020
Android version: Android 10 (Mi9 - MIUI stock room)

#### Expected Behaviour
Scrolling through the movie tabs should load up movies 
...

#### Actual Behaviour
The movie posters don't appear -> app crashes few seconds afterwards
...

#### Steps to repoduce the behaviour
1. Open Popcorn time
2. Stay on the movie section (only happens there!)
3. Swipe quickly with your finger to the left (meaning you go to the right on the tabs)
4. Wait for the crash to happen around the section "top rated"

**Comment by MrRory** [comment]
This sounds like an api problem.
