### ISSUE TITLE
The app is buggy

### ISSUE THREAD

**Issue by Yamathe** [popcorn-official/popcorn-android#683]
Version:  0.2.10-arm
Download date:  25/60/2020
Android version:  9

#### Expected Behaviour
Play the movie with Spanish subtitles
...

#### Actual Behaviour

>The subtitles stop appearing, the film continues playing and the video interface hangs
... 
#### Steps to repoduce the behaviour

1. ...I enter the app 
2. ...I wait for the subtitles in Spanish 
3. ...And like every 30-40 minutes of the movie it happens

**Comment by MrRory** [comment]
Please provide more information. It is unclear what your are experiencing.
