### ISSUE TITLE
Respond issues

### ISSUE THREAD

**Issue by aditijain1330** [popcorn-official/popcorn-android#684]
Version:  
Download date:  
Android version:  

#### Expected Behaviour

...This app is showing problem again and again.
They say that this app is not responding.

#### Actual Behaviour
It hangs
...

#### Steps to repoduce the behaviour

1. ...open any show in the shows genre
2. ...Your phone will hang a second and then they say that this app is not responding 
3. ...

**Comment by MrRory** [comment]
Please provide more information in your reports.
