### ISSUE TITLE
Android TV APK - Endless Update Loop on Startup

### ISSUE THREAD

**Issue by derasmus** [popcorn-official/popcorn-android#688]
Version:  0.1.4
Download date:  2020-07-08
Android version:  8.0.0

#### Expected Behaviour

Expected the app to start & load the home screen

#### Actual Behaviour

The app prompts for an update, with a 'Yes' or 'No, maybe later' option but regardless of the selection - the app loops back to the update prompt.

#### Steps to repoduce the behaviour

1. Start the app on Android 8.0.0 - see below
![IMG_8010](https://user-images.githubusercontent.com/6725283/87008186-a937a080-c1c3-11ea-9bad-807a3a257e9c.jpg)

**Comment by jagdishadusumalli** [comment]
Facing the same issue on 
Mi TV 4X 50 running Android TvOS 9.0 and also on
Nvidia Shield TV running Android TvOS 9.0

**Comment by longnd** [comment]
have you guys tried the latest buids on CI yet?
https://ci.popcorntime.app/job/Popcorn-Time-Android/

**Comment by jagdishadusumalli** [comment]
hey @longnd just did that and it does not go into the update loop so far.
Thanks for the suggestion

**Comment by derasmus** [comment]
hi @longnd - installed last night, no update loop. thanks
