### ISSUE TITLE
Popcorntime + Andriod phone + Chromecast

### ISSUE THREAD

**Issue by ghost** [popcorn-official/popcorn-android#70]
Version:   mobile-arm64-v8a-development-111.apk
Download date:  06-/11/2016  - dd/mm/yyyy
Android version:  - arm64-v8a arch

#### Expected Behaviour

... Open app, find movie, click "cast button" detect Chromecast (CC), Pair/beam/cast and Dance 

#### Actual Behaviour

... Does not detect CC.

#### Steps to repoduce the behaviour

1. ... Open app
2. ...Click Cast button

__________________Important side information_________________

**Desktop PC:** correctly detects CC with popcorntime(PC) and im able to stream directly flawlessly.

**Phone App:** Youtube, Google Home, Twitch, All able to detect and Pair/beam/cast to CC.
Andriod Smart View APP, does **NOT** detect CC.
**VPN** NONE
**Chromecast:** 2nd Generation

_______________Side info ________________
I am able to successfully detect+stream to friends Philips smart TV within the popcorntime app (phone)
I am also able to detect several wireless speakers within my home on the popcorntime app (phone)

**This is OP on reddit**
https://www.reddit.com/r/PopCornTime/comments/5bgvkk/andriod_popcorntime_chromecast/

Thanks, for an amazing program!

**Comment by GhostVeggies** [comment]
Me: Use time creating Github account, Use time looking for similar problem before posting, Open Post + make it as detailed as I can because that usually makes the difference.
@ChrisAlderson Close post without even responding.

Ps. Dont bother responding now, im deleting my account here

**Comment by ChrisAlderson** [comment]
ok

**Comment by noeltorious** [comment]
Why was this closed?

**Comment by servoper** [comment]
Lol.. Same here.... I mean even if I force close the app it's the same. Sometimes or works if I reboot the phone... And if I am in the app and stop and then start the app it goes in ANR... It happens both on Nexus 4 Android 6 and Nexus 6P Android 7.1.1 ... If you need help with the developer just let me know

**Comment by team-pct** [comment]
@servoper you are welcome to contribute to fix this issue

**Comment by team-pct** [comment]
@ghost probably chris was not able to reproduce your bug
