### ISSUE TITLE
Casting to tv

### ISSUE THREAD

**Issue by leeb23-aus** [popcorn-official/popcorn-android#706]
Can't cast to tv, only devise that appears when I press cast icon in popcorn time app is my sons xbox, I have recently updated your app and it use to work just fine, now not so much sorry.

**Comment by EdgardHernandezp** [comment]
@leeb23-aus I thought this app didn't have the feature to cast. I tried using an app (LocalCast) but doesn´t work properly. How you used to do to cast from PopCornTime app?

**Comment by leeb23-aus** [comment]
I have always used All Cast app to cast to my chromecast devise plugged
into tv. But know I have an android tv with built in chromecast and dont
need any apps for this.

**Comment by Persei08** [comment]
Guys please provides technical details, don't wait for someone to ask you.

I will assume you use PCT v4.4, so i suggest you to upgrade to [latest dev build](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/) (actually 438) and retry.

![Screenshot_2020-10-06_08-08-43](https://user-images.githubusercontent.com/22459458/95165374-24e9bf00-07ac-11eb-8dc6-f9c6d1243e7d.png)

**Comment by EdgardHernandezp** [comment]
@leeb23-aus but looks like you're using the android mobile version. In the homepage I saw there is a separate version for android tv.

**Comment by leeb23-aus** [comment]
Yes maybe so..
