### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by Serj1027** [popcorn-official/popcorn-android#71]
Version:  0.2.9
Download date:  10.11.2016
Android version:  6.0.1

#### Expected Behaviour
 Change cache folder to sd card
...

#### Actual Behaviour
 Can't read the Sd card( can't go back to select sd card or internal memory )
...

#### Steps to repoduce the behaviour

1. Go to settings-> change cache folder
2. Look for sd card
3. Can't find it.

**Comment by vzamanillo** [comment]
Confirmed, is related to M permissions and the directory chooser library.

**Comment by JeremiUlanowski** [comment]
Can you please fix it? The competition apps have no problem with this and it's seriously not allowing me to use your app.

**Comment by IamLosted** [comment]
Quite a bummer.. Since I have a phone with quite small internal space I simply cannot use the app.

**Comment by vzamanillo** [comment]
Could you please test with the latest build from ci?

**Comment by IamLosted** [comment]
Works for me now. Thank you!

**Comment by vzamanillo** [comment]
I will leave the issue opened while the rest of the people with the same problem test the new build.

**Comment by TizianoVecellio** [comment]
Works for me too! Great work!

**Comment by Serj1027** [comment]
I have need to update my app or what..? :(

**Comment by vzamanillo** [comment]
@Serj1027, you can download the latest build from https://ci.popcorntime.sh/job/Popcorn-Time-Android/

**Comment by Serj1027** [comment]
I get: Location not writable

**Comment by TizianoVecellio** [comment]
I think you can onlyl pick the cache folder it creates in the Android folder on the sd card.

**Comment by vzamanillo** [comment]
@Serj1027, actually the directory chooser fragment shows the read only directories too, but the application can (should) not handle the filesystem permissions, so if your selected folder is not writable you should select another writable folder.

**Comment by TizianoVecellio** [comment]
Well, now the app is just crashing constantly and the video is glitched out, even in an external player..

**Comment by vzamanillo** [comment]
Do a report and fill an issue

**Comment by TizianoVecellio** [comment]
Ok, done ;).

**Comment by vzamanillo** [comment]
Thank you!

**Comment by VlijmenFileer** [comment]
Just to add.  Today I downloaded a development version from the location mentioned:
mobile-armeabi-v7a-development-136.apk
and it seems to solve the issue.

If I ever get my hands on one of the Anroid developers who made such a scandalous mess out of Android FS permissions though, I might commit an act of severe aggression.  Those changes, unnecessary for user experience or security, and solely meant to increase Google's stranglehold on what users can do with their data (hint: no more freedom exchanging data via your SD card, use something that starts with "Google") have been giving me headaches for ages already.

**Comment by yairEO** [comment]
Same :(

**Comment by raycekar** [comment]
@yairEO what version were you using of PT?

**Comment by m041** [comment]
Cannot change cache directory on popcorntime android TV version 0.3.6
