### ISSUE TITLE
ااااا

### ISSUE THREAD

**Issue by afjjyffff** [popcorn-official/popcorn-android#710]
لا يمكن مشاهده الفيلم او المسلسل عند الضغط على الفلم او المسلسل يتم ارجاعي للصفحه الرئيسيه أرجوا حل المشكله في اسرع وقت ممكن

**Comment by Persei08** [comment]
Google translate english translation:
>You cannot watch the movie or series. When you click on the movie or series, return to the home page. Please solve the problem as soon as possible.

Upgrade to the [latest dev build](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/) (438 as i'm writing) and try to see if it works better

**Comment by MrRory** [comment]
Please use the issue templates.
