### ISSUE TITLE
Anime Section Not Loading on 0.2.10 for Android

### ISSUE THREAD

**Issue by nyhtml** [popcorn-official/popcorn-android#737]
## Describe the bug
When trying to load the Anime Section, it fails.

## To Reproduce
1. Go to 'app'
2. Click on 'Anime'
3. See error 'Data No Found'

## Expected behavior
Expected to see a list on Anime as with the macOS version.

## Smartphone (please complete the following information):
 - Device: Pixel XL
 - OS: 10 with Oct 16, 2019 security update.
 - Browser: Chrome for Android
 - Version: 88.0.4324.141

## Additional context
Clearing cache and storage did not fix the issue. macOS version is working okay.

![Screenshot_20210213-194749.png](https://user-images.githubusercontent.com/2177262/107865444-64987580-6e34-11eb-85c1-a9f22c34e3bf.png)

**Comment by nyhtml** [comment]
I tweaked the file. All good now.

**Comment by SteavenGamerYT** [comment]
what did you do
