### ISSUE TITLE
Material Design Makeover of Popcorn Time.

### ISSUE THREAD

**Issue by vipulasri** [popcorn-official/popcorn-android#75]
#### Expected Behavior
Popcorn Time material design makeover, following all material design guidelines.

#### Actual Behaviour
Old Design, Popcorn Time Android App.

**Comment by vipulasri** [comment]
I would like to work on it.

**Comment by team-pct** [comment]
Go ahead and send us your work here

**Comment by MrRory** [comment]
what's not material in the current approach?

**Comment by vipulasri** [comment]
I was having the previous version of app. Current app is material but some portions can be improved
