### ISSUE TITLE
Error fetching data message even it's downloading the content.

### ISSUE THREAD

**Issue by sam0hack** [popcorn-official/popcorn-android#758]
## Describe the bug
When using the android tv app. I'm having issues with some downloads but before I jump to that I want to let you know that the UI is the worst I like the UI in the desktop app and also every time it redirects me to download the safe watch app which I do not need because I already have VPN in my router. Now comes to the download issue on some contents it shows me--> error fetching data. But when I play the content it works even I have downloaded a 2.55 GB movie which shows error but plays without any problem and because of this (error fetching data) message the UI on the download section messes up and auto-scroll up and downs and because UI it is hard goto the delete and watches now button. 

## To Reproduce
1. Go to any section and download the content do this 5 - 10 times
2. Go to the download section and some of them show this message ---> error fetching data
3. Try to watch now and it should play even download but the message does not go away.
4. Try to go to the delete button which is difficult because of UI.
5. Sometimes the app hangs because maybe because it's reloading the UI in the download section too fast.

## Expected behavior
To improve the TV app. The UI should be smooth and the error message should not be there if it's downloading the content and of course doesn't hang.  

## Screenshots
![alt text](https://i.ibb.co/HGV0D4V/tmp2.png)
![alt text](https://i.ibb.co/k8MVmHt/tmp1.png)

## Smartphone (please complete the following information):
 - Device: ANDROID TV
 - OS: ANDORID 
 - Browser: -
 - Version: ANDROID 9 

## Additional context
The UI also cuts near the edges I've tested on  Sony Bravia 55 inch if this helps to make the UI better.

**Comment by ivan1986** [comment]
It's other version
and also where you found working time4popcorn ?

**Comment by sam0hack** [comment]
> It's other version
> and also where you found working time4popcorn ?

other version ? i don't get it ?

**Comment by ivan1986** [comment]
yes, looks on screns it's other fork. you download it from getpopcorntime.is ?

**Comment by sam0hack** [comment]
yes, i might have. Where do I get the latest stable version?

**Comment by ivan1986** [comment]
now only http://popcorn-ru.tk/build/
we try to release and up new site, but it's has some administrative issues

**Comment by sam0hack** [comment]
okay, I'll try this one, Thanks a lot @ivan1986  :+1:
