### ISSUE TITLE
No Download option, Only Streaming

### ISSUE THREAD

**Issue by vipulasri** [popcorn-official/popcorn-android#77]
Version:  0.2.9
Download date:  17-11-2016
Android version:  7.0

#### Expected Behavior
There's no option for downloading the video, only streaming.

#### Actual Behaviour
Only streaming of videos is there.

**Comment by vzamanillo** [comment]
Popcorn time is not a BitTorrent client, is a medida streaming client, you can use another client to dowload the same content.

**Comment by vipulasri** [comment]
But in previous version of Popcorn Time, there was an option to download
the same.
Version: 0.2.7

**Comment by vzamanillo** [comment]
I suposse it was removed because it has no sense, why do you want to save a show episode or movie that is already watched?

**Comment by vipulasri** [comment]
Previously it was not playing while was downloading. You have to download it first and then play. I think that downloading feature was useful as you can watch the episode or movie, even when you are not connected to network.

**Comment by ChrisAlderson** [comment]
The option to download only shows up if you have an application installed which can download torrents. So look for a bit torrent client in the Play Store and there should be a little magnet icon to the right of the ratings.
