### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by birone69** [popcorn-official/popcorn-android#780]
I'm currently running version 3.6.9, and after the first launch, the app simply crashes every single time I open it. I tested on android 7 and 10 as well.

**Comment by aha999** [comment]
The app always crashed on all android devices that i've tried it on...  Sometimes it says it's not responding, but if i click "wait" it maybe starts responding again. Sometimes the app crashed on the start everytime, sometimes not...

I just tried it on my phone, the 

- version 0.2.13 - arm, 
- Asus Zenfone 6, 
- Android 11 - stock. 

half a minute while the app is opened it says that the app is not responding, and if i press Wait, it is working OK, like there wasn't a problem.
