### ISSUE TITLE
Cast icon does not appear

### ISSUE THREAD

**Issue by belumira** [popcorn-official/popcorn-android#79]
Version:  0.2.9 armeabi-v7a
Download date:  11/19/16
Android version:  7.1

#### Expected Behaviour

cast icon should appear when chromecast is available

#### Actual Behaviour

cast icon does not appear or appears randomly

#### Steps to repoduce the behaviour

Just open de app and check for cast icon.

**Comment by Breaking1** [comment]
Try what's suggested here #74

**Comment by ddulic** [comment]
Same issue, same fix as suggested by @Breaking1

**Comment by MrRory** [comment]
Closing as duplicate
