### ISSUE TITLE
Use Parceler for Media models

### ISSUE THREAD

**Issue by vzamanillo** [popcorn-official/popcorn-android#80]
https://github.com/johncarl81/parceler

Is not a big [performance difference](https://github.com/frankiesardo/icepick/issues/36) compared to Google Parcelable but is better an **easy!**

**Comment by MrRory** [comment]
looks cool, makes a lot of things easier indeed so no reason not to use it

**Comment by vzamanillo** [comment]
Yeah, looks very good.

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/use-parceler-for-media-models/119
