### ISSUE TITLE
Update VLC libraries

### ISSUE THREAD

**Issue by MrRory** [popcorn-official/popcorn-android#81]
The VLC libraries are really outdated, they should be updated somewhere in the future.

**Comment by vzamanillo** [comment]
I was thinking in removing the module code and include it as dependency but our code needs to be refactored due to hardware acceleration changes in the updated version.

**Comment by MrRory** [comment]
they don't have an sdk like they have for iOS :/

**Comment by vzamanillo** [comment]
Maybe we should move to another alternatives like [ExoPlayer](https://github.com/google/ExoPlayer)

**Comment by team-pct** [comment]
Hmmm What about codecs? what is the issue with VLC we have a good contact with their team maybe they can help us if we have a specific problem

**Comment by MrRory** [comment]
There is no problem, ExoPlayer is just easier to implement and maintain

But contact with VLC?

**Comment by cooliobr** [comment]
@team-pct  Exoplayer use ffmpeg as audio renderer, then no problem with audio or sub.

**Comment by aldoborrero** [comment]
Work already done in [#PR166](https://github.com/butterproject/butter-android/pull/166). Updated to 2.0.6 (the most stable one).

**Comment by team-pct** [comment]
This issue was moved to https://discuss.popcorntime.sh/t/update-vlc-libraries/118
