### ISSUE TITLE
The app doesn't work

### ISSUE THREAD

**Issue by Robertc125** [popcorn-official/popcorn-android#813]
![Screenshot_20220906-222359_Popcorn Time](https://user-images.githubusercontent.com/94452589/188727064-eb727456-ecfd-4dfa-befc-c315bdeb994c.jpg)
![Screenshot_20220906-222353_Popcorn Time](https://user-images.githubusercontent.com/94452589/188727068-305478c3-a21f-4a7b-9344-e1ec28fbacb2.jpg)

I downloaded the android app(latent version) and I get 10 movies (btw just loading,cant watch them) and no tv shows (No data found) and idk what to do,I tried with vpn too(nothing).
Pls hlp.thx

**Comment by kiriles90** [comment]
Which one is the latest version that you mean? Update to 0.3.6 if you haven't already then set the the Content Language option to English.
