### ISSUE TITLE
Re add ability to see seeder health

### ISSUE THREAD

**Issue by Maio-msdos** [popcorn-official/popcorn-android#814]
Thanks for updating the app a lot of issues have been fixed! Could you please bring back the old red, amber, green seed health so you know whether a film/series episode in a X resolution in likely to work :) before trying it

**Comment by kiriles90** [comment]
It was never removed, you downloaded something else.

**Comment by Maio-msdos** [comment]
@kiriles90 I downloaded the 0.3.6 release from this repo, I was slightly wrong though in my issue there is seed health indicators for films but not series episodes?

**Comment by Maio-msdos** [comment]
If you look in https://github.com/popcorn-official/popcorn-android/blob/development/mobile/src/main/java/butter/droid/fragments/ShowDetailFragment.java you'll see no references to health, whereas in https://github.com/popcorn-official/popcorn-android/blob/development/mobile/src/main/java/butter/droid/fragments/MovieDetailFragment.java there is
