### ISSUE TITLE
Update TorrentStream-Android

### ISSUE THREAD

**Issue by MrRory** [popcorn-official/popcorn-android#82]
Looks like sv244's TorrentStream project on maven is abandoned. The project (transferred to [se-bastiaan/TorrentStream-Android](https://github.com/se-bastiaan/TorrentStream-Android)) now uses Jitpack for gradle dependency support and seems to have been updated today. PT is still relying on 1.1.0, latest version is 2.3.0 and is based on the latest version of (j)libtorrent too.

Also, the `TorrentInputStream` that was added looks like it was made for us 💯

**Comment by vzamanillo** [comment]
You are reading my mind...  :smile: I was looking at days ago...

**Comment by MrRory** [comment]
i've tested the `TorrentInputStream` and it seems that together with `setInterestedBytes` it works great, even when using Google Cast. 

also you should take a look at the project of the guy that made the pr: https://github.com/Plunderbund/Plunder
