### ISSUE TITLE
movie not playing due to unsupported video format

### ISSUE THREAD

**Issue by ithakaa** [popcorn-official/popcorn-android#825]
Operating System Version:
Amazon Fire TV Stick

Popcorn Time Version:
tv-arm-release-0.3.6.apk

Download date:
12.11.2022

Download url:
[tv-arm-release-0.3.6.apk](https://github.com/popcorn-official/popcorn-android/releases/download/v0.3.6/tv-arm-release-0.3.6.apk)

Some movies do not play, presented with an error.
Movie not playing due to unsupported video format

**Comment by tehfreak93** [comment]
Same here

**Comment by kiriles90** [comment]
@tehfreak93 If both of those didnt work too then its not really a Popcorn Time issue, rather an issue with the specific video file or device.
