### ISSUE TITLE
Unable to configure opensubtitles.org connection

### ISSUE THREAD

**Issue by shtefko** [popcorn-official/popcorn-android#830]
I have 0.3.6-arm version from guthub releases installed. In settings there is no option to setup the opensubtitles.org connection, just settings for subtitle appearance. Consequently, no subtitles ever load.

![Screenshot_20230114_115038_Popcorn Time](https://user-images.githubusercontent.com/1898211/212468994-9676d7d2-b5c3-4f29-bce8-298e9897d65d.jpg)
![Screenshot_20230114_114955_Popcorn Time](https://user-images.githubusercontent.com/1898211/212468996-5bf278f7-081a-409b-bf3a-91229420625d.jpg)

**Comment by kiriles90** [comment]
Yes. Duplicate of https://github.com/popcorn-official/popcorn-android/issues/802 though so closing this one, join the other issue.

**Comment by superbonaci** [comment]
The problem is still present in [mobile-arm-release-0.3.6.apk](https://github.com/popcorn-official/popcorn-android/releases/download/v0.3.6/mobile-arm-release-0.3.6.apk)

**Comment by kiriles90** [comment]
It also already has an open issue about (#802) so theres no need for 10 more.

**Comment by superbonaci** [comment]
Please release a new apk version.
