### ISSUE TITLE
Stuck on buffering

### ISSUE THREAD

**Issue by alenloncaric** [popcorn-official/popcorn-android#836]
Tried recompiling the whole code and debugging and the every movie i try is stuck at buffering... any idea how i can track this ? or at least cancel if the time expires... 

I can see that Torrent class in the background is moving pieces just nothing comes back in the callbacks

**Comment by kiriles90** [comment]
Hmm maybe @ivan1986 can offer some insight. Closing this since its not an issue with the app but continue the conversation normally below if you want.
