### ISSUE TITLE
Subtitles 

### ISSUE THREAD

**Issue by fuzy75** [popcorn-official/popcorn-android#837]
Hi

On Android app no subtitles

**Comment by fuzy75** [comment]
Hi, thanks.
Do you have any suggestion for Android TV?

**Comment by kiriles90** [comment]
Hi, yes I do.
Check the already open issues before creating a new duplicate one -> https://github.com/popcorn-official/popcorn-android/issues/802  

Any solutions/work-arounds (if they exist, they don't in this case) or any extra info will be there.
