### ISSUE TITLE
Issue with Android TV app streaming

### ISSUE THREAD

**Issue by anilanvesh** [popcorn-official/popcorn-android#839]
Not able to watch content on Android TV with 0.3.6 and 0.3.5
Buffering takes forever. Even if it starts streaming, there is severe lag and screen freezes or app crashes.
Tried on Google Chromecast with Google TV 4K and iFFalcon TV.
Back in 2019 and 2020 app worked fine on Android TVs.
But starting from 2021 since you guys launched new UI, app stopped working on Android TVs
Hope you guys fix issues with Android TV app and release smoother version.

**Comment by anilanvesh** [comment]
Yes, I tried watching trending content with good seeds. Still no use. 
Same content streams without any issues on Android mobile.
I will try the mobile one on big screen and update you on the same.

**Comment by anilanvesh** [comment]
I just checked using Android mobile app on Google Chromecast with Google TV. App installed without any issue. No buffer issue. But app freezes after it starts streaming and remote controls won't work. There's no way we can use mobile app on TV

**Comment by kiriles90** [comment]
The mobile app does work on tv but you mileage might vary depending on the device you are running it on, same like its with mobile devices. Nevertheless.. if it freezes after trying to stream its unusable for you. Maybe try lowering the max connections number (to something a lot less e.g 55 like the desktop app) in case its a cpu usage issue.

**Comment by anilanvesh** [comment]
Okay I will check that out.
