### ISSUE TITLE
Error when reinstall Popcorn 3.6.9 or 3.6.10 on Android

### ISSUE THREAD

**Issue by Marck7886** [popcorn-official/popcorn-android#847]
Hello Guys, 

I tried reinstall popcorn on cellphone, but the is a error:  **No Connection**

I tried install 0.3.6 ARM but not loading 

how can i insert another link on Android by phone?

Operating System Version:

Popcorn Time Version:

3.6.9.201 (it was working) 
3.6.10.202 
and
0.3.6-arm

Download date:

2023

Download url:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

#### Screenshot(s) of issue or error(s) logs (recommended)

![image](https://github.com/popcorn-official/popcorn-android/assets/66749743/f0731008-dfaf-426f-8e54-4e5638070a7f)

**Comment by kiriles90** [comment]
The current version (0.3.6) always was/still is the official app. If it doesn't work for you and you prefer some other app that you were using before **go look for help for that in their own website/repo/forum**. Now please **stop spamming** here and opening multiple issues for the same thing, its your problem that you don't understand the answer not ours so I will just autoclose them.

**Comment by Marck7886** [comment]
No this arm-0.3.6 app is not working for everyone... i'm not spamming... why not put the versions 3.6.10.202 to work again? 

In this arm-0.3.6 version there is no way to download... this is not loading any movie... and this is not ISP... works another devices... **just the android doesn't works...**

**Comment by kiriles90** [comment]
ITS A DIFFERENT DAMN APP FROM DIFFERENT PEOPLE. WHAT DONT YOU UNDERSTAND? GO ASK THEM IN THEIR PLACE.
