### ISSUE TITLE
Can't load Basque subtitles from OpenSubtitles

### ISSUE THREAD

**Issue by urtzai** [popcorn-official/popcorn-android#85]
Version:  2.9
Android version:  6.0.1

#### Expected Behaviour
Show Basque subtitle option in the movie screen

#### Actual Behaviour
It doesn't show any basque subtitle option. Even files are loaded to opensubtitles

#### Steps to repoduce the behaviour

1. Search a movie. For example: Inside out
2. Select the film.
3. Tap subs option menu.

This is the subs file: http://www.opensubtitles.org/eu/subtitles/6803300/inside-out-eu

**Comment by MrRory** [comment]
If it's not showing then we do not get it back from OS. Which generally means that it is not compatible.
