### ISSUE TITLE
No Data Found

### ISSUE THREAD

**Issue by adarabadian** [popcorn-official/popcorn-android#850]
Hey, 

I'm trying to use the app from my galaxy S23 ULTRA or my galaxy s7 tab. 
Both non rooted, the app works on my old device, but not on these. 

I tried downloading several versions and no success. 
I even created apk from my old device and installed it to the new devices and still same result. 

Any chance for help please? 🙏

Operating System Version:
Android 13

Popcorn Time Version:
mobile-arm-release-0.3.6

Download date:
May 22

Download url:
Multiple websites, including this one. Even transfered the app from another device. 

#### Expected Behaviour
To work :) 

#### Actual Behaviour
Prints "No data" / "No connection" 

#### Steps to reproduce the behaviour
Install apk and open app

#### Screenshot(s) of issue or error(s) logs (recommended)
![Screenshot_20230606_213418_Popcorn Time](https://github.com/popcorn-official/popcorn-android/assets/54512886/02d0854c-9750-444a-8ec3-3d8e28dbe1b2)

**Comment by kiriles90** [comment]
Do other categories or search queries produce something or its no data with everything? Does your ISP block the API urls? Have you tried a VPN or a DNS change? Closing this since its not an issue with the app or else everyone would have it but continue the conversation below freely.

**Comment by adarabadian** [comment]
@kiriles90
Thanks for you reply!

Both devices share the same Wifi as the old device which works perfectly.
Tried VPN, same result..

Sorry to bother you, I love the app but can't make it work :(

**Comment by kiriles90** [comment]
Hmm very weird. I'd say uninstall all Popcorn Time apps from the device that they don't work, restart then re-download and reinstall the latest version (0.3.6 atm) from the releases page here in github. Allow any permissions it asks for and given that your ISP doesn't block the API urls since you say the same exact version works on a different device, it should work on this one too. If it doesn't I'm stumped tbh as to what the issue might be.

**Comment by adarabadian** [comment]
Thanks @kiriles90

Done exactly what you said, now I get loading forever
![Uploading Screenshot_20230608_222143_Popcorn Time.jpg…]()

**Comment by adarabadian** [comment]
The problem was the language!
I setted the language to English and works perfectly!

Thanks soooo much!
❤️❤️❤️
