### ISSUE TITLE
No api servers manual control. Api servers aren't updating on Android. add manual control api servers

### ISSUE THREAD

**Issue by bobrobigi** [popcorn-official/popcorn-android#853]
Operating System Version:

Popcorn Time Version:

Download date:

Download url:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
They are updating. Trending is bugged. Search for something or change sorting/filters.
