### ISSUE TITLE
No API selection

### ISSUE THREAD

**Issue by labberdasher** [popcorn-official/popcorn-android#854]
FAQ says "Go to Settings, find the API server section and select one of the suggested APIs from the popup menu that is displayed when you click a Custom API field then restart the app when prompted". My settings (V0.3.6) has no API server selection

**Comment by labberdasher** [comment]
![Screenshot_20230703-210346](https://github.com/popcorn-official/popcorn-android/assets/32078081/65558083-2c54-461f-9e3c-c30be6ee831d)
![Screenshot_20230703-210401](https://github.com/popcorn-official/popcorn-android/assets/32078081/03b133d7-712d-45ab-b5d0-103b084a4527)
![Screenshot_20230703-210410](https://github.com/popcorn-official/popcorn-android/assets/32078081/a17bc7ef-cb40-4e2b-b471-80efb65edb4d)

**Comment by kiriles90** [comment]
That's for the desktop app. There are no custom API fields in the android app but the API urls still autoupdate. Trending is bugged. Search for something or change sorting/filters.
