### ISSUE TITLE
On homepage, top movies keeps loading forever

### ISSUE THREAD

**Issue by singhku1987** [popcorn-official/popcorn-android#863]
Operating System Version:
AndroidTV

Popcorn Time Version:
v0.3.6

Download date:
2023-11-06

Download url:
https://github.com/popcorn-official/popcorn-android/releases/download/v0.3.6/tv-arm-release-0.3.6.apk

#### Expected Behaviour
Homepage should list top movies in the section dedicated for it, just like for TV shows which works just fine.

#### Actual Behaviour
Top movies section on homepage shows just one box continuously showing 'loading' while top TV series is filled with many valid entries.

#### Steps to reproduce the behaviour
1. Download the apk from the given link
2. Install it on the device
3. Open the app
4. Reopen the app for a few attempts
5. Restart the device and reopen the app

#### Screenshot(s) of issue or error(s) logs (recommended)
can't as the device is firestick

**Comment by DreadKnight** [comment]
I'm getting "Loading data..." everywhere...

**Comment by kiriles90** [comment]
Its an API issue, not with the app. The main API atm and the one you are talking about is the RU one so try openning an issue in that repo.
