### ISSUE TITLE
Headphone

### ISSUE THREAD

**Issue by Bassievrucht** [popcorn-official/popcorn-android#95]
Version:  BETA 2.9
Download date:  27-11-2016
Android version:  6.0.1

#### Expected Behaviour
 If I used the beam mode during a movie and I put my headphone into my phone, I'm able to use my headphone for audio.
...

#### Actual Behaviour

...It uses the speakers from my TV 

#### Steps to repoduce the behaviour

1. Start beaming a movie to your tv
2. Put your headphones into your phone

**Comment by MrRory** [comment]
This is not possible, why do you even expect this to happen at all? The video is played on your TV.
