### ISSUE TITLE
Crashing on options 

### ISSUE THREAD

**Issue by luduarte** [popcorn-official/popcorn-android#99]
Version: 0.2.9 
Download date:  30/11/16
Android version: 4.4.4 

#### Expected Behaviour

... the app in theory have to open the options on series: last add, year, a-z

#### Actual Behaviour

... it's crashing down and stop working all the time, include close the app

#### Steps to repoduce the behaviour

1. ... just try to acsses any options and see, everything will close and a window with error will be saying the app stops
2. ... I dindt test on movies options, only see that on series
3. ...

**Comment by vzamanillo** [comment]
Could you please try with the [latest dev build](https://ci.popcorntime.sh/job/Popcorn-Time-Android/)? I think this problem is already solved.
